export const admittedInternalProductCases = [
  "Product service > should export the appropriate linkable configuration",
  "Product service > Product Service > retrieve > should throw an error when an id is not provided",
  "Product service > Product Service > retrieve > should throw an error when product with id does not exist",
  "Product service > Product Service > retrieve > should return a product when product with an id exists",
  "Product service > Product Service > create > should create a product",
  "Product service > Product Service > update > should update a product and its allowed relations",
  "Product service > Product Service > update > should update a product and its allowed relations using selector",
  "Product service > Product Service > update > should update a single product and its allowed relations",
  "Product service > Product Service > update > should throw an error when id is not present",
  "Product service > Product Service > update > should throw an error when product with id does not exist",
  "Product service > Product Service > list > should list all product that match the free text search",
  "Product service > Product Service > list > soft deleted > should list all products that are not deleted",
  "Product service > Product Service > list > soft deleted > should list all products including the deleted",
  "Product service > Product Service > list > relation: tags > should filter by id and including relations",
  "Product service > Product Service > list > relation: tags > should filter by id and without relations",
  "Product service > Product Service > list > relation: categories > should filter by categories relation and scope fields",
  "Product service > Product Service > list > relation: categories > should returns empty array when querying for a category that doesnt exist",
  "Product service > Product Service > list > relation: collections > should filter by collection relation and scope fields",
  "Product service > Product Service > list > relation: collections > should filter by collection when multiple collection ids are passed",
  "Product service > Product Service > list > relation: collections > should returns empty array when querying for a collection that doesnt exist",
  "Product service > Product Service > list > relation: variants > should filter by id and including relations",
  "Product service > Product Service > softDelete > should soft delete a product",
  "Product service > Product Service > restore > should restore a soft deleted product"
];
import { matchesProductCoverage } from "./test/support/product-coverage";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";
import type { Reporter } from "vitest/node";
export const admittedProductTypeCases = [
  "Product service > ProductModuleService product types > listTypes > should return types and count queried by ID",
  "Product service > ProductModuleService product types > listTypes > should return types and count based on the options and filter parameter",
  "Product service > ProductModuleService product types > listTypes > should return only requested fields for types",
  "Product service > ProductModuleService product types > listAndCountTypes > should return types and count queried by ID",
  "Product service > ProductModuleService product types > listAndCountTypes > should return types and count based on the options and filter parameter",
  "Product service > ProductModuleService product types > listAndCountTypes > should return only requested fields for types",
  "Product service > ProductModuleService product types > retrieveType > should return the requested type",
  "Product service > ProductModuleService product types > retrieveType > should return requested attributes when requested through config",
  "Product service > ProductModuleService product types > retrieveType > should throw an error when a type with ID does not exist",
  "Product service > ProductModuleService product types > deleteTypes > should delete the product type given an ID successfully",
  "Product service > ProductModuleService product types > updateTypes > should update the value of the type successfully",
  "Product service > ProductModuleService product types > updateTypes > should throw an error when an id does not exist",
  "Product service > ProductModuleService product types > createTypes > should create a type successfully"
];
export const admittedProductTagCases = [
  "Product service > ProductModuleService product tags > listTags > should return tags and count queried by ID",
  "Product service > ProductModuleService product tags > listTags > should return tags and count based on the options and filter parameter",
  "Product service > ProductModuleService product tags > listTags > should return only requested fields and relations for tags",
  "Product service > ProductModuleService product tags > listTags > should set foreign key to null when relation is select and is null",
  "Product service > ProductModuleService product tags > listAndCountTags > should return tags and count queried by ID",
  "Product service > ProductModuleService product tags > listAndCountTags > should return tags and count based on the options and filter parameter",
  "Product service > ProductModuleService product tags > listAndCountTags > should return only requested fields and relations for tags",
  "Product service > ProductModuleService product tags > retrieveTag > should return the requested tag",
  "Product service > ProductModuleService product tags > retrieveTag > should return requested attributes when requested through config",
  "Product service > ProductModuleService product tags > retrieveTag > should throw an error when a tag with ID does not exist",
  "Product service > ProductModuleService product tags > deleteTags > should delete the product tag given an ID successfully",
  "Product service > ProductModuleService product tags > updateTags > should update the value of the tag successfully",
  "Product service > ProductModuleService product tags > updateTags > should throw an error when an id does not exist",
  "Product service > ProductModuleService product tags > createTags > should create a tag successfully",
  "Product service > ProductModuleService product tags > upsertTags > should upsert tags successfully"
];
export const admittedProductCollectionCases = [
  "Product service > ProductModuleService product collections > listCollections > should return collections queried by ID",
  "Product service > ProductModuleService product collections > listCollections > should return collections based on the options and filter parameter",
  "Product service > ProductModuleService product collections > listCollections > should return only requested fields and relations for collections",
  "Product service > ProductModuleService product collections > listAndCountCollections > should return collections and count queried by ID",
  "Product service > ProductModuleService product collections > listAndCountCollections > should return collections and count based on the options and filter parameter",
  "Product service > ProductModuleService product collections > listAndCountCollections > should return only requested fields and relations for collections",
  "Product service > ProductModuleService product collections > retrieveCollection > should return the requested collection",
  "Product service > ProductModuleService product collections > retrieveCollection > should return requested attributes when requested through config",
  "Product service > ProductModuleService product collections > retrieveCollection > should throw an error when a collection with ID does not exist",
  "Product service > ProductModuleService product collections > deleteCollections > should delete the product collection given an ID successfully",
  "Product service > ProductModuleService product collections > updateCollections > should update the value of the collection successfully",
  "Product service > ProductModuleService product collections > updateCollections > should add products to a collection successfully",
  "Product service > ProductModuleService product collections > updateCollections > should respond with collections when products are updated",
  "Product service > ProductModuleService product collections > updateCollections > should throw an error when an id does not exist",
  "Product service > ProductModuleService product collections > updateCollections > should dissociate existing products when new products are synced",
  "Product service > ProductModuleService product collections > updateCollections > should dissociate all existing products",
  "Product service > ProductModuleService product collections > createCollections > should create a collection successfully",
  "Product service > ProductModuleService product collections > createCollections > should create collection with products successfully"
];
export const admittedProductOptionCases = [
  "Product service > ProductModuleService product options > listOptions > should return options and count queried by ID",
  "Product service > ProductModuleService product options > listOptions > should return options and count based on the options and filter parameter",
  "Product service > ProductModuleService product options > listOptions > should return only requested fields and relations for options",
  "Product service > ProductModuleService product options > listAndCountOptions > should return options and count queried by ID",
  "Product service > ProductModuleService product options > listAndCountOptions > should return options and count based on the options and filter parameter",
  "Product service > ProductModuleService product options > listAndCountOptions > should return only requested fields and relations for options",
  "Product service > ProductModuleService product options > retrieveOption > should return the requested option",
  "Product service > ProductModuleService product options > retrieveOption > should return requested attributes when requested through config",
  "Product service > ProductModuleService product options > retrieveOption > should throw an error when a option with ID does not exist",
  "Product service > ProductModuleService product options > deleteOptions > should delete the product option given an ID successfully",
  "Product service > ProductModuleService product options > updateOptions > should update the title of the option successfully",
  "Product service > ProductModuleService product options > updateOptions > should throw an error when an id does not exist",
  "Product service > ProductModuleService product options > createOptions > should create a option successfully"
];
export const admittedProductVariantCases = [
  "Product service > ProductModuleService product variants > listAndCountVariants > should return variants and count queried by ID",
  "Product service > ProductModuleService product variants > listAndCountVariants > should retrieve variant images including product images not associated with other variants",
  "Product service > ProductModuleService product variants > listAndCountVariants > should return variants and count based on the options and filter parameter",
  "Product service > ProductModuleService product variants > listAndCountVariants > should return only requested fields and relations for variants",
  "Product service > ProductModuleService product variants > retrieveVariant > should return the requested variant",
  "Product service > ProductModuleService product variants > retrieveVariant > should return requested attributes when requested through config",
  "Product service > ProductModuleService product variants > retrieveVariant > should throw an error when a variant with ID does not exist",
  "Product service > ProductModuleService product variants > updateVariants > should update the title of the variant successfully",
  "Product service > ProductModuleService product variants > updateVariants > should do a partial update on the options of a variant successfully",
  "Product service > ProductModuleService product variants > updateVariants > should throw an error when an id does not exist",
  "Product service > ProductModuleService product variants > createVariants > should create variants successfully",
  "Product service > ProductModuleService product variants > createVariants > should correctly associate variants with own product options",
  "Product service > ProductModuleService product variants > createVariants > should throw if there is an existing variant with same options combination",
  "Product service > ProductModuleService product variants > createVariants > should throw if there is an existing variant with same options combination (on update)",
  "Product service > ProductModuleService product variants > softDelete variant > should soft delete a variant and its relations"
];
export const admittedProductCategoryCases = [
  "Product service > ProductModuleService product categories > listCategories > should return categories queried by ID",
  "Product service > ProductModuleService product categories > listCategories > should return categories based on the options and filter parameter",
  "Product service > ProductModuleService product categories > listCategories > should return only requested fields and relations for categories",
  "Product service > ProductModuleService product categories > listCategories > with tree inclusion > should return all descendants of a category",
  "Product service > ProductModuleService product categories > listCategories > with tree inclusion > should return all ancestors of a category",
  "Product service > ProductModuleService product categories > listAndCountCategories > should return categories and count queried by ID",
  "Product service > ProductModuleService product categories > listAndCountCategories > should return categories and count based on the options and filter parameter",
  "Product service > ProductModuleService product categories > listAndCountCategories > should return only requested fields and relations for categories",
  "Product service > ProductModuleService product categories > retrieveCategory > should return the requested category",
  "Product service > ProductModuleService product categories > retrieveCategory > should return requested attributes when requested through config",
  "Product service > ProductModuleService product categories > retrieveCategory > should throw an error when a category with ID does not exist",
  "Product service > ProductModuleService product categories > createCategory > should create a category successfully",
  "Product service > ProductModuleService product categories > createCategory > should append rank from an existing category depending on parent",
  "Product service > ProductModuleService product categories > updateCategory > should update the name of the category successfully",
  "Product service > ProductModuleService product categories > updateCategory > should throw an error when an id does not exist",
  "Product service > ProductModuleService product categories > updateCategory > should reorder rank successfully in the same parent",
  "Product service > ProductModuleService product categories > updateCategory > should reorder rank successfully when changing parent",
  "Product service > ProductModuleService product categories > updateCategory > should reorder rank successfully when changing parent and in first position",
  "Product service > ProductModuleService product categories > deleteCategory > should throw an error when an id does not exist",
  "Product service > ProductModuleService product categories > deleteCategory > should throw an error when it has children",
  "Product service > ProductModuleService product categories > deleteCategory > should reorder siblings rank successfully on deleting"
];
export const admittedInternalCategoryCases = [
  "Product service > Product category Service > list > lists all product categories",
  "Product service > Product category Service > list > scopes product categories by parent_category_id",
  "Product service > Product category Service > list > includes the entire list of descendants when include_descendants_tree is true",
  "Product service > Product category Service > list > includes the entire list of descendants when include_descendants_tree is true for multiple results",
  "Product service > Product category Service > list > includes the entire list of parents when include_ancestors_tree is true",
  "Product service > Product category Service > list > includes the entire list of descendants when include_descendants_tree is true",
  "Product service > Product category Service > list > includes the entire list of descendants an parents when include_descendants_tree and include_ancestors_tree are true",
  "Product service > Product category Service > list > includes the entire list of parents when include_ancestors_tree is true for multiple results",
  "Product service > Product category Service > list > includes the entire list of descendants an parents when include_descendants_tree and include_ancestors_tree are true for multiple results",
  "Product service > Product category Service > list > scopes children when include_descendants_tree is true",
  "Product service > Product category Service > retrieve > should return category for the given id",
  "Product service > Product category Service > retrieve > should throw an error when category with id does not exist",
  "Product service > Product category Service > retrieve > should throw an error when an id is not provided",
  "Product service > Product category Service > retrieve > should return category based on config select param",
  "Product service > Product category Service > retrieve > should return category based on config relation param",
  "Product service > Product category Service > listAndCount > should return categories and count based on take and skip",
  "Product service > Product category Service > listAndCount > should return all product categories and count",
  "Product service > Product category Service > listAndCount > should only return categories that are scoped by parent_category_id",
  "Product service > Product category Service > listAndCount > should includes descendants when include_descendants_tree is true",
  "Product service > Product category Service > listAndCount > should filter out children when include_descendants_tree is true",
  "Product service > Product category Service > create > should create a category successfully",
  "Product service > Product category Service > create > should append rank from an existing category depending on parent",
  "Product service > Product category Service > update > should update the name of the category successfully",
  "Product service > Product category Service > update > should throw an error when an id does not exist",
  "Product service > Product category Service > update > should reorder rank successfully in the same parent",
  "Product service > Product category Service > update > should reorder rank successfully when changing parent",
  "Product service > Product category Service > update > should reorder rank successfully when changing parent and in first position",
  "Product service > Product category Service > update > should update the mpath of the full descendent tree successfully when moving the grand parent in the hierarchy",
  "Product service > Product category Service > delete > should throw an error when an id does not exist",
  "Product service > Product category Service > delete > should throw an error when it has children",
  "Product service > Product category Service > delete > should reorder siblings rank successfully on deleting"
];
export const admittedProductCases = [
  ...admittedInternalProductCases,
  ...admittedInternalCategoryCases,
  ...admittedProductOptionCases, ...admittedProductVariantCases, ...admittedProductCategoryCases,
  ...admittedProductCollectionCases,
  ...admittedProductTagCases,
  ...admittedProductTypeCases,
  "Product injected event bus > ProductModuleService Events > Product Deletion > should emit all cascade delete events when soft deleting a product",
  "Product injected event bus > ProductModuleService Events > Delete Operations - Base Service Automatic Events > should emit delete events for all entity types via base service",
  "Product service > ProductModuleService products > softDelete > should soft delete a product and its cascaded relations",
  "Product service > ProductModuleService products > softDelete > should retrieve soft-deleted products if filtered on deleted_at",
  "Product service > ProductModuleService products > restore > should restore a soft deleted product and its cascaded relations",
  "Product injected event bus > ProductModuleService Events > Product Creation > should emit all related events when creating a product with full relations",
  "Product injected event bus > ProductModuleService Events > Product Update > should emit cascade events when updating product with relations",
  "Product injected event bus > ProductModuleService Events > Product Variant Operations > should emit PRODUCT_VARIANT_CREATED event only when creating standalone variant",
  "Product injected event bus > ProductModuleService Events > Product Variant Operations > should emit PRODUCT_VARIANT_UPDATED event only when updating variant",
  "Product injected event bus > ProductModuleService Events > Product Tag Operations > should emit PRODUCT_TAG_CREATED event on createProductTags",
  "Product injected event bus > ProductModuleService Events > Product Tag Operations > should emit PRODUCT_TAG_UPDATED event on updateProductTags",
  "Product injected event bus > ProductModuleService Events > Product Tag Operations > should emit appropriate events on upsertProductTags",
  "Product injected event bus > ProductModuleService Events > Product Type Operations > should emit PRODUCT_TYPE_CREATED event on createProductTypes",
  "Product injected event bus > ProductModuleService Events > Product Type Operations > should emit PRODUCT_TYPE_UPDATED event on updateProductTypes",
  "Product injected event bus > ProductModuleService Events > Product Type Operations > should emit appropriate events on upsertProductTypes",
  "Product injected event bus > ProductModuleService Events > Product Option Operations > should emit PRODUCT_OPTION_CREATED event on createProductOptions",
  "Product injected event bus > ProductModuleService Events > Product Option Operations > should emit PRODUCT_OPTION_UPDATED event on updateProductOptions",
  "Product injected event bus > ProductModuleService Events > Product Option Operations > should emit appropriate events on upsertProductOptions",
  "Product injected event bus > ProductModuleService Events > Product Option Value Operations > should emit PRODUCT_OPTION_VALUE_UPDATED event on updateProductOptionValues",
  "Product injected event bus > ProductModuleService Events > Product Collection Operations > should emit PRODUCT_COLLECTION_CREATED event on createProductCollections",
  "Product injected event bus > ProductModuleService Events > Product Collection Operations > should emit PRODUCT_COLLECTION_UPDATED event on updateProductCollections",
  "Product injected event bus > ProductModuleService Events > Product Collection Operations > should emit appropriate events on upsertProductCollections",
  "Product injected event bus > ProductModuleService Events > Product Category Operations > should emit PRODUCT_CATEGORY_CREATED event on createProductCategories",
  "Product injected event bus > ProductModuleService Events > Product Category Operations > should emit PRODUCT_CATEGORY_UPDATED event on updateProductCategories",
  "Product injected event bus > ProductModuleService Events > Product Category Operations > should emit appropriate events on upsertProductCategories",
  "Product service > ProductModuleService products > update > should update multiple products",
  "Product service > ProductModuleService products > update > should update a product and upsert relations that are not created yet",
  "Product service > ProductModuleService products > update > should upsert variants (update one and create one)",
  "Product service > ProductModuleService products > update > should preserve option and value identity on update",
  "Product service > ProductModuleService products > update > should add relationships to a product",
  "Product service > ProductModuleService products > update > should upsert a product type when type object is passed",
  "Product service > ProductModuleService products > update > should replace relationships of a product",
  "Product service > ProductModuleService products > update > should remove relationships of a product",
  "Product service > ProductModuleService products > update > should throw an error when product ID does not exist",
  "Product service > ProductModuleService products > update > should update, create and delete variants",
  "Product service > ProductModuleService products > update > should do a partial update on the options of a variant successfully",
  "Product service > ProductModuleService products > update > should create a variant with id that was passed if it does not exist",
  "Product service > ProductModuleService products > update > should simultaneously update options and variants",
  "Product service > ProductModuleService products > update > should throw an error when some tag id does not exist",
  "Product service > ProductModuleService products > update > should throw an error when some category id does not exist",
  "Product service > ProductModuleService products > update > should throw an error when collection id does not exist",
  "Product service > ProductModuleService products > update > should throw an error when type id does not exist",
  "Product service > ProductModuleService products > update > should throw if two variants have the same options combination",
  "Product service > ProductModuleService products > update > should throw if a variant doesn't have all options set",
  "Product service > ProductModuleService products > update > should throw if a variant uses a non-existing option",
  "Product service > ProductModuleService products > create > should create a product",
  "Product service > ProductModuleService products > create > should throw because variant doesn't have all options set",
  "Product service > ProductModuleService products > list > should return a list of products scoped by collection id",
  "Product service > ProductModuleService products > list > should return a list of products scoped by variant options",
  "Product service > ProductModuleService products > list > should return empty array when querying for a collection that doesnt exist",
  "Product service > ProductModuleService products > images > should create images with correct rank",
  "Product service > ProductModuleService products > images > should update images with correct rank",
  "Product service > ProductModuleService products > images > should delete images if empty array is passed on update",
  "Product service > ProductModuleService products > images > should retrieve images in the correct order consistently",
  "Product service > ProductModuleService products > images > should retrieve images ordered by rank",
  "Product service > ProductModuleService products > images > should populate variant.images when variants.images relation is requested",
];
export const productCoverage = (expected: readonly string[]): Reporter => {
  const executed: string[] = [];
  return {
    onTestRunStart() { executed.length = 0; },
    onTestCaseResult(test) { if (test.result().state !== "skipped") executed.push(test.fullName); },
    onTestRunEnd() {
      if (!matchesProductCoverage(expected, executed)) {
        throw new Error("Product upstream coverage mismatch: expected all " + expected.length + " admitted cases to execute");
      }
    },
  };
};
export default defineConfig({
  resolve: { alias: [
    { find: /^@medusajs\/test-utils$/, replacement: fileURLToPath(new URL("./test/support/runner.ts", import.meta.url)) },
    { find: /^@services$/, replacement: fileURLToPath(new URL("../medusa-product/src/services/index.ts", import.meta.url)) },
    { find: /^@models$/, replacement: fileURLToPath(new URL("../medusa-product/src/models/index.ts", import.meta.url)) },
    { find: /^@types$/, replacement: fileURLToPath(new URL("../medusa-product/src/types/index.ts", import.meta.url)) },
    { find: "cloudflare:workers", replacement: fileURLToPath(new URL("../persistence-postgres/test/cloudflareWorkersStub.ts", import.meta.url)) },
  ] },
  test: { env: { FLAREX_PRODUCT_RESOURCES: "scale" }, globals: true, maxWorkers: 1, fileParallelism: false, include: ["test/product-upstream.test.ts"],
    reporters: ["default", productCoverage(admittedProductCases)],
    hookTimeout: 120000, testTimeout: 100000,
  },
});
