export const MAX_INVALIDATION_DEPENDENCY_LOOKUPS = 65_536;
export const MAX_INVALIDATION_AFFECTED_QUERIES = 4_096;
export const MAX_INVALIDATION_AFFECTED_QUERY_SENTINEL = 4_097;

export const MAX_QUERY_DEPENDENCY_KEYS = 8_192;
export const MAX_QUERY_DEPENDENCY_SENTINEL = 8_193;
export const MAX_QUERY_DEPENDENCY_BYTES = 4 * 1_024 * 1_024;
