import {
  DECLARATIVE_V2_EXECUTABLE_CORE_IDENTITY_V1,
  DECLARATIVE_V2_VERIFIER_DIAGNOSTIC_IDENTITY_V1,
  DECLARATIVE_V2_VERIFIER_UNICODE_IDENTITY_V1,
} from "./declarativeV2VerifierV1.contract";
import {
  GENERATED_DECLARATIVE_V2_VERIFIER_MANIFEST_V1,
} from "./declarativeV2VerifierV1.generated";

function freezeOwnedContractGraph<T>(value: T): T {
  if (value !== null && typeof value === "object") {
    for (const member of Object.values(value)) freezeOwnedContractGraph(member);
    Object.freeze(value);
  }
  return value;
}

export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_IDENTITY_V1 =
  "flarex.declarative-v2/verifier-executable-table/v1" as const;
export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_MAGIC_V1 =
  "FLXDVX1\0" as const;
export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_VERSION_V1 = 1 as const;
export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_HEADER_BYTES_V1 =
  128 as const;
export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_SECTION_BYTES_V1 =
  24 as const;
export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_ALIGNMENT_V1 = 8 as const;
export const DECLARATIVE_V2_VERIFIER_TRANSITION_QUANTUM_V1 = 1_024 as const;

export const DECLARATIVE_V2_TOKEN_KINDS_V1 = [
  { id: 1, name: "identifier" },
  { id: 2, name: "keyword" },
  { id: 3, name: "number" },
  { id: 4, name: "bigint" },
  { id: 5, name: "string" },
  { id: 6, name: "template" },
  { id: 7, name: "regexp" },
  { id: 8, name: "punctuator" },
  { id: 9, name: "eof" },
] as const;

export type DeclarativeV2TokenKindV1 =
  typeof DECLARATIVE_V2_TOKEN_KINDS_V1[number]["name"];

export const DECLARATIVE_V2_LEXICAL_BYTE_CLASSES_V1 = [
  { id: 1, name: "nul", bytes: [0x00] },
  { id: 2, name: "lineTerminator", bytes: [0x0a, 0x0d] },
  { id: 3, name: "asciiWhitespace", bytes: [0x09, 0x0b, 0x0c, 0x20] },
  { id: 4, name: "decimalDigit", ranges: [[0x30, 0x39]] },
  { id: 5, name: "asciiIdentifierStart", ranges: [[0x41, 0x5a], [0x61, 0x7a]], bytes: [0x24, 0x5f] },
  { id: 6, name: "quote", bytes: [0x22, 0x27] },
  { id: 7, name: "templateQuote", bytes: [0x60] },
  { id: 8, name: "slash", bytes: [0x2f] },
  { id: 9, name: "backslash", bytes: [0x5c] },
  { id: 10, name: "punctuator", bytes: [0x21, 0x25, 0x26, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x5b, 0x5d, 0x7b, 0x7c, 0x7d, 0x7e] },
  { id: 11, name: "nonAscii", ranges: [[0x80, 0xff]] },
  { id: 12, name: "other", ranges: [[0x01, 0xff]] },
] as const;

export const DECLARATIVE_V2_KEYWORDS_V1 = [
  "async",
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "null",
  "of",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "undefined",
  "var",
  "void",
  "while",
  "with",
  "yield",
] as const;

export const DECLARATIVE_V2_PUNCTUATORS_V1 = [
  ">>>=",
  "**=",
  "&&=",
  "||=",
  "??=",
  "===",
  "!==",
  ">>>",
  "<<=",
  ">>=",
  "=>",
  "==",
  "!=",
  "<=",
  ">=",
  "++",
  "--",
  "**",
  "&&",
  "||",
  "??",
  "?.",
  "<<",
  ">>",
  "+=",
  "-=",
  "*=",
  "/=",
  "%=",
  "&=",
  "|=",
  "^=",
  "...",
  "{",
  "}",
  "(",
  ")",
  "[",
  "]",
  ".",
  ";",
  ",",
  "<",
  ">",
  "+",
  "-",
  "*",
  "/",
  "%",
  "&",
  "|",
  "^",
  "!",
  "~",
  "?",
  ":",
  "=",
] as const;

export const DECLARATIVE_V2_REGEX_GOAL_AFTER_V1 = [
  { id: 1, token: "identifier", goal: "division" },
  { id: 2, token: "number", goal: "division" },
  { id: 3, token: "bigint", goal: "division" },
  { id: 4, token: "string", goal: "division" },
  { id: 5, token: "template", goal: "division" },
  { id: 6, token: "regexp", goal: "division" },
  { id: 7, token: ")", goal: "division" },
  { id: 8, token: "]", goal: "division" },
  { id: 9, token: "}", goal: "division" },
  { id: 10, token: "++", goal: "division" },
  { id: 11, token: "--", goal: "division" },
] as const;

export const DECLARATIVE_V2_ASI_RULES_V1 = [
  { id: 1, context: 1, action: 1, name: "eof/insert" },
  { id: 2, context: 2, action: 1, name: "closeBrace/insert" },
  {
    id: 3,
    context: 3,
    action: 2,
    name: "restrictedBreak/insertOnLineTerminator",
  },
  {
    id: 4,
    context: 4,
    action: 2,
    name: "restrictedContinue/insertOnLineTerminator",
  },
  {
    id: 5,
    context: 5,
    action: 2,
    name: "restrictedReturn/insertOnLineTerminator",
  },
  {
    id: 6,
    context: 6,
    action: 3,
    name: "restrictedThrow/rejectOnLineTerminator",
  },
  {
    id: 7,
    context: 7,
    action: 3,
    name: "postfixIncrement/rejectOnLineTerminator",
  },
  {
    id: 8,
    context: 8,
    action: 3,
    name: "postfixDecrement/rejectOnLineTerminator",
  },
  { id: 9, context: 9, action: 1, name: "lineTerminator/insert" },
] as const;

export const DECLARATIVE_V2_TEMPLATE_TRANSITIONS_V1 = [
  {
    id: 1,
    state: 1,
    input: 1,
    nextState: 0,
    action: 1,
    name: "template/backtick/code",
  },
  {
    id: 2,
    state: 1,
    input: 2,
    nextState: 2,
    action: 2,
    name: "template/dollarBrace/substitution",
  },
  {
    id: 3,
    state: 1,
    input: 3,
    nextState: 3,
    action: 3,
    name: "template/escape/templateEscape",
  },
  {
    id: 4,
    state: 3,
    input: 4,
    nextState: 1,
    action: 4,
    name: "templateEscape/scalar/template",
  },
  {
    id: 5,
    state: 2,
    input: 5,
    nextState: 1,
    action: 5,
    name: "substitution/closeAtDepthZero/template",
  },
] as const;

export const DECLARATIVE_V2_UTF8_TRANSITIONS_V1 = [
  { id: 1, state: 0, byteClass: 1, nextState: 0, action: 1 },
  { id: 2, state: 0, byteClass: 2, nextState: 1, action: 2 },
  { id: 3, state: 0, byteClass: 3, nextState: 2, action: 2 },
  { id: 4, state: 0, byteClass: 4, nextState: 3, action: 2 },
  { id: 5, state: 1, byteClass: 5, nextState: 0, action: 3 },
  { id: 6, state: 2, byteClass: 5, nextState: 4, action: 2 },
  { id: 7, state: 4, byteClass: 5, nextState: 0, action: 3 },
  { id: 8, state: 3, byteClass: 5, nextState: 6, action: 2 },
  { id: 9, state: 6, byteClass: 5, nextState: 7, action: 2 },
  { id: 10, state: 7, byteClass: 5, nextState: 0, action: 3 },
  { id: 11, state: 1, byteClass: 6, nextState: 0, action: 4 },
  { id: 12, state: 2, byteClass: 6, nextState: 0, action: 4 },
  { id: 13, state: 3, byteClass: 6, nextState: 0, action: 4 },
  { id: 14, state: 4, byteClass: 6, nextState: 0, action: 4 },
  { id: 15, state: 6, byteClass: 6, nextState: 0, action: 4 },
  { id: 16, state: 7, byteClass: 6, nextState: 0, action: 4 },
] as const;

export const DECLARATIVE_V2_NUMBER_TRANSITIONS_V1 = [
  { id: 1, state: 0, input: 1, nextState: 1, action: 1 },
  { id: 2, state: 1, input: 1, nextState: 1, action: 1 },
  { id: 3, state: 1, input: 2, nextState: 2, action: 1 },
  { id: 4, state: 1, input: 3, nextState: 3, action: 1 },
  { id: 5, state: 2, input: 1, nextState: 2, action: 1 },
  { id: 6, state: 2, input: 3, nextState: 3, action: 1 },
  { id: 7, state: 3, input: 4, nextState: 4, action: 1 },
  { id: 8, state: 3, input: 1, nextState: 5, action: 1 },
  { id: 9, state: 4, input: 1, nextState: 5, action: 1 },
  { id: 10, state: 5, input: 1, nextState: 5, action: 1 },
  { id: 11, state: 1, input: 5, nextState: 1, action: 1 },
  { id: 12, state: 2, input: 5, nextState: 2, action: 1 },
  { id: 13, state: 5, input: 5, nextState: 5, action: 1 },
] as const;

export const DECLARATIVE_V2_MODULE_PARSER_STATES_V1 = [
  { id: 1, name: "moduleStart" },
  { id: 2, name: "afterDirective" },
  { id: 3, name: "afterImport" },
  { id: 4, name: "afterDeclaration" },
  { id: 5, name: "complete" },
  { id: 6, name: "bodyExpectsOperand" },
  { id: 7, name: "bodyExpectsOperator" },
] as const;

export const DECLARATIVE_V2_PARSER_TERMINALS_V1 = [
  { id: 1, name: "directive" },
  { id: 2, name: "import" },
  { id: 3, name: "declaration" },
  { id: 4, name: "eof" },
  { id: 5, name: "operand" },
  { id: 6, name: "prefix" },
  { id: 7, name: "binary" },
  { id: 8, name: "openParen" },
  { id: 9, name: "closeParen" },
  { id: 10, name: "openBracket" },
  { id: 11, name: "closeBracket" },
  { id: 12, name: "openBrace" },
  { id: 13, name: "closeBrace" },
  { id: 14, name: "separator" },
  { id: 15, name: "ternary" },
  { id: 16, name: "statementPrefix" },
  { id: 17, name: "statementBoundary" },
  { id: 18, name: "member" },
  { id: 19, name: "postfix" },
  { id: 20, name: "await" },
  { id: 21, name: "template" },
  { id: 22, name: "bodyEof" },
] as const;

export const DECLARATIVE_V2_PARSER_NONTERMINALS_V1 = [
  { id: 1, name: "module" },
  { id: 2, name: "moduleItems" },
  { id: 3, name: "moduleItem" },
  { id: 4, name: "functionBody" },
  { id: 5, name: "statements" },
  { id: 6, name: "statement" },
  { id: 7, name: "expression" },
] as const;

export const DECLARATIVE_V2_PARSER_NONTERMINAL_FLAG_V1 = 0x8000_0000 as const;

export const DECLARATIVE_V2_PARSER_PRODUCTIONS_V1 = [
  { id: 1, lhs: 1, rhsLength: 2, semanticOpcode: 7, rhs: [0x8000_0002, 4, 0, 0] },
  { id: 2, lhs: 2, rhsLength: 2, semanticOpcode: 8, rhs: [0x8000_0002, 0x8000_0003, 0, 0] },
  { id: 3, lhs: 2, rhsLength: 0, semanticOpcode: 9, rhs: [0, 0, 0, 0] },
  { id: 4, lhs: 3, rhsLength: 1, semanticOpcode: 1, rhs: [1, 0, 0, 0] },
  { id: 5, lhs: 3, rhsLength: 1, semanticOpcode: 2, rhs: [2, 0, 0, 0] },
  { id: 6, lhs: 3, rhsLength: 1, semanticOpcode: 3, rhs: [3, 0, 0, 0] },
  { id: 7, lhs: 4, rhsLength: 3, semanticOpcode: 14, rhs: [12, 0x8000_0005, 13, 0] },
  { id: 8, lhs: 5, rhsLength: 2, semanticOpcode: 8, rhs: [0x8000_0005, 0x8000_0006, 0, 0] },
  { id: 9, lhs: 5, rhsLength: 0, semanticOpcode: 9, rhs: [0, 0, 0, 0] },
  { id: 10, lhs: 6, rhsLength: 2, semanticOpcode: 14, rhs: [0x8000_0007, 14, 0, 0] },
  { id: 11, lhs: 6, rhsLength: 1, semanticOpcode: 14, rhs: [0x8000_0007, 0, 0, 0] },
  { id: 12, lhs: 7, rhsLength: 1, semanticOpcode: 13, rhs: [5, 0, 0, 0] },
  { id: 13, lhs: 7, rhsLength: 2, semanticOpcode: 13, rhs: [6, 0x8000_0007, 0, 0] },
  { id: 14, lhs: 7, rhsLength: 3, semanticOpcode: 13, rhs: [0x8000_0007, 7, 0x8000_0007, 0] },
] as const;

export const DECLARATIVE_V2_MODULE_PARSER_ACTIONS_V1 = [
  { id: 1, state: 1, terminal: 1, action: 1, value: 2 },
  { id: 2, state: 1, terminal: 2, action: 1, value: 3 },
  { id: 3, state: 1, terminal: 3, action: 1, value: 4 },
  { id: 4, state: 1, terminal: 4, action: 3, value: 0 },
  { id: 5, state: 2, terminal: 1, action: 1, value: 2 },
  { id: 6, state: 2, terminal: 2, action: 1, value: 3 },
  { id: 7, state: 2, terminal: 3, action: 1, value: 4 },
  { id: 8, state: 2, terminal: 4, action: 3, value: 0 },
  { id: 9, state: 3, terminal: 2, action: 1, value: 3 },
  { id: 10, state: 3, terminal: 3, action: 1, value: 4 },
  { id: 11, state: 3, terminal: 4, action: 3, value: 0 },
  { id: 12, state: 4, terminal: 3, action: 1, value: 4 },
  { id: 13, state: 4, terminal: 4, action: 3, value: 0 },
  { id: 14, state: 6, terminal: 5, action: 1, value: 7 },
  { id: 15, state: 6, terminal: 6, action: 1, value: 6 },
  { id: 16, state: 6, terminal: 8, action: 1, value: 6 },
  { id: 17, state: 6, terminal: 10, action: 1, value: 6 },
  { id: 18, state: 6, terminal: 12, action: 1, value: 6 },
  { id: 19, state: 6, terminal: 14, action: 1, value: 6 },
  { id: 20, state: 6, terminal: 16, action: 1, value: 6 },
  { id: 21, state: 6, terminal: 17, action: 1, value: 6 },
  { id: 22, state: 6, terminal: 20, action: 1, value: 6 },
  { id: 23, state: 6, terminal: 21, action: 1, value: 7 },
  { id: 24, state: 7, terminal: 7, action: 1, value: 6 },
  { id: 25, state: 7, terminal: 8, action: 1, value: 6 },
  { id: 26, state: 7, terminal: 9, action: 1, value: 7 },
  { id: 27, state: 7, terminal: 11, action: 1, value: 7 },
  { id: 28, state: 7, terminal: 13, action: 1, value: 7 },
  { id: 29, state: 7, terminal: 14, action: 1, value: 6 },
  { id: 30, state: 7, terminal: 15, action: 1, value: 6 },
  { id: 31, state: 7, terminal: 17, action: 1, value: 6 },
  { id: 32, state: 7, terminal: 18, action: 1, value: 6 },
  { id: 33, state: 7, terminal: 19, action: 1, value: 7 },
  { id: 34, state: 7, terminal: 22, action: 3, value: 0 },
  { id: 35, state: 6, terminal: 9, action: 1, value: 7 },
  { id: 36, state: 6, terminal: 11, action: 1, value: 7 },
  { id: 37, state: 6, terminal: 13, action: 1, value: 7 },
  { id: 38, state: 6, terminal: 22, action: 3, value: 0 },
  { id: 39, state: 7, terminal: 12, action: 1, value: 6 },
  { id: 40, state: 7, terminal: 16, action: 1, value: 6 },
  { id: 41, state: 7, terminal: 21, action: 1, value: 7 },
] as const;

export const DECLARATIVE_V2_MODULE_PARSER_GOTOS_V1 = [
  { id: 1, state: 1, nonterminal: 1, nextState: 5 },
  { id: 2, state: 1, nonterminal: 2, nextState: 1 },
  { id: 3, state: 1, nonterminal: 3, nextState: 1 },
  { id: 4, state: 6, nonterminal: 7, nextState: 7 },
  { id: 5, state: 6, nonterminal: 6, nextState: 6 },
  { id: 6, state: 6, nonterminal: 5, nextState: 6 },
  { id: 7, state: 6, nonterminal: 4, nextState: 7 },
] as const;

export const DECLARATIVE_V2_OPERATOR_PRECEDENCE_V1 = [
  { id: 1, spelling: "=", precedence: 1, associativity: 2 },
  { id: 2, spelling: "+=", precedence: 1, associativity: 2 },
  { id: 3, spelling: "-=", precedence: 1, associativity: 2 },
  { id: 4, spelling: "*=", precedence: 1, associativity: 2 },
  { id: 5, spelling: "/=", precedence: 1, associativity: 2 },
  { id: 6, spelling: "%=", precedence: 1, associativity: 2 },
  { id: 7, spelling: "**=", precedence: 1, associativity: 2 },
  { id: 8, spelling: "<<=", precedence: 1, associativity: 2 },
  { id: 9, spelling: ">>=", precedence: 1, associativity: 2 },
  { id: 10, spelling: ">>>=", precedence: 1, associativity: 2 },
  { id: 11, spelling: "&=", precedence: 1, associativity: 2 },
  { id: 12, spelling: "|=", precedence: 1, associativity: 2 },
  { id: 13, spelling: "^=", precedence: 1, associativity: 2 },
  { id: 14, spelling: "&&=", precedence: 1, associativity: 2 },
  { id: 15, spelling: "||=", precedence: 1, associativity: 2 },
  { id: 16, spelling: "??=", precedence: 1, associativity: 2 },
  { id: 17, spelling: "??", precedence: 2, associativity: 1 },
  { id: 18, spelling: "||", precedence: 3, associativity: 1 },
  { id: 19, spelling: "&&", precedence: 4, associativity: 1 },
  { id: 20, spelling: "|", precedence: 5, associativity: 1 },
  { id: 21, spelling: "^", precedence: 6, associativity: 1 },
  { id: 22, spelling: "&", precedence: 7, associativity: 1 },
  { id: 23, spelling: "===", precedence: 8, associativity: 1 },
  { id: 24, spelling: "!==", precedence: 8, associativity: 1 },
  { id: 25, spelling: "==", precedence: 8, associativity: 1 },
  { id: 26, spelling: "!=", precedence: 8, associativity: 1 },
  { id: 27, spelling: "<", precedence: 9, associativity: 1 },
  { id: 28, spelling: ">", precedence: 9, associativity: 1 },
  { id: 29, spelling: "<=", precedence: 9, associativity: 1 },
  { id: 30, spelling: ">=", precedence: 9, associativity: 1 },
  { id: 31, spelling: "<<", precedence: 10, associativity: 1 },
  { id: 32, spelling: ">>", precedence: 10, associativity: 1 },
  { id: 33, spelling: ">>>", precedence: 10, associativity: 1 },
  { id: 34, spelling: "+", precedence: 11, associativity: 1 },
  { id: 35, spelling: "-", precedence: 11, associativity: 1 },
  { id: 36, spelling: "*", precedence: 12, associativity: 1 },
  { id: 37, spelling: "/", precedence: 12, associativity: 1 },
  { id: 38, spelling: "%", precedence: 12, associativity: 1 },
  { id: 39, spelling: "**", precedence: 13, associativity: 2 },
] as const;

export const DECLARATIVE_V2_PARSER_RECOVERY_V1 = [
  { id: 1, state: 1, terminal: 4, action: 1, consumes: 0 },
  { id: 2, state: 2, terminal: 4, action: 1, consumes: 0 },
  { id: 3, state: 3, terminal: 4, action: 1, consumes: 0 },
  { id: 4, state: 4, terminal: 4, action: 1, consumes: 0 },
] as const;

export const DECLARATIVE_V2_SEMANTIC_ACTIONS_V1 = [
  { id: 1, opcode: 1, name: "recordDirective" },
  { id: 2, opcode: 2, name: "recordImport" },
  { id: 3, opcode: 3, name: "recordDeclaration" },
  { id: 4, opcode: 4, name: "recordCall" },
  { id: 5, opcode: 5, name: "recordCapability" },
  { id: 6, opcode: 6, name: "recordDiagnostic" },
  { id: 7, opcode: 7, name: "finishModule" },
  { id: 8, opcode: 8, name: "appendModuleItem" },
  { id: 9, opcode: 9, name: "emptyModuleItems" },
  { id: 10, opcode: 10, name: "pushControlFrame" },
  { id: 11, opcode: 11, name: "popControlFrame" },
  { id: 12, opcode: 12, name: "finishLexing" },
  { id: 13, opcode: 13, name: "validateExpression" },
  { id: 14, opcode: 14, name: "validateStatement" },
  { id: 15, opcode: 15, name: "orderOutput" },
] as const;

export const DECLARATIVE_V2_SAFE_ABI_LOOKUP_V1 = [
  "authGetUserIdentity",
  "bytesConcat",
  "bytesGet",
  "bytesSet",
  "bytesSlice",
  "databaseDelete",
  "databaseGet",
  "databaseInsert",
  "databasePatch",
  "databaseReplace",
  "errorCode",
  "errorCreate",
  "errorData",
  "errorMessage",
  "queryCollect",
  "queryFirst",
  "queryOrder",
  "queryPaginate",
  "queryStart",
  "queryTake",
  "queryUnique",
  "queryWithIndex",
  "rangeEq",
  "rangeGt",
  "rangeGte",
  "rangeLt",
  "rangeLte",
  "runMutation",
  "runQuery",
  "sameValue",
  "sameValueZero",
  "scalarToString",
  "stringCodePointAt",
  "stringFromCodePoint",
  "valueDelete",
  "valueGet",
  "valueHas",
  "valueOwnKeys",
  "valueResizeArray",
  "valueSet",
  "valueSpreadArray",
  "valueSpreadObject",
] as const;

export const DECLARATIVE_V2_CONTEXT_MEMBER_ABI_LOWERINGS_V1 = [
  {
    id: 1,
    memberPath: ["db", "get"],
    operation: "databaseGet",
    argumentCounts: [1],
  },
  {
    id: 2,
    memberPath: ["db", "insert"],
    operation: "databaseInsert",
    argumentCounts: [2],
  },
  {
    id: 3,
    memberPath: ["db", "patch"],
    operation: "databasePatch",
    argumentCounts: [2],
  },
  {
    id: 4,
    memberPath: ["db", "replace"],
    operation: "databaseReplace",
    argumentCounts: [2],
  },
  {
    id: 5,
    memberPath: ["db", "delete"],
    operation: "databaseDelete",
    argumentCounts: [1],
  },
  {
    id: 6,
    memberPath: ["runQuery"],
    operation: "runQuery",
    argumentCounts: [1, 2],
  },
  {
    id: 7,
    memberPath: ["runMutation"],
    operation: "runMutation",
    argumentCounts: [1, 2],
  },
] as const;

export const DECLARATIVE_V2_PLATFORM_IMPORT_ALLOWLIST_V1 = [
  "flarex:platform",
] as const;

/*
 * R2a canonical grammar source.
 *
 * The older module/body rows below remain encoded only as a byte-compatible
 * bridge for the provisional, production-unreachable R1 runtime. They are not
 * the grammar authority. R2b removes that handwritten consumer and executes
 * only the canonical LR rows generated from this source.
 */
export const DECLARATIVE_V2_CANONICAL_TERMINALS_V1 = [
  { id: 1, name: "eof" },
  { id: 2, name: "identifier" },
  { id: 3, name: "number" },
  { id: 4, name: "bigint" },
  { id: 5, name: "string" },
  { id: 6, name: "templateNoSubstitution" },
  { id: 7, name: "templateHead" },
  { id: 8, name: "templateMiddle" },
  { id: 9, name: "templateTail" },
  { id: 10, name: "true" },
  { id: 11, name: "false" },
  { id: 12, name: "null" },
  { id: 13, name: "undefined" },
  { id: 14, name: "async" },
  { id: 15, name: "await" },
  { id: 16, name: "break" },
  { id: 17, name: "case" },
  { id: 18, name: "catch" },
  { id: 19, name: "const" },
  { id: 20, name: "continue" },
  { id: 21, name: "default" },
  { id: 22, name: "do" },
  { id: 23, name: "else" },
  { id: 24, name: "export" },
  { id: 25, name: "finally" },
  { id: 26, name: "for" },
  { id: 27, name: "from" },
  { id: 28, name: "function" },
  { id: 29, name: "if" },
  { id: 30, name: "import" },
  { id: 31, name: "let" },
  { id: 32, name: "of" },
  { id: 33, name: "return" },
  { id: 34, name: "switch" },
  { id: 35, name: "throw" },
  { id: 36, name: "try" },
  { id: 37, name: "typeof" },
  { id: 38, name: "void" },
  { id: 39, name: "delete" },
  { id: 40, name: "while" },
  { id: 41, name: "{" },
  { id: 42, name: "}" },
  { id: 43, name: "(" },
  { id: 44, name: ")" },
  { id: 45, name: "[" },
  { id: 46, name: "]" },
  { id: 47, name: ";" },
  { id: 48, name: "," },
  { id: 49, name: ":" },
  { id: 50, name: "?" },
  { id: 51, name: "." },
  { id: 52, name: "?." },
  { id: 53, name: "..." },
  { id: 54, name: "=" },
  { id: 55, name: "+=" },
  { id: 56, name: "-=" },
  { id: 57, name: "*=" },
  { id: 58, name: "/=" },
  { id: 59, name: "%=" },
  { id: 60, name: "**=" },
  { id: 61, name: "<<=" },
  { id: 62, name: ">>=" },
  { id: 63, name: ">>>=" },
  { id: 64, name: "&=" },
  { id: 65, name: "|=" },
  { id: 66, name: "^=" },
  { id: 67, name: "&&=" },
  { id: 68, name: "||=" },
  { id: 69, name: "??=" },
  { id: 70, name: "??" },
  { id: 71, name: "||" },
  { id: 72, name: "&&" },
  { id: 73, name: "|" },
  { id: 74, name: "^" },
  { id: 75, name: "&" },
  { id: 76, name: "===" },
  { id: 77, name: "!==" },
  { id: 78, name: "<" },
  { id: 79, name: ">" },
  { id: 80, name: "<=" },
  { id: 81, name: ">=" },
  { id: 82, name: "<<" },
  { id: 83, name: ">>" },
  { id: 84, name: ">>>" },
  { id: 85, name: "+" },
  { id: 86, name: "-" },
  { id: 87, name: "*" },
  { id: 88, name: "/" },
  { id: 89, name: "%" },
  { id: 90, name: "**" },
  { id: 91, name: "!" },
  { id: 92, name: "~" },
  { id: 93, name: "++" },
  { id: 94, name: "--" },
  {
    id: 95,
    name: "expressionStatementStart",
  },
  {
    id: 96,
    name: "forBindingStart",
  },
] as const;

export const DECLARATIVE_V2_CANONICAL_NONTERMINALS_V1 = [
  { id: 1, name: "$accept" },
  { id: 2, name: "Module" },
  { id: 3, name: "Directives" },
  { id: 4, name: "Directive" },
  { id: 5, name: "Imports" },
  { id: 6, name: "ImportDeclaration" },
  { id: 7, name: "ImportClause" },
  { id: 8, name: "ImportSpecifiersOpt" },
  { id: 9, name: "ImportSpecifiers" },
  { id: 10, name: "ImportSpecifier" },
  { id: 11, name: "Functions" },
  { id: 12, name: "FunctionDeclaration" },
  { id: 13, name: "AsyncOpt" },
  { id: 14, name: "ParametersOpt" },
  { id: 15, name: "Parameters" },
  { id: 16, name: "BindingPattern" },
  { id: 17, name: "ArrayBinding" },
  { id: 18, name: "BindingElementsOpt" },
  { id: 19, name: "BindingElements" },
  { id: 20, name: "BindingElement" },
  { id: 21, name: "ObjectBinding" },
  { id: 22, name: "BindingPropertiesOpt" },
  { id: 23, name: "BindingProperties" },
  { id: 24, name: "BindingProperty" },
  { id: 25, name: "Block" },
  { id: 26, name: "StatementList" },
  { id: 27, name: "Statement" },
  { id: 28, name: "VariableStatement" },
  { id: 29, name: "LetBindings" },
  { id: 30, name: "LetBinding" },
  { id: 31, name: "ConstBindings" },
  { id: 32, name: "ConstBinding" },
  { id: 33, name: "IfStatement" },
  { id: 34, name: "SwitchStatement" },
  { id: 35, name: "SwitchClauses" },
  { id: 36, name: "SwitchClause" },
  { id: 37, name: "WhileStatement" },
  { id: 38, name: "DoStatement" },
  { id: 39, name: "ForStatement" },
  { id: 40, name: "ForInitOpt" },
  { id: 41, name: "ForDeclaration" },
  { id: 42, name: "ForOfStatement" },
  { id: 43, name: "ForBinding" },
  { id: 44, name: "ReturnStatement" },
  { id: 45, name: "ThrowStatement" },
  { id: 46, name: "TryStatement" },
  { id: 47, name: "CatchClause" },
  { id: 48, name: "FinallyClause" },
  { id: 49, name: "BreakStatement" },
  { id: 50, name: "ContinueStatement" },
  { id: 51, name: "ExpressionOpt" },
  { id: 52, name: "Expression" },
  { id: 53, name: "AssignmentExpression" },
  { id: 54, name: "ConditionalExpression" },
  { id: 55, name: "NullishExpression" },
  { id: 56, name: "LogicalOrExpression" },
  { id: 57, name: "LogicalAndExpression" },
  { id: 58, name: "BitwiseOrExpression" },
  { id: 59, name: "BitwiseXorExpression" },
  { id: 60, name: "BitwiseAndExpression" },
  { id: 61, name: "EqualityExpression" },
  { id: 62, name: "RelationalExpression" },
  { id: 63, name: "ShiftExpression" },
  { id: 64, name: "AdditiveExpression" },
  { id: 65, name: "MultiplicativeExpression" },
  { id: 66, name: "ExponentiationExpression" },
  { id: 67, name: "UnaryExpression" },
  { id: 68, name: "UpdateExpression" },
  { id: 69, name: "PostfixExpression" },
  { id: 70, name: "PrimaryExpression" },
  { id: 71, name: "ArgumentsOpt" },
  { id: 72, name: "Arguments" },
  { id: 73, name: "Argument" },
  { id: 74, name: "ArrayLiteral" },
  { id: 75, name: "ArrayElementsOpt" },
  { id: 76, name: "ArrayElements" },
  { id: 77, name: "ArrayElement" },
  { id: 78, name: "ObjectLiteral" },
  { id: 79, name: "ObjectPropertiesOpt" },
  { id: 80, name: "ObjectProperties" },
  { id: 81, name: "ObjectProperty" },
  { id: 82, name: "TemplateLiteral" },
  { id: 83, name: "TemplateSpans" },
  { id: 84, name: "CoalesceExpression" },
] as const;

export const DECLARATIVE_V2_CANONICAL_SEMANTIC_OPCODES_V1 = [
  { id: 1, name: "acceptModule" },
  { id: 2, name: "appendModuleMember" },
  { id: 3, name: "recordDirective" },
  { id: 4, name: "recordImport" },
  { id: 5, name: "recordFunction" },
  { id: 6, name: "recordBinding" },
  { id: 7, name: "recordStatement" },
  { id: 8, name: "recordExpression" },
  { id: 9, name: "recordCall" },
  { id: 10, name: "recordMember" },
  { id: 11, name: "recordTemplate" },
  { id: 12, name: "empty" },
] as const;

type DeclarativeV2CanonicalProductionSourceV1 = readonly [
  lhs: string,
  rhs: readonly string[],
  semanticOpcode: number,
  precedenceTerminal?: string,
];

const DECLARATIVE_V2_CANONICAL_PRODUCTION_SOURCE_V1 = [
  ["$accept", ["Module"], 1],
  ["Module", ["Directives", "Imports", "Functions"], 1],
  ["Directives", ["Directives", "Directive"], 2],
  ["Directives", [], 12],
  ["Directive", ["string", ";"], 3],
  ["Imports", ["Imports", "ImportDeclaration"], 2],
  ["Imports", [], 12],
  ["ImportDeclaration", ["import", "ImportClause", "from", "string", ";"], 4],
  ["ImportClause", ["identifier"], 4],
  ["ImportClause", ["{", "ImportSpecifiersOpt", "}"], 4],
  ["ImportSpecifiersOpt", ["ImportSpecifiers"], 2],
  ["ImportSpecifiersOpt", ["ImportSpecifiers", ","], 2],
  ["ImportSpecifiersOpt", [], 12],
  ["ImportSpecifiers", ["ImportSpecifier"], 2],
  ["ImportSpecifiers", ["ImportSpecifiers", ",", "ImportSpecifier"], 2],
  ["ImportSpecifier", ["identifier"], 4],
  ["Functions", ["Functions", "FunctionDeclaration"], 2],
  ["Functions", [], 12],
  ["FunctionDeclaration", ["AsyncOpt", "function", "identifier", "(", "ParametersOpt", ")", "Block"], 5],
  ["FunctionDeclaration", ["export", "AsyncOpt", "function", "identifier", "(", "ParametersOpt", ")", "Block"], 5],
  ["FunctionDeclaration", ["export", "default", "AsyncOpt", "function", "identifier", "(", "ParametersOpt", ")", "Block"], 5],
  ["AsyncOpt", ["async"], 2],
  ["AsyncOpt", [], 12],
  ["ParametersOpt", ["Parameters"], 2],
  ["ParametersOpt", ["Parameters", ","], 2],
  ["ParametersOpt", [], 12],
  ["Parameters", ["BindingPattern"], 6],
  ["Parameters", ["Parameters", ",", "BindingPattern"], 6],
  ["BindingPattern", ["identifier"], 6],
  ["BindingPattern", ["ArrayBinding"], 6],
  ["BindingPattern", ["ObjectBinding"], 6],
  ["ArrayBinding", ["[", "BindingElementsOpt", "]"], 6],
  ["BindingElementsOpt", ["BindingElements"], 6],
  ["BindingElementsOpt", ["BindingElements", ","], 6],
  ["BindingElementsOpt", [], 12],
  ["BindingElements", ["BindingElement"], 6],
  ["BindingElements", ["BindingElements", ",", "BindingElement"], 6],
  ["BindingElement", ["BindingPattern"], 6],
  ["BindingElement", ["...", "identifier"], 6],
  ["ObjectBinding", ["{", "BindingPropertiesOpt", "}"], 6],
  ["BindingPropertiesOpt", ["BindingProperties"], 6],
  ["BindingPropertiesOpt", ["BindingProperties", ","], 6],
  ["BindingPropertiesOpt", [], 12],
  ["BindingProperties", ["BindingProperty"], 6],
  ["BindingProperties", ["BindingProperties", ",", "BindingProperty"], 6],
  ["BindingProperty", ["identifier"], 6],
  ["BindingProperty", ["identifier", ":", "BindingPattern"], 6],
  ["BindingProperty", ["...", "identifier"], 6],
  ["Block", ["{", "StatementList", "}"], 7],
  ["StatementList", ["StatementList", "Statement"], 2],
  ["StatementList", [], 12],
  ["Statement", ["Block"], 7],
  ["Statement", [";"], 7],
  ["Statement", ["expressionStatementStart", "Expression", ";"], 7],
  ["Statement", ["VariableStatement"], 7],
  ["Statement", ["IfStatement"], 7],
  ["Statement", ["SwitchStatement"], 7],
  ["Statement", ["WhileStatement"], 7],
  ["Statement", ["DoStatement"], 7],
  ["Statement", ["ForStatement"], 7],
  ["Statement", ["ForOfStatement"], 7],
  ["Statement", ["ReturnStatement"], 7],
  ["Statement", ["ThrowStatement"], 7],
  ["Statement", ["TryStatement"], 7],
  ["Statement", ["BreakStatement"], 7],
  ["Statement", ["ContinueStatement"], 7],
  ["VariableStatement", ["let", "LetBindings", ";"], 6],
  ["VariableStatement", ["const", "ConstBindings", ";"], 6],
  ["LetBindings", ["LetBinding"], 6],
  ["LetBindings", ["LetBindings", ",", "LetBinding"], 6],
  ["LetBinding", ["BindingPattern"], 6],
  ["LetBinding", ["BindingPattern", "=", "AssignmentExpression"], 6],
  ["ConstBindings", ["ConstBinding"], 6],
  ["ConstBindings", ["ConstBindings", ",", "ConstBinding"], 6],
  ["ConstBinding", ["BindingPattern", "=", "AssignmentExpression"], 6],
  ["IfStatement", ["if", "(", "Expression", ")", "Statement"], 7, "if"],
  ["IfStatement", ["if", "(", "Expression", ")", "Statement", "else", "Statement"], 7],
  ["SwitchStatement", ["switch", "(", "Expression", ")", "{", "SwitchClauses", "}"], 7],
  ["SwitchClauses", ["SwitchClauses", "SwitchClause"], 2],
  ["SwitchClauses", [], 12],
  ["SwitchClause", ["case", "Expression", ":", "StatementList"], 7],
  ["SwitchClause", ["default", ":", "StatementList"], 7],
  ["WhileStatement", ["while", "(", "Expression", ")", "Statement"], 7],
  ["DoStatement", ["do", "Statement", "while", "(", "Expression", ")", ";"], 7],
  ["ForStatement", ["for", "(", "ForInitOpt", ";", "ExpressionOpt", ";", "ExpressionOpt", ")", "Statement"], 7],
  ["ForInitOpt", ["Expression"], 8],
  ["ForInitOpt", ["ForDeclaration"], 6],
  ["ForInitOpt", [], 12],
  ["ForDeclaration", ["let", "LetBindings"], 6],
  ["ForDeclaration", ["const", "ConstBindings"], 6],
  ["ForOfStatement", ["for", "(", "ForBinding", "of", "Expression", ")", "Statement"], 7],
  ["ForBinding", ["let", "BindingPattern"], 6],
  ["ForBinding", ["const", "BindingPattern"], 6],
  ["ForBinding", ["forBindingStart", "BindingPattern"], 6],
  ["ReturnStatement", ["return", "ExpressionOpt", ";"], 7],
  ["ThrowStatement", ["throw", "Expression", ";"], 7],
  ["TryStatement", ["try", "Block", "CatchClause"], 7],
  ["TryStatement", ["try", "Block", "FinallyClause"], 7],
  ["TryStatement", ["try", "Block", "CatchClause", "FinallyClause"], 7],
  ["CatchClause", ["catch", "Block"], 7],
  ["CatchClause", ["catch", "(", "BindingPattern", ")", "Block"], 7],
  ["FinallyClause", ["finally", "Block"], 7],
  ["BreakStatement", ["break", ";"], 7],
  ["ContinueStatement", ["continue", ";"], 7],
  ["ExpressionOpt", ["Expression"], 8],
  ["ExpressionOpt", [], 12],
  ["Expression", ["AssignmentExpression"], 8],
  ["Expression", ["Expression", ",", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["ConditionalExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "+=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "-=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "*=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "/=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "%=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "**=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "<<=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", ">>=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", ">>>=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "&=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "|=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "^=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "&&=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "||=", "AssignmentExpression"], 8],
  ["AssignmentExpression", ["PostfixExpression", "??=", "AssignmentExpression"], 8],
  ["ConditionalExpression", ["NullishExpression"], 8],
  ["ConditionalExpression", ["NullishExpression", "?", "AssignmentExpression", ":", "AssignmentExpression"], 8],
  ["NullishExpression", ["LogicalOrExpression"], 8],
  ["NullishExpression", ["CoalesceExpression"], 8],
  ["CoalesceExpression", ["BitwiseOrExpression", "??", "BitwiseOrExpression"], 8],
  ["CoalesceExpression", ["CoalesceExpression", "??", "BitwiseOrExpression"], 8],
  ["LogicalOrExpression", ["LogicalAndExpression"], 8],
  ["LogicalOrExpression", ["LogicalOrExpression", "||", "LogicalAndExpression"], 8],
  ["LogicalAndExpression", ["BitwiseOrExpression"], 8],
  ["LogicalAndExpression", ["LogicalAndExpression", "&&", "BitwiseOrExpression"], 8],
  ["BitwiseOrExpression", ["BitwiseXorExpression"], 8],
  ["BitwiseOrExpression", ["BitwiseOrExpression", "|", "BitwiseXorExpression"], 8],
  ["BitwiseXorExpression", ["BitwiseAndExpression"], 8],
  ["BitwiseXorExpression", ["BitwiseXorExpression", "^", "BitwiseAndExpression"], 8],
  ["BitwiseAndExpression", ["EqualityExpression"], 8],
  ["BitwiseAndExpression", ["BitwiseAndExpression", "&", "EqualityExpression"], 8],
  ["EqualityExpression", ["RelationalExpression"], 8],
  ["EqualityExpression", ["EqualityExpression", "===", "RelationalExpression"], 8],
  ["EqualityExpression", ["EqualityExpression", "!==", "RelationalExpression"], 8],
  ["RelationalExpression", ["ShiftExpression"], 8],
  ["RelationalExpression", ["RelationalExpression", "<", "ShiftExpression"], 8],
  ["RelationalExpression", ["RelationalExpression", ">", "ShiftExpression"], 8],
  ["RelationalExpression", ["RelationalExpression", "<=", "ShiftExpression"], 8],
  ["RelationalExpression", ["RelationalExpression", ">=", "ShiftExpression"], 8],
  ["ShiftExpression", ["AdditiveExpression"], 8],
  ["ShiftExpression", ["ShiftExpression", "<<", "AdditiveExpression"], 8],
  ["ShiftExpression", ["ShiftExpression", ">>", "AdditiveExpression"], 8],
  ["ShiftExpression", ["ShiftExpression", ">>>", "AdditiveExpression"], 8],
  ["AdditiveExpression", ["MultiplicativeExpression"], 8],
  ["AdditiveExpression", ["AdditiveExpression", "+", "MultiplicativeExpression"], 8],
  ["AdditiveExpression", ["AdditiveExpression", "-", "MultiplicativeExpression"], 8],
  ["MultiplicativeExpression", ["ExponentiationExpression"], 8],
  ["MultiplicativeExpression", ["MultiplicativeExpression", "*", "ExponentiationExpression"], 8],
  ["MultiplicativeExpression", ["MultiplicativeExpression", "/", "ExponentiationExpression"], 8],
  ["MultiplicativeExpression", ["MultiplicativeExpression", "%", "ExponentiationExpression"], 8],
  ["ExponentiationExpression", ["UnaryExpression"], 8],
  ["ExponentiationExpression", ["UpdateExpression", "**", "ExponentiationExpression"], 8],
  ["UnaryExpression", ["UpdateExpression"], 8],
  ["UnaryExpression", ["await", "UnaryExpression"], 8],
  ["UnaryExpression", ["typeof", "UnaryExpression"], 8],
  ["UnaryExpression", ["void", "UnaryExpression"], 8],
  ["UnaryExpression", ["delete", "UnaryExpression"], 8],
  ["UnaryExpression", ["!", "UnaryExpression"], 8],
  ["UnaryExpression", ["~", "UnaryExpression"], 8],
  ["UnaryExpression", ["+", "UnaryExpression"], 8],
  ["UnaryExpression", ["-", "UnaryExpression"], 8],
  ["UnaryExpression", ["++", "PostfixExpression"], 8],
  ["UnaryExpression", ["--", "PostfixExpression"], 8],
  ["UpdateExpression", ["PostfixExpression"], 8],
  ["PostfixExpression", ["PrimaryExpression"], 8],
  ["PostfixExpression", ["PostfixExpression", ".", "identifier"], 10],
  ["PostfixExpression", ["PostfixExpression", ".", "delete"], 10],
  ["PostfixExpression", ["PostfixExpression", "?.", "identifier"], 10],
  ["PostfixExpression", ["PostfixExpression", "[", "Expression", "]"], 10],
  ["PostfixExpression", ["PostfixExpression", "?.", "[", "Expression", "]"], 10],
  ["PostfixExpression", ["PostfixExpression", "(", "ArgumentsOpt", ")"], 9],
  ["PostfixExpression", ["PostfixExpression", "?.", "(", "ArgumentsOpt", ")"], 9],
  ["PostfixExpression", ["PostfixExpression", "++"], 8],
  ["PostfixExpression", ["PostfixExpression", "--"], 8],
  ["PrimaryExpression", ["identifier"], 8],
  ["PrimaryExpression", ["number"], 8],
  ["PrimaryExpression", ["bigint"], 8],
  ["PrimaryExpression", ["string"], 8],
  ["PrimaryExpression", ["true"], 8],
  ["PrimaryExpression", ["false"], 8],
  ["PrimaryExpression", ["null"], 8],
  ["PrimaryExpression", ["undefined"], 8],
  ["PrimaryExpression", ["ArrayLiteral"], 8],
  ["PrimaryExpression", ["ObjectLiteral"], 8],
  ["PrimaryExpression", ["TemplateLiteral"], 11],
  ["PrimaryExpression", ["(", "Expression", ")"], 8],
  ["ArgumentsOpt", ["Arguments"], 8],
  ["ArgumentsOpt", ["Arguments", ","], 8],
  ["ArgumentsOpt", [], 12],
  ["Arguments", ["Argument"], 8],
  ["Arguments", ["Arguments", ",", "Argument"], 8],
  ["Argument", ["AssignmentExpression"], 8],
  ["Argument", ["...", "AssignmentExpression"], 8],
  ["ArrayLiteral", ["[", "ArrayElementsOpt", "]"], 8],
  ["ArrayElementsOpt", ["ArrayElements"], 8],
  ["ArrayElementsOpt", ["ArrayElements", ","], 8],
  ["ArrayElementsOpt", [], 12],
  ["ArrayElements", ["ArrayElement"], 8],
  ["ArrayElements", ["ArrayElements", ",", "ArrayElement"], 8],
  ["ArrayElement", ["AssignmentExpression"], 8],
  ["ArrayElement", ["...", "AssignmentExpression"], 8],
  ["ObjectLiteral", ["{", "ObjectPropertiesOpt", "}"], 8],
  ["ObjectPropertiesOpt", ["ObjectProperties"], 8],
  ["ObjectPropertiesOpt", ["ObjectProperties", ","], 8],
  ["ObjectPropertiesOpt", [], 12],
  ["ObjectProperties", ["ObjectProperty"], 8],
  ["ObjectProperties", ["ObjectProperties", ",", "ObjectProperty"], 8],
  ["ObjectProperty", ["identifier"], 8],
  ["ObjectProperty", ["identifier", ":", "AssignmentExpression"], 8],
  ["ObjectProperty", ["string", ":", "AssignmentExpression"], 8],
  ["ObjectProperty", ["number", ":", "AssignmentExpression"], 8],
  ["ObjectProperty", ["...", "AssignmentExpression"], 8],
  ["TemplateLiteral", ["templateNoSubstitution"], 11],
  ["TemplateLiteral", ["templateHead", "Expression", "TemplateSpans"], 11],
  ["TemplateSpans", ["templateTail"], 11],
  ["TemplateSpans", ["templateMiddle", "Expression", "TemplateSpans"], 11],
] as const satisfies ReadonlyArray<DeclarativeV2CanonicalProductionSourceV1>;

export const DECLARATIVE_V2_CANONICAL_PRODUCTIONS_V1 =
  freezeOwnedContractGraph(
    DECLARATIVE_V2_CANONICAL_PRODUCTION_SOURCE_V1.map(
      ([lhs, rhs, semanticOpcode, precedenceTerminal], index) => ({
        id: index + 1,
        lhs,
        rhs: [...rhs],
        semanticOpcode,
        ...(precedenceTerminal === undefined ? {} : { precedenceTerminal }),
      }),
    ),
  );

export const DECLARATIVE_V2_CANONICAL_PRECEDENCE_V1 = [
  { id: 1, terminal: "if", precedence: 1, associativity: 2 },
  { id: 2, terminal: "else", precedence: 2, associativity: 2 },
] as const;

export const DECLARATIVE_V2_CANONICAL_LR_STORAGE_POLICY_V1 =
  freezeOwnedContractGraph({
    construction: "canonical-lr1-first-closure-goto",
    stateNumbering: "numeric-symbol-bfs",
    storedItems: "lr1-kernel-items",
    closure: "deterministically-recomputed-from-kernel-and-grammar",
    conflictPolicy:
      "precedence-resolved-shift-reduce; reject-unresolved-and-reduce-reduce",
    recovery: "terminal-diagnostic-only; no-insertion-or-resumption",
    recoveryStorage:
      "one-default-row; absent-action-means-terminal-syntax-diagnostic",
  } as const);

export const DECLARATIVE_V2_CANONICAL_UTF8_BYTE_CLASSES_V1 = [
  { id: 1, name: "ascii", first: 0x00, last: 0x7f },
  { id: 2, name: "continuation80_8f", first: 0x80, last: 0x8f },
  { id: 3, name: "continuation90_9f", first: 0x90, last: 0x9f },
  { id: 4, name: "continuationA0_bf", first: 0xa0, last: 0xbf },
  { id: 5, name: "lead2", first: 0xc2, last: 0xdf },
  { id: 6, name: "lead3E0", first: 0xe0, last: 0xe0 },
  { id: 7, name: "lead3General", first: 0xe1, last: 0xec },
  { id: 8, name: "lead3Ed", first: 0xed, last: 0xed },
  { id: 9, name: "lead3Upper", first: 0xee, last: 0xef },
  { id: 10, name: "lead4F0", first: 0xf0, last: 0xf0 },
  { id: 11, name: "lead4General", first: 0xf1, last: 0xf3 },
  { id: 12, name: "lead4F4", first: 0xf4, last: 0xf4 },
  { id: 13, name: "invalid", first: 0x00, last: 0xff },
] as const;

export const DECLARATIVE_V2_CANONICAL_UTF8_STATES_V1 = [
  { id: 1, name: "accepting", accepting: 1 },
  { id: 2, name: "need1", accepting: 0 },
  { id: 3, name: "need2", accepting: 0 },
  { id: 4, name: "need2AfterE0", accepting: 0 },
  { id: 5, name: "need2AfterEd", accepting: 0 },
  { id: 6, name: "need3", accepting: 0 },
  { id: 7, name: "need3AfterF0", accepting: 0 },
  { id: 8, name: "need3AfterF4", accepting: 0 },
  { id: 9, name: "error", accepting: 0 },
] as const;

const utf8Transition = (
  id: number,
  state: number,
  byteClass: number,
  nextState: number,
) => Object.freeze({ id, state, byteClass, nextState });

const DECLARATIVE_V2_CANONICAL_UTF8_LEGAL_TRANSITIONS_V1 = [
    utf8Transition(1, 1, 1, 1),
    utf8Transition(2, 1, 5, 2),
    utf8Transition(3, 1, 6, 4),
    utf8Transition(4, 1, 7, 3),
    utf8Transition(5, 1, 8, 5),
    utf8Transition(6, 1, 9, 3),
    utf8Transition(7, 1, 10, 7),
    utf8Transition(8, 1, 11, 6),
    utf8Transition(9, 1, 12, 8),
    utf8Transition(10, 2, 2, 1),
    utf8Transition(11, 2, 3, 1),
    utf8Transition(12, 2, 4, 1),
    utf8Transition(13, 3, 2, 2),
    utf8Transition(14, 3, 3, 2),
    utf8Transition(15, 3, 4, 2),
    utf8Transition(16, 4, 4, 2),
    utf8Transition(17, 5, 2, 2),
    utf8Transition(18, 5, 3, 2),
    utf8Transition(19, 6, 2, 3),
    utf8Transition(20, 6, 3, 3),
    utf8Transition(21, 6, 4, 3),
    utf8Transition(22, 7, 3, 3),
    utf8Transition(23, 7, 4, 3),
    utf8Transition(24, 8, 2, 3),
  ] as const;

export const DECLARATIVE_V2_CANONICAL_UTF8_TRANSITIONS_V1 =
  freezeOwnedContractGraph(
    DECLARATIVE_V2_CANONICAL_UTF8_STATES_V1.flatMap(({ id: state }) =>
      DECLARATIVE_V2_CANONICAL_UTF8_BYTE_CLASSES_V1.map(
        ({ id: byteClass }, classIndex) => {
          const legal =
            DECLARATIVE_V2_CANONICAL_UTF8_LEGAL_TRANSITIONS_V1.find(
              (row) => row.state === state && row.byteClass === byteClass,
            );
          return {
            id:
              (state - 1) *
                DECLARATIVE_V2_CANONICAL_UTF8_BYTE_CLASSES_V1.length +
              classIndex +
              1,
            state,
            byteClass,
            nextState: legal?.nextState ?? 9,
          };
        },
      )
    ),
  );

export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_SECTIONS_V1 = [
  { id: 1, name: "byteClasses", recordBytes: 2 },
  { id: 2, name: "keywords", recordBytes: 12 },
  { id: 3, name: "punctuators", recordBytes: 12 },
  { id: 4, name: "regexGoals", recordBytes: 12 },
  { id: 5, name: "utf8Transitions", recordBytes: 20 },
  { id: 6, name: "numberTransitions", recordBytes: 20 },
  { id: 7, name: "asiTransitions", recordBytes: 12 },
  { id: 8, name: "templateTransitions", recordBytes: 20 },
  { id: 9, name: "terminals", recordBytes: 12 },
  { id: 10, name: "nonterminals", recordBytes: 12 },
  { id: 11, name: "productions", recordBytes: 32 },
  { id: 12, name: "precedence", recordBytes: 16 },
  { id: 13, name: "parserActions", recordBytes: 20 },
  { id: 14, name: "parserGotos", recordBytes: 16 },
  { id: 15, name: "recovery", recordBytes: 20 },
  { id: 16, name: "semanticActions", recordBytes: 8 },
  { id: 17, name: "abiLookup", recordBytes: 12 },
  { id: 18, name: "diagnosticLookup", recordBytes: 12 },
  { id: 19, name: "canonicalContract", recordBytes: 1 },
  { id: 20, name: "canonicalTerminals", recordBytes: 12 },
  { id: 21, name: "canonicalNonterminals", recordBytes: 12 },
  { id: 22, name: "canonicalProductionHeaders", recordBytes: 24 },
  { id: 23, name: "canonicalProductionRhs", recordBytes: 8 },
  { id: 24, name: "canonicalLrItems", recordBytes: 16 },
  { id: 25, name: "canonicalLrStates", recordBytes: 16 },
  { id: 26, name: "canonicalLrActions", recordBytes: 20 },
  { id: 27, name: "canonicalLrGotos", recordBytes: 16 },
  { id: 28, name: "canonicalLrRecovery", recordBytes: 20 },
  { id: 29, name: "canonicalPrecedence", recordBytes: 20 },
  { id: 30, name: "canonicalSemanticOpcodes", recordBytes: 12 },
  { id: 31, name: "canonicalUtf8ByteClasses", recordBytes: 16 },
  { id: 32, name: "canonicalUtf8States", recordBytes: 12 },
  { id: 33, name: "canonicalUtf8Transitions", recordBytes: 16 },
] as const;

export const DECLARATIVE_V2_VERIFIER_EXECUTABLE_CONTRACT_V1 =
  freezeOwnedContractGraph({
    identity: DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_IDENTITY_V1,
    binds: {
      executableCoreIdentity: DECLARATIVE_V2_EXECUTABLE_CORE_IDENTITY_V1,
      diagnosticIdentity: DECLARATIVE_V2_VERIFIER_DIAGNOSTIC_IDENTITY_V1,
      unicodeIdentity: DECLARATIVE_V2_VERIFIER_UNICODE_IDENTITY_V1,
      acceptedSpecificationManifestIdentity:
        GENERATED_DECLARATIVE_V2_VERIFIER_MANIFEST_V1.manifestIdentity,
      acceptedSpecificationAssetSha256:
        GENERATED_DECLARATIVE_V2_VERIFIER_MANIFEST_V1.assetSha256,
    },
    format: {
      magic: DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_MAGIC_V1,
      version: DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_VERSION_V1,
      headerBytes: DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_HEADER_BYTES_V1,
      sectionBytes: DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_SECTION_BYTES_V1,
      alignment: DECLARATIVE_V2_VERIFIER_EXECUTABLE_TABLE_ALIGNMENT_V1,
      sections: DECLARATIVE_V2_VERIFIER_EXECUTABLE_SECTIONS_V1,
    },
    transitionQuantum: DECLARATIVE_V2_VERIFIER_TRANSITION_QUANTUM_V1,
    tokenKinds: DECLARATIVE_V2_TOKEN_KINDS_V1,
    byteClasses: DECLARATIVE_V2_LEXICAL_BYTE_CLASSES_V1,
    keywords: DECLARATIVE_V2_KEYWORDS_V1,
    punctuators: DECLARATIVE_V2_PUNCTUATORS_V1,
    regexGoals: DECLARATIVE_V2_REGEX_GOAL_AFTER_V1,
    utf8Transitions: DECLARATIVE_V2_UTF8_TRANSITIONS_V1,
    numberTransitions: DECLARATIVE_V2_NUMBER_TRANSITIONS_V1,
    asiRules: DECLARATIVE_V2_ASI_RULES_V1,
    templateTransitions: DECLARATIVE_V2_TEMPLATE_TRANSITIONS_V1,
    parserStates: DECLARATIVE_V2_MODULE_PARSER_STATES_V1,
    parserTerminals: DECLARATIVE_V2_PARSER_TERMINALS_V1,
    parserNonterminals: DECLARATIVE_V2_PARSER_NONTERMINALS_V1,
    parserProductions: DECLARATIVE_V2_PARSER_PRODUCTIONS_V1,
    operatorPrecedence: DECLARATIVE_V2_OPERATOR_PRECEDENCE_V1,
    parserActions: DECLARATIVE_V2_MODULE_PARSER_ACTIONS_V1,
    parserGotos: DECLARATIVE_V2_MODULE_PARSER_GOTOS_V1,
    parserRecovery: DECLARATIVE_V2_PARSER_RECOVERY_V1,
    semanticActions: DECLARATIVE_V2_SEMANTIC_ACTIONS_V1,
    abiLookup: DECLARATIVE_V2_SAFE_ABI_LOOKUP_V1,
    contextMemberAbiLowerings:
      DECLARATIVE_V2_CONTEXT_MEMBER_ABI_LOWERINGS_V1,
    platformImportAllowlist: DECLARATIVE_V2_PLATFORM_IMPORT_ALLOWLIST_V1,
    canonicalGrammar: {
      terminals: DECLARATIVE_V2_CANONICAL_TERMINALS_V1,
      nonterminals: DECLARATIVE_V2_CANONICAL_NONTERMINALS_V1,
      productions: DECLARATIVE_V2_CANONICAL_PRODUCTIONS_V1,
      precedence: DECLARATIVE_V2_CANONICAL_PRECEDENCE_V1,
      semanticOpcodes: DECLARATIVE_V2_CANONICAL_SEMANTIC_OPCODES_V1,
      lrStoragePolicy: DECLARATIVE_V2_CANONICAL_LR_STORAGE_POLICY_V1,
    },
    canonicalUtf8: {
      byteClasses: DECLARATIVE_V2_CANONICAL_UTF8_BYTE_CLASSES_V1,
      states: DECLARATIVE_V2_CANONICAL_UTF8_STATES_V1,
      transitions: DECLARATIVE_V2_CANONICAL_UTF8_TRANSITIONS_V1,
    },
  } as const);
