/* Generated by scripts/declarativeV2VerifierBoundsV1.ts. Do not edit. */
const GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_VALUE_V1 = {
  "generatorVersion": 2,
  "maximumProductionRhsLength": 3,
  "epsilonProductionCount": 2,
  "parseDiagnosticPhasesPerDomainUnit": 4,
  "parseDiagnosticDefinitionsPerDomainUnit": 19,
  "parserStackEntriesPerDomainUnit": 6,
  "evidenceFramesPerDomainUnit": 21,
  "maximumEvidenceTextFields": 3,
  "maximumJsonEscapeBytesPerInputByte": 6,
  "maximumEvidenceFixedBytes": 1024,
  "semanticOutputRecordsPerDomainUnit": 6,
  "maximumSemanticOutputBytesPerDomainByte": 8,
  "maximumSemanticTransitionsPerDomainUnitSquared": 256,
  "arenaOperationalByteLimit": 67108864,
  "selectedSourceAndModulePathByteLimit": 156,
  "firstExcludedSourceAndModulePathByteLimit": 157,
  "arenaBytesAtSelectedLimit": 66819028,
  "arenaBytesAtFirstExcludedLimit": 67534609,
  "boundsIdentity": "0c8fa2dc3b7b720dd48da148be06e47feb49747a075b09ca6e543075703cd8a0"
} as const;
export const GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_V1 = Object.freeze(GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_VALUE_V1);
