/* Generated by scripts/declarativeV2VerifierBoundsV1.ts. Do not edit. */
const GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_VALUE_V1 = {
  "generatorVersion": 1,
  "maximumProductionRhsLength": 3,
  "epsilonProductionCount": 2,
  "parseDiagnosticPhasesPerDomainUnit": 4,
  "parseDiagnosticDefinitionsPerDomainUnit": 19,
  "parserStackEntriesPerDomainUnit": 6,
  "evidenceFramesPerDomainUnit": 21,
  "maximumEvidenceTextFields": 3,
  "maximumJsonEscapeBytesPerInputByte": 6,
  "maximumEvidenceFixedBytes": 1024,
  "semanticOutputRecordsPerDomainUnit": 6,
  "maximumSemanticOutputBytesPerDomainByte": 8,
  "maximumSemanticTransitionsPerDomainUnitSquared": 256,
  "arenaOperationalByteLimit": 67108864,
  "selectedSourceAndModulePathByteLimit": 128,
  "arenaBytesAtSelectedLimit": 48273592,
  "arenaBytesAtNextPowerOfTwo": 156553528,
  "boundsIdentity": "db2dd17538d9c26f8d03b01f244cb8d2bfe845bb8a41e3093261778b25c9b56b"
} as const;
export const GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_V1 = Object.freeze(GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_VALUE_V1);
