/* Generated by scripts/declarativeV2VerifierBoundsV1.ts. Do not edit. */
const GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_VALUE_V1 = {
  "generatorVersion": 3,
  "arenaIdentity": "flarex.declarative-v2/verifier-arena/v2",
  "factoredArenaPolicy": {
    "diagnosticRecordBytes": 32,
    "evidenceIndexRecordBytes": 4,
    "maximumEvidenceFixedBytes": 1024,
    "maximumEvidenceTextFields": 3,
    "maximumJsonEscapeBytesPerInputByte": 6
  },
  "maximumProductionRhsLength": 3,
  "epsilonProductionCount": 2,
  "parseDiagnosticPhasesPerDomainUnit": 4,
  "parseDiagnosticDefinitionsPerDomainUnit": 19,
  "parserStackEntriesPerDomainUnit": 6,
  "evidenceFramesPerDomainUnit": 21,
  "maximumEvidenceTextFields": 3,
  "maximumJsonEscapeBytesPerInputByte": 6,
  "maximumEvidenceFixedBytes": 1024,
  "semanticOutputRecordsPerDomainUnit": 6,
  "maximumSemanticOutputBytesPerDomainByte": 8,
  "maximumSemanticTransitionsPerDomainUnitSquared": 256,
  "arenaOperationalByteLimit": 67108864,
  "selectedSourceAndModulePathByteLimit": 26869,
  "firstExcludedSourceAndModulePathByteLimit": 26870,
  "arenaBytesAtSelectedLimit": 67108001,
  "arenaBytesAtFirstExcludedLimit": 67110498,
  "boundsIdentity": "a777dcb4ba18a5ff7d6f9b382111f03b7b25e76e8e41906b67b7c90ac1dad841"
} as const;
export const GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_V1 = Object.freeze(GENERATED_DECLARATIVE_V2_VERIFIER_PARSE_BOUNDS_VALUE_V1);
