// Generated by scripts/buildIdentity.ts. Do not edit by hand.
export const GENERATED_PRIVATE_ANALYZER_RELEASE_MANIFEST_V1 = Object.freeze({
  implementationIdentityMarker:
    "__FLAREX_PRIVATE_ANALYZER_IMPLEMENTATION_V1__206835e4a5e3fd24d6b3c14e50225927cc452f1ea0b5e9978db265cca3cd47f0__END__",
  implementationIdentityOffset: 45,
  implementationIdentityLength: 64,
  configurationIdentity:
    "c0ffa918d2cbfe69cc6193807caecdccf6d50c391bc2525db300b5a4cc4ce795",
  toolchain: Object.freeze({
    wrangler: "4.100.0",
    typescript: "7.0.2",
    effect: "4.0.0-beta.90",
    workersTypes: "4.20260613.1",
    esbuild: "0.27.3",
  }),
});
