// Generated by scripts/buildIdentity.ts. Do not edit by hand.
export const GENERATED_PRIVATE_ANALYZER_RELEASE_MANIFEST_V1 = Object.freeze({
  implementationIdentityMarker:
    "__FLAREX_PRIVATE_ANALYZER_IMPLEMENTATION_V1__20bc02254f2ca71d9552bdc0af06cd2aeb96f116d5ac785425fa2e6b13bc174f__END__",
  implementationIdentityOffset: 45,
  implementationIdentityLength: 64,
  configurationIdentity:
    "20ffcd819f39a5e2e7a338c79b51144f524a7f19e20317e1328c10e378a46c19",
  toolchain: Object.freeze({
    wrangler: "4.100.0",
    typescript: "7.0.2",
    effect: "4.0.0-beta.90",
    workersTypes: "4.20260613.1",
    esbuild: "0.27.3",
  }),
});
