// Generated by scripts/buildIdentity.ts. Do not edit by hand.
export const GENERATED_PRIVATE_ANALYZER_RELEASE_MANIFEST_V1 = Object.freeze({
  implementationIdentityMarker:
    "__FLAREX_PRIVATE_ANALYZER_IMPLEMENTATION_V1__132133d11c8dec3c963e33736cd043c535891c6dc757f607515d0db638748725__END__",
  implementationIdentityOffset: 45,
  implementationIdentityLength: 64,
  configurationIdentity:
    "62b0a1e20b0b3a06c98c4220cb0f2fd6008c677bbc8ec1e24c986e9fa2c1768a",
  toolchain: Object.freeze({
    wrangler: "4.100.0",
    typescript: "7.0.2",
    effect: "4.0.0-beta.90",
    workersTypes: "4.20260613.1",
    esbuild: "0.27.3",
  }),
});
