import {
  SCHEDULER_DEFAULT_DEAD_LETTER_REASON,
  SCHEDULER_DEFAULT_DELIVERY_LIMIT,
  SCHEDULER_DEFAULT_MAX_BATCHES,
  SCHEDULER_DEFAULT_MIN_ATTEMPTS,
  SCHEDULER_DEFAULT_STUCK_AFTER_MS,
} from "flarex-protocol/scheduler";

export const DEFAULT_PENDING_DEPLOYMENT_LIMIT = 25;
export const DEFAULT_EXPIRED_CONNECTION_DEPLOYMENT_SCAN_LIMIT = 100;
export const DEFAULT_DELIVERY_LIMIT = SCHEDULER_DEFAULT_DELIVERY_LIMIT;
export const DEFAULT_MAX_BATCHES = SCHEDULER_DEFAULT_MAX_BATCHES;
export const DEFAULT_STUCK_AFTER_MS = SCHEDULER_DEFAULT_STUCK_AFTER_MS;
export const DEFAULT_MIN_ATTEMPTS = SCHEDULER_DEFAULT_MIN_ATTEMPTS;
export const DEFAULT_DEAD_LETTER_REASON = SCHEDULER_DEFAULT_DEAD_LETTER_REASON;
