export const APPLICATION_RELATION_BUILD_SOURCE_PAGE_SIZE = 4;

export const APPLICATION_RELATION_BUILD_CURSOR_CODEC_VERSION = 1 as const;
export const APPLICATION_RELATION_READINESS_RECEIPT_CODEC_VERSION = 1 as const;
export const APPLICATION_RELATION_READINESS_RECEIPT_MAXIMUM_BYTES = 16_384;
