import {
  generatedExecutionWorkerSource,
  type GeneratedExecutionWorkerSourceOptions,
} from "./GeneratedWorkerSource.ts";
import type { ExecutionArtifactRef, InvokeRequest, PushSourcePackage } from "../types.ts";

export type ExecutionArtifactRuntimeWorkerSourceProfile =
  | "local-miniflare"
  | "hosted-dynamic-worker";

export type ExecutionArtifactRuntimeWorkerSourceOptions = {
  readonly profile: ExecutionArtifactRuntimeWorkerSourceProfile;
  readonly executionModule: string;
};

export type ExecutionArtifactWorkerModulesOptions = {
  readonly sourcePackage: PushSourcePackage;
  readonly runtimeModulePath: string;
  readonly runtimeWorkerSource: string;
  readonly reservedBy: string;
};

export type ExecutionArtifactWorkerExecutorTransport = "legacy" | "postgres";

export type ExecutionArtifactWorkerEnvOptions = {
  readonly executorToken?: string | undefined;
  readonly executorTransport?: ExecutionArtifactWorkerExecutorTransport | undefined;
  readonly invokeMaxAttempts?: string | number | undefined;
  readonly projectId?: string | undefined;
  readonly internalToken?: string | undefined;
};

export type ExecutionArtifactWorkerEnv = {
  readonly FLAREX_EXECUTOR_TOKEN?: string;
  readonly FLAREX_EXECUTOR_TRANSPORT?: ExecutionArtifactWorkerExecutorTransport;
  readonly FLAREX_INVOKE_MAX_ATTEMPTS?: string;
  readonly FLAREX_PROJECT_ID?: string;
  readonly FLAREX_INTERNAL_TOKEN?: string;
};

export type ExecutionArtifactWorkerDefinitionOptions = {
  readonly sourcePackage: PushSourcePackage;
  readonly profile: ExecutionArtifactRuntimeWorkerSourceProfile;
  readonly runtimeModulePath: string;
  readonly reservedBy: string;
  readonly env?: ExecutionArtifactWorkerEnvOptions | undefined;
};

export type ExecutionArtifactWorkerDefinition = {
  readonly mainModule: string;
  readonly modules: Record<string, string>;
  readonly env: ExecutionArtifactWorkerEnv;
};

export type InternalAuthIdentityOptions = {
  readonly token?: string | undefined;
  readonly tokenVersion?: string | undefined;
};

export type ExecutorIdentityOptions = {
  readonly executorToken?: string | undefined;
  readonly executorTokenVersion?: string | undefined;
  readonly executorTransport?: ExecutionArtifactWorkerExecutorTransport | undefined;
  readonly invokeMaxAttempts?: string | number | undefined;
  readonly projectId?: string | undefined;
};

export type ExecutionArtifactInternalRequestRef = ExecutionArtifactRef;

export type ExecutionArtifactInternalRequestHeadersOptions = {
  readonly ref: ExecutionArtifactInternalRequestRef;
  readonly internalToken?: string | undefined;
};

export type ExecutionArtifactInternalInvokeRequestPayload = {
  readonly deploymentId: string;
  readonly ref: ExecutionArtifactInternalRequestRef;
  readonly request: InvokeRequest;
};

export type ExecutionArtifactInternalInvokeRequestOptions = {
  readonly url: string;
  readonly payload: ExecutionArtifactInternalInvokeRequestPayload;
  readonly internalToken?: string | undefined;
};

type ExecutionArtifactRuntimeWorkerSourceProfileOptions = Omit<
  GeneratedExecutionWorkerSourceOptions,
  "executionModule" | "includeQuerySessionRoute" | "includeUnsupportedCapabilities"
> & {
  readonly includeQuerySessionRoute?: true;
  readonly includeUnsupportedCapabilities?: true;
};

export class ExecutionArtifactWorkerSourceModuleMissingError extends Error {
  readonly status = 400;

  constructor(modulePath: string) {
    super(`Source package module ${modulePath} has no source.`);
    this.name = "ExecutionArtifactWorkerSourceModuleMissingError";
  }
}

export class ExecutionArtifactWorkerReservedModulePathError extends Error {
  readonly status = 400;

  constructor(modulePath: string, reservedBy: string) {
    super(`Source package module path ${modulePath} is reserved by the ${reservedBy}.`);
    this.name = "ExecutionArtifactWorkerReservedModulePathError";
  }
}

export class ExecutionArtifactWorkerDuplicateModulePathError extends Error {
  readonly status = 400;

  constructor(modulePath: string) {
    super(`Source package contains duplicate module path ${modulePath}.`);
    this.name = "ExecutionArtifactWorkerDuplicateModulePathError";
  }
}

const RUNTIME_WORKER_SOURCE_PROFILES = {
  "local-miniflare": {
    headerComment: "// Generated by flarex-dev for local execution-artifact runtime materialization.",
    backendBinding: "FLAREX_BACKEND",
    backendBaseUrl: "https://flarex-backend.internal",
    missingBackendBindingMessage: "FLAREX_BACKEND service binding is required for local execution artifact runtime.",
    includeQuerySessionRoute: true,
  },
  "hosted-dynamic-worker": {
    headerComment: "// Generated by Flarex artifact-runtime for Dynamic Worker execution.",
    backendBinding: "FLAREX_EXECUTOR",
    backendBaseUrl: "https://flarex-executor.internal",
    missingBackendBindingMessage: "FLAREX_EXECUTOR service binding is required for hosted Dynamic Worker execution.",
    includeUnsupportedCapabilities: true,
  },
} satisfies Record<
  ExecutionArtifactRuntimeWorkerSourceProfile,
  ExecutionArtifactRuntimeWorkerSourceProfileOptions
>;

export function executionArtifactRuntimeWorkerSource(
  options: ExecutionArtifactRuntimeWorkerSourceOptions,
): string {
  const profile = RUNTIME_WORKER_SOURCE_PROFILES[options.profile];
  return generatedExecutionWorkerSource({
    ...profile,
    executionModule: options.executionModule,
  });
}

export function executionArtifactWorkerModules(
  options: ExecutionArtifactWorkerModulesOptions,
): Record<string, string> {
  const entries: Array<readonly [string, string]> = [
    [options.runtimeModulePath, options.runtimeWorkerSource],
  ];
  const seenPaths = new Set([options.runtimeModulePath]);
  for (const module of options.sourcePackage.modules) {
    if (module.path === options.runtimeModulePath) {
      throw new ExecutionArtifactWorkerReservedModulePathError(module.path, options.reservedBy);
    }
    if (seenPaths.has(module.path)) {
      throw new ExecutionArtifactWorkerDuplicateModulePathError(module.path);
    }
    seenPaths.add(module.path);
    if (module.source === undefined) {
      throw new ExecutionArtifactWorkerSourceModuleMissingError(module.path);
    }
    entries.push([module.path, module.source]);
  }
  return Object.fromEntries(entries);
}

export function executionArtifactWorkerEnv(
  options: ExecutionArtifactWorkerEnvOptions,
): ExecutionArtifactWorkerEnv {
  return {
    ...(options.executorToken === undefined ? {} : { FLAREX_EXECUTOR_TOKEN: options.executorToken }),
    ...(options.executorTransport === undefined
      ? {}
      : { FLAREX_EXECUTOR_TRANSPORT: options.executorTransport }),
    ...(options.invokeMaxAttempts === undefined
      ? {}
      : { FLAREX_INVOKE_MAX_ATTEMPTS: String(options.invokeMaxAttempts) }),
    ...(options.projectId === undefined ? {} : { FLAREX_PROJECT_ID: options.projectId }),
    ...(options.internalToken === undefined ? {} : { FLAREX_INTERNAL_TOKEN: options.internalToken }),
  };
}

export function executionArtifactWorkerDefinition(
  options: ExecutionArtifactWorkerDefinitionOptions,
): ExecutionArtifactWorkerDefinition {
  return {
    mainModule: options.runtimeModulePath,
    modules: executionArtifactWorkerModules({
      sourcePackage: options.sourcePackage,
      runtimeModulePath: options.runtimeModulePath,
      runtimeWorkerSource: executionArtifactRuntimeWorkerSource({
        profile: options.profile,
        executionModule: options.sourcePackage.execution,
      }),
      reservedBy: options.reservedBy,
    }),
    env: executionArtifactWorkerEnv(options.env ?? {}),
  };
}

export function executorIdentity(options: ExecutorIdentityOptions): string {
  return [
    `transport=${options.executorTransport ?? "legacy"}`,
    `project=${options.projectId ?? "none"}`,
    `attempts=${options.invokeMaxAttempts === undefined ? "default" : String(options.invokeMaxAttempts)}`,
    `auth=${internalAuthIdentity({
      token: options.executorToken,
      tokenVersion: options.executorTokenVersion,
    })}`,
  ].join(",");
}

export function internalAuthIdentity(options: InternalAuthIdentityOptions): string {
  if (options.token === undefined) return "none";
  return options.tokenVersion === undefined ? "enabled-unversioned" : `version-${options.tokenVersion}`;
}

export function executionArtifactInternalRequestHeaders(
  options: ExecutionArtifactInternalRequestHeadersOptions,
): Record<string, string> {
  return {
    "content-type": "application/json",
    "x-flarex-artifact-id": options.ref.artifactId,
    "x-flarex-source-package-hash": options.ref.sourcePackageHash,
    ...(options.internalToken === undefined
      ? {}
      : { authorization: `Bearer ${options.internalToken}` }),
  };
}

export function executionArtifactInternalInvokeRequest(
  options: ExecutionArtifactInternalInvokeRequestOptions,
): Request {
  return new Request(options.url, {
    method: "POST",
    headers: executionArtifactInternalRequestHeaders({
      ref: options.payload.ref,
      internalToken: options.internalToken,
    }),
    body: JSON.stringify({
      deploymentId: options.payload.deploymentId,
      ...options.payload.request,
    }),
  });
}
