import {
  generatedExecutionWorkerSource,
  type GeneratedExecutionWorkerSourceOptions,
} from "./GeneratedWorkerSource.ts";
import type { PushSourcePackage } from "../types.ts";

export type ExecutionArtifactRuntimeWorkerSourceProfile =
  | "local-miniflare"
  | "hosted-dynamic-worker";

export type ExecutionArtifactRuntimeWorkerSourceOptions = {
  readonly profile: ExecutionArtifactRuntimeWorkerSourceProfile;
  readonly executionModule: string;
};

export type ExecutionArtifactWorkerModulesOptions = {
  readonly sourcePackage: PushSourcePackage;
  readonly runtimeModulePath: string;
  readonly runtimeWorkerSource: string;
  readonly reservedBy: string;
};

type ExecutionArtifactRuntimeWorkerSourceProfileOptions = Omit<
  GeneratedExecutionWorkerSourceOptions,
  "executionModule" | "includeQuerySessionRoute" | "includeUnsupportedCapabilities"
> & {
  readonly includeQuerySessionRoute?: true;
  readonly includeUnsupportedCapabilities?: true;
};

export class ExecutionArtifactWorkerSourceModuleMissingError extends Error {
  readonly status = 400;

  constructor(modulePath: string) {
    super(`Source package module ${modulePath} has no source.`);
    this.name = "ExecutionArtifactWorkerSourceModuleMissingError";
  }
}

export class ExecutionArtifactWorkerReservedModulePathError extends Error {
  readonly status = 400;

  constructor(modulePath: string, reservedBy: string) {
    super(`Source package module path ${modulePath} is reserved by the ${reservedBy}.`);
    this.name = "ExecutionArtifactWorkerReservedModulePathError";
  }
}

export class ExecutionArtifactWorkerDuplicateModulePathError extends Error {
  readonly status = 400;

  constructor(modulePath: string) {
    super(`Source package contains duplicate module path ${modulePath}.`);
    this.name = "ExecutionArtifactWorkerDuplicateModulePathError";
  }
}

const RUNTIME_WORKER_SOURCE_PROFILES = {
  "local-miniflare": {
    headerComment: "// Generated by flarex-dev for local execution-artifact runtime materialization.",
    backendBinding: "FLAREX_BACKEND",
    backendBaseUrl: "https://flarex-backend.internal",
    missingBackendBindingMessage: "FLAREX_BACKEND service binding is required for local execution artifact runtime.",
    includeQuerySessionRoute: true,
  },
  "hosted-dynamic-worker": {
    headerComment: "// Generated by Flarex artifact-runtime for Dynamic Worker execution.",
    backendBinding: "FLAREX_EXECUTOR",
    backendBaseUrl: "https://flarex-executor.internal",
    missingBackendBindingMessage: "FLAREX_EXECUTOR service binding is required for hosted Dynamic Worker execution.",
    includeUnsupportedCapabilities: true,
  },
} satisfies Record<
  ExecutionArtifactRuntimeWorkerSourceProfile,
  ExecutionArtifactRuntimeWorkerSourceProfileOptions
>;

export function executionArtifactRuntimeWorkerSource(
  options: ExecutionArtifactRuntimeWorkerSourceOptions,
): string {
  const profile = RUNTIME_WORKER_SOURCE_PROFILES[options.profile];
  return generatedExecutionWorkerSource({
    ...profile,
    executionModule: options.executionModule,
  });
}

export function executionArtifactWorkerModules(
  options: ExecutionArtifactWorkerModulesOptions,
): Record<string, string> {
  const entries: Array<readonly [string, string]> = [
    [options.runtimeModulePath, options.runtimeWorkerSource],
  ];
  const seenPaths = new Set([options.runtimeModulePath]);
  for (const module of options.sourcePackage.modules) {
    if (module.path === options.runtimeModulePath) {
      throw new ExecutionArtifactWorkerReservedModulePathError(module.path, options.reservedBy);
    }
    if (seenPaths.has(module.path)) {
      throw new ExecutionArtifactWorkerDuplicateModulePathError(module.path);
    }
    seenPaths.add(module.path);
    if (module.source === undefined) {
      throw new ExecutionArtifactWorkerSourceModuleMissingError(module.path);
    }
    entries.push([module.path, module.source]);
  }
  return Object.fromEntries(entries);
}
