import {
  MAX_POINT_MUTATION_EXACT_RUNTIME_AUTH_SEMANTIC_BYTES_V1,
  MAX_POINT_MUTATION_EXACT_RUNTIME_CONTEXT_TEXT_BYTES_V1,
} from "flarex-protocol/point-mutation-exact-runtime";
import {
  POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_FORMAT_V1,
  POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1,
  POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_RESULT_FORMAT_V1,
  POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_RESULT_VERSION_V1,
  POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_VERSION_V1,
  type PointMutationInternalQueryExactRuntimeArtifactRefV1,
  type PointMutationInternalQueryExactRuntimeFunctionV1,
} from "flarex-protocol/point-mutation-internal-query-exact-runtime";
import { MAX_POINT_MUTATION_ARGUMENT_ARRAY_SEMANTIC_BYTES_V1 } from
  "flarex-protocol/point-mutation-start";

import { applicationErrorPlatformSourceV1 } from
  "./ApplicationErrorExactRuntimeWorkerSource";

export interface PointMutationInternalQueryExactRuntimeWorkerSourceOptionsV1 {
  readonly moduleTime: number;
  readonly runtimeTargetSha256Hex: string;
  readonly artifact: PointMutationInternalQueryExactRuntimeArtifactRefV1;
  readonly function: PointMutationInternalQueryExactRuntimeFunctionV1;
  readonly rootFunctionOrdinal: bigint;
  readonly internalQueryCatalog: ReadonlyArray<Readonly<{
    readonly functionOrdinal: bigint;
    readonly functionPath: string;
    readonly artifactExecutionModule: string;
    readonly exportName: string;
    readonly argsValidator: unknown;
    readonly returnsValidator: unknown;
  }>>;
}

export function pointMutationInternalQueryExactRuntimeWorkerConfigurationSourceV1(
  options: PointMutationInternalQueryExactRuntimeWorkerSourceOptionsV1,
): string {
  return `// Generated by Flarex for one exact point-mutation Worker.
export const exactRuntimeConfigurationV1 = Object.freeze({
  executionModule: ${JSON.stringify(options.artifact.executionModule)},
  moduleEvaluationTime: ${JSON.stringify(options.moduleTime)},
  pinnedSourcePackageHash: ${JSON.stringify(options.runtimeTargetSha256Hex)},
  requestFormat: ${JSON.stringify(POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_FORMAT_V1)},
  requestVersion: ${POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_VERSION_V1},
  resultFormat: ${JSON.stringify(POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_RESULT_FORMAT_V1)},
  resultVersion: ${POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_RESULT_VERSION_V1},
  maxContextTextBytes: ${MAX_POINT_MUTATION_EXACT_RUNTIME_CONTEXT_TEXT_BYTES_V1},
  maxAuthSemanticBytes: ${MAX_POINT_MUTATION_EXACT_RUNTIME_AUTH_SEMANTIC_BYTES_V1},
  randomSeedBytes: ${POINT_MUTATION_INTERNAL_QUERY_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1},
  maxArgumentArraySemanticBytes: ${MAX_POINT_MUTATION_ARGUMENT_ARRAY_SEMANTIC_BYTES_V1},
  function: Object.freeze(${JSON.stringify(options.function)}),
  rootFunctionOrdinal: ${JSON.stringify(Number(options.rootFunctionOrdinal))},
  internalQueryCatalog: Object.freeze(${JSON.stringify(
    options.internalQueryCatalog.map(entry => ({
      ordinal: Number(entry.functionOrdinal),
      path: entry.functionPath,
      kind: "query",
      visibility: "internal",
      argsValidator: entry.argsValidator,
      returnsValidator: entry.returnsValidator,
    })),
  )}.map(Object.freeze)),
});
`;
}

export function pointMutationInternalQueryExactRuntimeExecutionBridgeSourceV1(
  input: Readonly<{
    readonly root: Readonly<{
      readonly artifactExecutionModule: string;
      readonly exportName: string;
      readonly functionPath: string;
    }>;
    readonly internalQueryCatalog: ReadonlyArray<Readonly<{
      readonly functionPath: string;
      readonly artifactExecutionModule: string;
      readonly exportName: string;
    }>>;
  }>,
): string {
  const entries = [
    { ...input.root, kind: "mutation" as const, visibility: "public" as const },
    ...input.internalQueryCatalog.map(entry => ({
      ...entry,
      kind: "query" as const,
      visibility: "internal" as const,
    })),
  ];
  const imports: string[] = [];
  const registrations: string[] = [];
  for (let index = 0; index < entries.length; index += 1) {
    const entry = entries[index]!;
    const separator = entry.functionPath.indexOf(":");
    if (separator <= 0 || separator !== entry.functionPath.lastIndexOf(":")) {
      throw new Error("Exact point-mutation function path is invalid.");
    }
    imports.push(`import * as applicationModule${index}V1 from ${
      JSON.stringify(`../${entry.artifactExecutionModule}`)};`);
    registrations.push(
      `defineV1(${JSON.stringify(entry.functionPath)}, Object.freeze({ ` +
      `${entry.kind === "mutation" ? "isMutation" : "isQuery"}: true, ` +
      `${entry.visibility === "public" ? "isPublic" : "isInternal"}: true, ` +
      `_handler: applicationModule${index}V1[${JSON.stringify(entry.exportName)}] }));`,
    );
  }
  return `// Generated from authenticated candidate-bound mutation/query entries.
${imports.join("\n")}
const registryV1 = Object.create(null);
function defineV1(pathV1, functionV1) {
  const separatorV1 = pathV1.indexOf(":");
  const moduleV1 = pathV1.slice(0, separatorV1);
  const exportV1 = pathV1.slice(separatorV1 + 1);
  const moduleRegistryV1 = registryV1[moduleV1] ?? (registryV1[moduleV1] = Object.create(null));
  if (Object.hasOwn(moduleRegistryV1, exportV1)) throw new Error("Duplicate exact mutation/query entry.");
  Object.defineProperty(moduleRegistryV1, exportV1, { value: functionV1, enumerable: true });
}
${registrations.join("\n")}
for (const moduleV1 of Object.values(registryV1)) Object.freeze(moduleV1);
export default Object.freeze(registryV1);
`;
}

export function pointMutationInternalQueryExactRuntimePlatformSourceV1(): string {
  return applicationErrorPlatformSourceV1({
    runtimeKernelModulePath:
      "../pointMutationInternalQueryExactRuntimeWorker/flarex-point-mutation-internal-query-runtime-kernel-v1.js",
    captureExportName:
      "capturePointMutationInternalQueryCoreApplicationErrorDataV1",
    invalid: {
      kind: "profileApplicationError",
      exportName: "PointMutationInternalQueryApplicationV1Error",
      reason: "argumentsInvalid",
    },
  });
}
