import {
  POINT_QUERY_EXACT_RUNTIME_FORMAT_V1,
  POINT_QUERY_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1,
  POINT_QUERY_EXACT_RUNTIME_RESULT_FORMAT_V1,
  POINT_QUERY_EXACT_RUNTIME_RESULT_VERSION_V1,
  POINT_QUERY_EXACT_RUNTIME_VERSION_V1,
  type PointQueryExactRuntimeArtifactRefV1,
  type PointQueryExactRuntimeFunctionV1,
} from "flarex-protocol/point-query-exact-runtime";

export interface PointQueryExactRuntimeWorkerSourceOptionsV1 {
  readonly moduleTime: number;
  readonly runtimeTargetSha256Hex: string;
  readonly artifact: PointQueryExactRuntimeArtifactRefV1;
  readonly function: PointQueryExactRuntimeFunctionV1;
  readonly snapshotCommitSeq: bigint;
}

export function pointQueryExactRuntimeWorkerConfigurationSourceV1(
  options: PointQueryExactRuntimeWorkerSourceOptionsV1,
): string {
  return `// Generated by Flarex for one exact point-query Worker.
export const exactQueryRuntimeConfigurationV1 = Object.freeze({
  moduleEvaluationTime: ${JSON.stringify(options.moduleTime)},
  runtimeTargetSha256Hex: ${JSON.stringify(options.runtimeTargetSha256Hex)},
  requestFormat: ${JSON.stringify(POINT_QUERY_EXACT_RUNTIME_FORMAT_V1)},
  requestVersion: ${POINT_QUERY_EXACT_RUNTIME_VERSION_V1},
  resultFormat: ${JSON.stringify(POINT_QUERY_EXACT_RUNTIME_RESULT_FORMAT_V1)},
  resultVersion: ${POINT_QUERY_EXACT_RUNTIME_RESULT_VERSION_V1},
  randomSeedBytes: ${POINT_QUERY_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1},
  artifact: Object.freeze(${JSON.stringify(options.artifact)}),
  function: Object.freeze(${JSON.stringify(options.function)}),
  snapshotCommitSeq: BigInt(${JSON.stringify(String(options.snapshotCommitSeq))}),
});
`;
}

export function pointQueryExactRuntimeExecutionBridgeSourceV1(
  artifactExecutionModule: string,
  exportName: string,
  functionPath: string,
): string {
  const separator = functionPath.indexOf(":");
  if (separator <= 0 || separator !== functionPath.lastIndexOf(":")) {
    throw new Error("Exact point-query function path is invalid.");
  }
  const moduleName = functionPath.slice(0, separator);
  return `// Generated from an authenticated candidate-bound query entry.
import * as applicationModuleV1 from ${JSON.stringify(`../${artifactExecutionModule}`)};
const handlerV1 = applicationModuleV1[${JSON.stringify(exportName)}];
const functionV1 = Object.freeze({ isQuery: true, isPublic: true, _handler: handlerV1 });
export default Object.freeze({ ${JSON.stringify(moduleName)}: Object.freeze({ ${JSON.stringify(exportName)}: functionV1 }) });
`;
}

export function pointQueryExactRuntimePlatformSourceV1(): string {
  return `// Private exact query syscall ABI for one operation-scoped Worker.
const contextsV1 = [];
function currentV1() {
  const contextV1 = contextsV1.at(-1);
  if (contextV1 === undefined) throw new Error("Point-query syscall escaped its invocation context.");
  return contextV1;
}
export async function withPointQueryContextV1(contextV1, operationV1) {
  contextsV1.push(contextV1);
  try { return await operationV1(); }
  finally {
    if (contextsV1.pop() !== contextV1) {
      contextsV1.length = 0;
      throw new Error("Concurrent point-query syscall context is unsupported.");
    }
  }
}
export function authGetUserIdentity() { return currentV1().auth.getUserIdentity(); }
export function databaseGet(documentIdV1) { return currentV1().db.get(documentIdV1); }
`;
}
