import {
  MAX_POINT_MUTATION_EXACT_RUNTIME_AUTH_SEMANTIC_BYTES_V1,
  MAX_POINT_MUTATION_EXACT_RUNTIME_CONTEXT_TEXT_BYTES_V1,
  POINT_MUTATION_EXACT_RUNTIME_ENTRYPOINT_V1,
  POINT_MUTATION_EXACT_RUNTIME_FORMAT_V1,
  POINT_MUTATION_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1,
  POINT_MUTATION_EXACT_RUNTIME_RESULT_FORMAT_V1,
  POINT_MUTATION_EXACT_RUNTIME_RESULT_VERSION_V1,
  POINT_MUTATION_EXACT_RUNTIME_VERSION_V1,
} from "flarex-protocol/point-mutation-exact-runtime";
import {
  MAX_POINT_MUTATION_ARGUMENT_ARRAY_SEMANTIC_BYTES_V1,
} from "flarex-protocol/point-mutation-start";

export interface PointMutationExactRuntimeWorkerSourceOptions {
  readonly executionModule: string;
  readonly moduleTime: number;
  readonly moduleRandomSeedHex: string;
}

/**
 * Generates the dedicated exact-attempt mutation entrypoint.
 *
 * The journal argument is an invocation-scoped Workers RPC capability. It is
 * deliberately absent from env and module state, while resolved tables remain
 * nested RPC capabilities instead of forgeable scalar handles.
 */
export function pointMutationExactRuntimeWorkerSource(
  options: PointMutationExactRuntimeWorkerSourceOptions,
): string {
  return `// Generated by Flarex for exact point-mutation attempt execution.
import { WorkerEntrypoint } from "cloudflare:workers";

const EXECUTION_MODULE = ${JSON.stringify(options.executionModule)};
const MODULE_TIME = ${JSON.stringify(options.moduleTime)};
const MODULE_RANDOM_SEED_HEX = ${JSON.stringify(options.moduleRandomSeedHex)};
const REQUEST_FORMAT = ${JSON.stringify(POINT_MUTATION_EXACT_RUNTIME_FORMAT_V1)};
const REQUEST_VERSION = ${POINT_MUTATION_EXACT_RUNTIME_VERSION_V1};
const RESULT_FORMAT = ${JSON.stringify(POINT_MUTATION_EXACT_RUNTIME_RESULT_FORMAT_V1)};
const RESULT_VERSION = ${POINT_MUTATION_EXACT_RUNTIME_RESULT_VERSION_V1};
const MAX_CONTEXT_TEXT_BYTES = ${MAX_POINT_MUTATION_EXACT_RUNTIME_CONTEXT_TEXT_BYTES_V1};
const MAX_AUTH_SEMANTIC_BYTES = ${MAX_POINT_MUTATION_EXACT_RUNTIME_AUTH_SEMANTIC_BYTES_V1};
const RANDOM_SEED_BYTES = ${POINT_MUTATION_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1};
const MAX_ARGUMENT_ARRAY_SEMANTIC_BYTES = ${MAX_POINT_MUTATION_ARGUMENT_ARRAY_SEMANTIC_BYTES_V1};
const MAX_VALUE_BYTES = 1 << 25;
const MAX_VALUE_NESTING = 64;
const MAX_APP_DOCUMENT_BYTES = 1 << 20;
const MAX_APP_DOCUMENT_NESTING = 16;
const MAX_ARRAY_ITEMS = 8192;
const MAX_OBJECT_FIELDS = 1024;
const MAX_OBJECT_FIELD_BYTES = 1024;
const MAX_CATALOG_TABLE_ID = 2147483647;
const MIN_INT64 = -(1n << 63n);
const MAX_INT64 = (1n << 63n) - 1n;
const textEncoder = new TextEncoder();
const nativeDate = globalThis.Date;
const nativeMath = globalThis.Math;
const nativeCrypto = globalThis.crypto;
const nativePerformance = globalThis.performance;
const nativeIntl = globalThis.Intl;
const nativeScheduler = globalThis.scheduler;
const nativeAbortSignal = globalThis.AbortSignal;
const nativeStructuredClone = globalThis.structuredClone;
const createObject = Object.create;
const defineProperty = Object.defineProperty;
const freeze = Object.freeze;
const getPrototypeOf = Object.getPrototypeOf;
const getOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;
const reflectApply = Reflect.apply;
const reflectConstruct = Reflect.construct;
const reflectOwnKeys = Reflect.ownKeys;
let deterministicTime = MODULE_TIME;
let deterministicRandom = randomFromSeed(hexSeed(MODULE_RANDOM_SEED_HEX));
let runAdmitted = false;

function ExactRuntimeDate(...args) {
  if (new.target === undefined) {
    return new nativeDate(deterministicTime).toString();
  }
  return args.length === 0
    ? reflectConstruct(nativeDate, [deterministicTime], new.target)
    : reflectConstruct(nativeDate, args, new.target);
}

installExactRuntimeIntrinsics();

function installExactRuntimeIntrinsics() {
  ExactRuntimeDate.prototype = nativeDate.prototype;
  defineProperty(nativeDate.prototype, "constructor", {
    value: ExactRuntimeDate,
    enumerable: false,
    configurable: false,
    writable: false,
  });
  defineProperty(ExactRuntimeDate, "now", {
    value: () => deterministicTime,
    enumerable: false,
    configurable: false,
    writable: false,
  });
  defineProperty(ExactRuntimeDate, "parse", {
    value: (value) => reflectApply(nativeDate.parse, nativeDate, [value]),
    enumerable: false,
    configurable: false,
    writable: false,
  });
  defineProperty(ExactRuntimeDate, "UTC", {
    value: (...args) => reflectApply(nativeDate.UTC, nativeDate, args),
    enumerable: false,
    configurable: false,
    writable: false,
  });
  defineProperty(nativeMath, "random", {
    value: () => deterministicRandom(),
    enumerable: false,
    configurable: false,
    writable: false,
  });
  installExactGlobal("Date", ExactRuntimeDate);
  installExactGlobal("Math", nativeMath);
  if (nativeCrypto !== undefined) {
    const unavailableRandom = () => {
      throw new Error("Nondeterministic crypto randomness is unavailable in exact mutation runtime.");
    };
    const exactCrypto = createObject(null);
    defineProperty(exactCrypto, "getRandomValues", {
      value: unavailableRandom,
      enumerable: true,
      configurable: false,
      writable: false,
    });
    if (typeof nativeCrypto.randomUUID === "function") {
      defineProperty(exactCrypto, "randomUUID", {
        value: unavailableRandom,
        enumerable: true,
        configurable: false,
        writable: false,
      });
    }
    if (nativeCrypto.subtle !== undefined) {
      const unavailableSubtle = () => {
        throw new Error(
          "Asynchronous crypto operations are unavailable in exact mutation runtime.",
        );
      };
      const exactSubtle = createObject(null);
      for (const name of [
        "decrypt",
        "deriveBits",
        "deriveKey",
        "digest",
        "encrypt",
        "exportKey",
        "generateKey",
        "importKey",
        "sign",
        "unwrapKey",
        "verify",
        "wrapKey",
      ]) {
        defineProperty(exactSubtle, name, {
          value: unavailableSubtle,
          enumerable: true,
          configurable: false,
          writable: false,
        });
      }
      defineProperty(exactCrypto, "subtle", {
        value: freeze(exactSubtle),
        enumerable: true,
        configurable: false,
        writable: false,
      });
    }
    installExactGlobal("crypto", freeze(exactCrypto));
  }
  const unavailableCache = () => {
    throw new Error("Cloudflare Cache API is unavailable in exact mutation runtime.");
  };
  const exactDefaultCache = createObject(null);
  for (const name of ["delete", "match", "put"]) {
    defineProperty(exactDefaultCache, name, {
      value: unavailableCache,
      enumerable: true,
      configurable: false,
      writable: false,
    });
  }
  const exactCaches = createObject(null);
  defineProperty(exactCaches, "default", {
    value: freeze(exactDefaultCache),
    enumerable: true,
    configurable: false,
    writable: false,
  });
  defineProperty(exactCaches, "open", {
    value: unavailableCache,
    enumerable: true,
    configurable: false,
    writable: false,
  });
  installExactGlobal("caches", freeze(exactCaches));
  if (nativePerformance !== undefined) {
    const exactPerformance = createObject(null);
    defineProperty(exactPerformance, "now", {
      value: () => 0,
      enumerable: true,
      configurable: false,
      writable: false,
    });
    defineProperty(exactPerformance, "timeOrigin", {
      value: MODULE_TIME,
      enumerable: true,
      configurable: false,
      writable: false,
    });
    installExactGlobal("performance", freeze(exactPerformance));
  }
  const unavailableTimer = () => {
    throw new Error("Timers are unavailable in exact mutation runtime.");
  };
  for (const name of ["setTimeout", "setInterval", "setImmediate"]) {
    if (typeof globalThis[name] === "function") {
      installExactGlobal(name, unavailableTimer);
    }
  }
  if (nativeScheduler !== undefined) {
    const exactScheduler = createObject(null);
    for (const name of ["wait", "yield", "postTask"]) {
      defineProperty(exactScheduler, name, {
        value: unavailableTimer,
        enumerable: true,
        configurable: false,
        writable: false,
      });
    }
    installExactGlobal("scheduler", freeze(exactScheduler));
  }
  if (
    nativeAbortSignal !== undefined &&
    typeof nativeAbortSignal.timeout === "function"
  ) {
    defineProperty(nativeAbortSignal, "timeout", {
      value: unavailableTimer,
      enumerable: false,
      configurable: false,
      writable: false,
    });
  }
  if (nativeIntl !== undefined) {
    const exactIntl = createObject(null);
    for (const key of reflectOwnKeys(nativeIntl)) {
      if (key === "DateTimeFormat") continue;
      const descriptor = getOwnPropertyDescriptor(nativeIntl, key);
      if (descriptor !== undefined && "value" in descriptor) {
        defineProperty(exactIntl, key, {
          value: descriptor.value,
          enumerable: descriptor.enumerable,
          configurable: false,
          writable: false,
        });
      }
    }
    defineProperty(ExactRuntimeDateTimeFormat, "supportedLocalesOf", {
      value: (locales, options) =>
        reflectApply(
          nativeIntl.DateTimeFormat.supportedLocalesOf,
          nativeIntl.DateTimeFormat,
          [locales, options],
        ),
      enumerable: false,
      configurable: false,
      writable: false,
    });
    defineProperty(exactIntl, "DateTimeFormat", {
      value: freeze(ExactRuntimeDateTimeFormat),
      enumerable: false,
      configurable: false,
      writable: false,
    });
    installExactGlobal("Intl", freeze(exactIntl));
  }

  installUnavailableAsyncGlobal("fetch");
  installUnavailableAsyncGlobal("MessageChannel");
  installUnavailableAsyncGlobal("BroadcastChannel");
  installUnavailableAsyncGlobal("WebSocketPair");
  installUnavailableAsyncGlobal("File");
  if (globalThis.WebAssembly !== undefined) {
    const exactWebAssembly = createObject(null);
    const blocked = new Set([
      "compile",
      "compileStreaming",
      "instantiate",
      "instantiateStreaming",
    ]);
    for (const key of reflectOwnKeys(globalThis.WebAssembly)) {
      const descriptor = getOwnPropertyDescriptor(globalThis.WebAssembly, key);
      if (descriptor === undefined || !("value" in descriptor)) continue;
      defineProperty(exactWebAssembly, key, {
        value: blocked.has(key)
          ? unavailableAsyncCapability
          : descriptor.value,
        enumerable: descriptor.enumerable,
        configurable: false,
        writable: false,
      });
    }
    installExactGlobal("WebAssembly", freeze(exactWebAssembly));
  }

  hardenIntrinsic("Object", Object);
  hardenIntrinsic("Function", Function);
  hardenIntrinsic("Array", Array);
  hardenIntrinsic("ArrayBuffer", ArrayBuffer);
  hardenIntrinsic("BigInt", BigInt);
  freeze(nativeDate.prototype);
  freeze(nativeDate);
  hardenIntrinsic("Date", ExactRuntimeDate);
  hardenIntrinsic("Error", Error);
  hardenIntrinsic("Map", Map);
  hardenIntrinsic("Number", Number);
  hardenIntrinsic("Promise", Promise);
  hardenIntrinsic("Reflect", Reflect);
  hardenIntrinsic("RegExp", RegExp);
  hardenIntrinsic("Set", Set);
  hardenIntrinsic("String", String);
  hardenIntrinsic("TextEncoder", TextEncoder);
  hardenIntrinsic("Uint8Array", Uint8Array);
  hardenIntrinsic("WeakSet", WeakSet);
  if (nativeAbortSignal !== undefined) {
    hardenIntrinsic("AbortSignal", nativeAbortSignal);
  }
  freeze(nativeMath);
}

function ExactRuntimeDateTimeFormat(...args) {
  const formatter = reflectConstruct(nativeIntl.DateTimeFormat, args);
  const exactFormatter = createObject(null);
  const requireTime = (value) => {
    if (value === undefined) {
      throw new Error(
        "Intl.DateTimeFormat requires an explicit time in exact mutation runtime.",
      );
    }
    return value;
  };
  const format = formatter.format;
  defineProperty(exactFormatter, "format", {
    value: (value) => format(requireTime(value)),
    enumerable: true,
    configurable: false,
    writable: false,
  });
  defineProperty(exactFormatter, "formatToParts", {
    value: (value) =>
      reflectApply(formatter.formatToParts, formatter, [requireTime(value)]),
    enumerable: true,
    configurable: false,
    writable: false,
  });
  defineProperty(exactFormatter, "resolvedOptions", {
    value: () => reflectApply(formatter.resolvedOptions, formatter, []),
    enumerable: true,
    configurable: false,
    writable: false,
  });
  if (typeof formatter.formatRange === "function") {
    defineProperty(exactFormatter, "formatRange", {
      value: (start, end) =>
        reflectApply(
          formatter.formatRange,
          formatter,
          [requireTime(start), requireTime(end)],
        ),
      enumerable: true,
      configurable: false,
      writable: false,
    });
  }
  if (typeof formatter.formatRangeToParts === "function") {
    defineProperty(exactFormatter, "formatRangeToParts", {
      value: (start, end) =>
        reflectApply(
          formatter.formatRangeToParts,
          formatter,
          [requireTime(start), requireTime(end)],
        ),
      enumerable: true,
      configurable: false,
      writable: false,
    });
  }
  return freeze(exactFormatter);
}

const executionModulePromise = import(${JSON.stringify(`./${options.executionModule}`)});

export class ${POINT_MUTATION_EXACT_RUNTIME_ENTRYPOINT_V1} extends WorkerEntrypoint {
  async run(input, journal) {
    if (runAdmitted) {
      throw new Error("Exact point-mutation runtime admits one invocation.");
    }
    runAdmitted = true;
    const request = decodeRequest(input);
    const capability = decodeJournalCapability(journal);
    const fn = await resolveFunction(request.function.path);
    requireExactMutation(fn);
    const handler = handlerFor(fn);
    deterministicTime = request.context.executionTime;
    deterministicRandom = randomFromSeed(request.context.randomSeed);
    const journalRuntime = databaseForJournal(request.tables, capability);
    let handlerResult;
    let handlerFailure;
    try {
      handlerResult = await handler(
        executionContext(request, journalRuntime.database),
        request.arguments,
      );
    } catch (cause) {
      handlerFailure = { cause };
    }
    journalRuntime.close();
    try {
      await journalRuntime.drain();
    } catch (cause) {
      throw journalBoundaryError(cause);
    }
    if (handlerFailure !== undefined) {
      if (handlerFailure.cause instanceof ExactRuntimeJournalBoundaryError) {
        throw handlerFailure.cause;
      }
      throw new ExactRuntimeUserCodeError(handlerFailure.cause);
    }
    try {
      return Object.freeze({
        format: RESULT_FORMAT,
        version: RESULT_VERSION,
        value: normalizeValue(
          handlerResult === undefined ? null : handlerResult,
          "$",
          0,
          new WeakSet(),
        ).value,
      });
    } catch (cause) {
      throw new ExactRuntimeUserCodeError(cause);
    }
  }
}

function hardenIntrinsic(name, value) {
  if (
    value !== null &&
    (typeof value === "object" || typeof value === "function")
  ) {
    if (value.prototype !== undefined) freeze(value.prototype);
    freeze(value);
  }
  installExactGlobal(name, value);
}

function installExactGlobal(name, value) {
  const exactDescriptor = {
    value,
    enumerable: false,
    configurable: false,
    writable: false,
  };
  defineProperty(globalThis, name, exactDescriptor);
  let prototype = getPrototypeOf(globalThis);
  while (prototype !== null) {
    if (getOwnPropertyDescriptor(prototype, name) !== undefined) {
      try {
        defineProperty(prototype, name, exactDescriptor);
      } catch (cause) {
        throw new Error(
          \`Exact mutation runtime cannot neutralize inherited global \${name}.\`,
          { cause },
        );
      }
    }
    prototype = getPrototypeOf(prototype);
  }
}

function unavailableAsyncCapability() {
  throw new Error(
    "Ambient asynchronous capabilities are unavailable in exact mutation runtime.",
  );
}

function installUnavailableAsyncGlobal(name) {
  if (typeof globalThis[name] === "function") {
    installExactGlobal(name, unavailableAsyncCapability);
  }
}

function hexSeed(value) {
  if (!/^[0-9a-f]{64}$/.test(value)) {
    throw new Error("Exact-runtime module seed is invalid.");
  }
  const seed = new Uint8Array(32);
  for (let index = 0; index < seed.length; index += 1) {
    seed[index] = Number.parseInt(value.slice(index * 2, index * 2 + 2), 16);
  }
  return seed;
}

function randomFromSeed(seed) {
  if (!(seed instanceof Uint8Array) || seed.byteLength !== RANDOM_SEED_BYTES) {
    throw new Error("Exact-runtime random seed is invalid.");
  }
  const word = (offset) =>
    (
      seed[offset] |
      (seed[offset + 1] << 8) |
      (seed[offset + 2] << 16) |
      (seed[offset + 3] << 24)
    ) >>> 0;
  let a = (word(0) + ((word(16) << 1) | (word(16) >>> 31)) + 0x9e3779b9) >>> 0;
  let b = (word(4) + ((word(20) << 7) | (word(20) >>> 25)) + 0x243f6a88) >>> 0;
  let c = (word(8) + ((word(24) << 13) | (word(24) >>> 19)) + 0xb7e15162) >>> 0;
  let d = (word(12) + ((word(28) << 19) | (word(28) >>> 13)) + 0xdeadbeef) >>> 0;
  return () => {
    a >>>= 0;
    b >>>= 0;
    c >>>= 0;
    d >>>= 0;
    const result = (((a + b) | 0) + d) | 0;
    d = (d + 1) | 0;
    a = b ^ (b >>> 9);
    b = (c + (c << 3)) | 0;
    c = ((c << 21) | (c >>> 11));
    c = (c + result) | 0;
    return (result >>> 0) / 4294967296;
  };
}

class ExactRuntimeUserCodeError extends Error {
  constructor(cause) {
    super("Exact point-mutation user code failed.");
    this.name = "PointMutationExactRuntimeUserCodeV1Error";
    this.cause = cause;
  }
}

class ExactRuntimeJournalBoundaryError extends Error {
  constructor(cause) {
    super("Exact point-mutation journal boundary failed.");
    this.name = "PointMutationExactRuntimeJournalBoundaryV1Error";
    this.cause = cause;
  }
}

function journalBoundaryError(cause) {
  return cause instanceof ExactRuntimeJournalBoundaryError
    ? cause
    : new ExactRuntimeJournalBoundaryError(cause);
}

function decodeRequest(value) {
  const request = exactRecord(value, [
    "format",
    "version",
    "artifact",
    "function",
    "auth",
    "arguments",
    "argumentArraySemanticBytes",
    "tables",
    "context",
  ], "exact-runtime request");
  if (request.format !== REQUEST_FORMAT || request.version !== REQUEST_VERSION) {
    throw new Error("Unsupported exact-runtime protocol format or version.");
  }
  const artifact = exactRecord(
    request.artifact,
    ["runtime", "artifactId", "sourcePackageHash", "executionModule"],
    "exact-runtime artifact",
  );
  if (
    artifact.runtime !== "dynamic-worker" ||
    !/^artifact_[a-f0-9]{32}$/.test(artifact.artifactId) ||
    !/^[a-f0-9]{64}$/.test(artifact.sourcePackageHash) ||
    artifact.sourcePackageHash !== MODULE_RANDOM_SEED_HEX ||
    artifact.artifactId !== \`artifact_\${artifact.sourcePackageHash.slice(0, 32)}\` ||
    artifact.executionModule !== EXECUTION_MODULE
  ) {
    throw new Error("Invalid exact-runtime artifact pin.");
  }
  const fn = exactRecord(
    request.function,
    ["path", "executionModule", "kind", "visibility"],
    "exact-runtime function",
  );
  if (
    !nonblankPostgresText(fn.path) ||
    fn.executionModule !== EXECUTION_MODULE ||
    fn.kind !== "mutation" ||
    fn.visibility !== "public"
  ) {
    throw new Error("Invalid exact-runtime function pin.");
  }
  const auth = decodeAuth(request.auth);
  const context = decodeContext(request.context);
  const tables = decodeTables(request.tables);
  const normalizedArguments = normalizeValue(
    request.arguments,
    "$.arguments",
    0,
    new WeakSet(),
  );
  if (!isPlainRecord(normalizedArguments.value)) {
    throw new Error("Exact-runtime arguments must be an object.");
  }
  if (
    !Number.isSafeInteger(request.argumentArraySemanticBytes) ||
    request.argumentArraySemanticBytes < 2 ||
    request.argumentArraySemanticBytes > MAX_ARGUMENT_ARRAY_SEMANTIC_BYTES ||
    request.argumentArraySemanticBytes !== normalizedArguments.semanticBytes + 2
  ) {
    throw new Error("Exact-runtime argument semantic size mismatch.");
  }
  return Object.freeze({
    format: request.format,
    version: request.version,
    artifact: Object.freeze({ ...artifact }),
    function: Object.freeze({ ...fn }),
    auth,
    arguments: normalizedArguments.value,
    argumentArraySemanticBytes: request.argumentArraySemanticBytes,
    tables,
    context,
  });
}

function decodeAuth(value) {
  if (!isPlainRecord(value)) {
    throw new Error("Invalid exact-runtime auth projection.");
  }
  if (value.kind === "anonymous") {
    exactKeys(value, ["kind"], "exact-runtime anonymous auth");
    return Object.freeze({ kind: "anonymous" });
  }
  if (value.kind === "user") {
    exactKeys(
      value,
      ["kind", "user"],
      "exact-runtime user auth",
    );
    const ownedUser = reflectApply(
      nativeStructuredClone,
      globalThis,
      [value.user],
    );
    const normalized = normalizeValue(
      ownedUser,
      "$.auth.user",
      0,
      new WeakSet(),
    );
    if (
      normalized.semanticBytes > MAX_AUTH_SEMANTIC_BYTES ||
      !isUserIdentity(ownedUser)
    ) {
      throw new Error("Invalid exact-runtime user auth.");
    }
    freezeJsonValue(ownedUser);
    return Object.freeze({
      kind: "user",
      user: freeze(ownedUser),
    });
  }
  throw new Error("Invalid exact-runtime auth kind.");
}

function decodeContext(value) {
  const context = exactRecord(value, [
    "executionId",
    "logScopeId",
    "randomSeed",
    "executionTime",
    "initialCreationTimeCursor",
  ], "exact-runtime context");
  if (
    !nonblankBoundedText(context.executionId) ||
    !nonblankBoundedText(context.logScopeId) ||
    !(context.randomSeed instanceof Uint8Array) ||
    context.randomSeed.byteLength !== RANDOM_SEED_BYTES ||
    !creationTime(context.executionTime) ||
    !creationTime(context.initialCreationTimeCursor)
  ) {
    throw new Error("Invalid exact-runtime execution context.");
  }
  return Object.freeze({
    executionId: context.executionId,
    logScopeId: context.logScopeId,
    randomSeed: context.randomSeed.slice(),
    executionTime: context.executionTime,
    initialCreationTimeCursor: context.initialCreationTimeCursor,
  });
}

function decodeTables(value) {
  if (!Array.isArray(value) || value.length > MAX_OBJECT_FIELDS) {
    throw new Error("Invalid exact-runtime table projection.");
  }
  validateArrayShape(value, "exact-runtime table projection");
  const ids = new Set();
  const names = new Set();
  const tables = value.map((item) => {
    const table = exactRecord(
      item,
      ["tableId", "logicalName"],
      "exact-runtime table",
    );
    if (
      !Number.isSafeInteger(table.tableId) ||
      table.tableId < 1 ||
      table.tableId > MAX_CATALOG_TABLE_ID ||
      !/^[A-Za-z][A-Za-z0-9_]{0,63}$/.test(table.logicalName) ||
      ids.has(table.tableId) ||
      names.has(table.logicalName)
    ) {
      throw new Error("Invalid exact-runtime table projection.");
    }
    ids.add(table.tableId);
    names.add(table.logicalName);
    return Object.freeze({
      tableId: table.tableId,
      logicalName: table.logicalName,
    });
  });
  return Object.freeze(tables);
}

function decodeJournalCapability(value) {
  if (
    (typeof value !== "object" && typeof value !== "function") ||
    value === null ||
    typeof value.resolvePointTable !== "function"
  ) {
    throw new Error("Exact-runtime journal RPC capability is unavailable.");
  }
  return value;
}

function executionContext(request, database) {
  return Object.freeze({
    auth: Object.freeze({
      getUserIdentity: async () => request.auth.kind === "anonymous"
        ? null
        : reflectApply(
            nativeStructuredClone,
            globalThis,
            [request.auth.user],
          ),
    }),
    db: database,
    runQuery: unsupported("ctx.runQuery"),
    runMutation: unsupported("ctx.runMutation"),
    scheduler: Object.freeze({
      runAfter: unsupported("ctx.scheduler.runAfter"),
      runAt: unsupported("ctx.scheduler.runAt"),
      cancel: unsupported("ctx.scheduler.cancel"),
    }),
    storage: Object.freeze({
      getUrl: unsupported("ctx.storage.getUrl"),
      generateUploadUrl: unsupported("ctx.storage.generateUploadUrl"),
      delete: unsupported("ctx.storage.delete"),
      getMetadata: unsupported("ctx.storage.getMetadata"),
    }),
  });
}

function isUserIdentity(value) {
  if (!isPlainRecord(value)) return false;
  if (
    typeof value.tokenIdentifier !== "string" ||
    typeof value.subject !== "string" ||
    typeof value.issuer !== "string"
  ) {
    return false;
  }
  for (const [key, field] of Object.entries(value)) {
    if (field === undefined) continue;
    if (isKnownStringIdentityClaim(key)) {
      if (typeof field !== "string") return false;
      continue;
    }
    if (isKnownBooleanIdentityClaim(key)) {
      if (typeof field !== "boolean") return false;
      continue;
    }
    if (!isJsonValue(field)) return false;
  }
  return true;
}

function isKnownStringIdentityClaim(key) {
  return (
    key === "tokenIdentifier" ||
    key === "subject" ||
    key === "issuer" ||
    key === "name" ||
    key === "givenName" ||
    key === "familyName" ||
    key === "nickname" ||
    key === "preferredUsername" ||
    key === "profileUrl" ||
    key === "pictureUrl" ||
    key === "email" ||
    key === "gender" ||
    key === "birthday" ||
    key === "timezone" ||
    key === "language" ||
    key === "phoneNumber" ||
    key === "address" ||
    key === "updatedAt"
  );
}

function isKnownBooleanIdentityClaim(key) {
  return key === "emailVerified" || key === "phoneNumberVerified";
}

function isJsonValue(value) {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "boolean"
  ) {
    return true;
  }
  if (typeof value === "number") return Number.isFinite(value);
  if (Array.isArray(value)) return value.every(isJsonValue);
  if (!isPlainRecord(value)) return false;
  return Object.values(value).every(isJsonValue);
}

function freezeJsonValue(value) {
  if (Array.isArray(value)) {
    for (const item of value) freezeJsonValue(item);
    freeze(value);
    return;
  }
  if (value !== null && typeof value === "object") {
    for (const item of Object.values(value)) freezeJsonValue(item);
    freeze(value);
  }
}

function databaseForJournal(tables, journal) {
  const namesById = new Map(
    tables.map((table) => [String(table.tableId), table.logicalName]),
  );
  const idsByName = new Map(
    tables.map((table) => [table.logicalName, String(table.tableId)]),
  );
  const tableCapabilities = new Map();
  let syscallSequence = 0n;
  let operationTail = Promise.resolve();
  let firstOperationFailure;
  let acceptingOperations = true;
  const requireTableName = (name) => {
    if (typeof name !== "string" || name.length === 0) {
      throw new Error("A nonempty app table name is required.");
    }
    const known = tables.some((table) => table.logicalName === name);
    if (!known) throw new Error(\`Unknown app table: \${name}\`);
    return name;
  };
  const resolveTableCapability = async (name) => {
    let capabilityPromise = tableCapabilities.get(name);
    if (capabilityPromise === undefined) {
      capabilityPromise = Promise.resolve(journal.resolvePointTable(name))
        .then((capability) => {
          if (
            (typeof capability !== "object" &&
              typeof capability !== "function") ||
            capability === null ||
            typeof capability.runPointOperation !== "function"
          ) {
            throw new Error(
              "Resolved exact-runtime table capability is invalid.",
            );
          }
          return capability;
        });
      tableCapabilities.set(name, capabilityPromise);
    }
    return capabilityPromise;
  };
  const tableNameForDocumentId = (documentId) => {
    if (!isAppDocumentId(documentId)) {
      throw new Error("A Flarex document ID string is required.");
    }
    const separator = documentId.indexOf(":");
    const name = separator > 0
      ? namesById.get(documentId.slice(0, separator))
      : undefined;
    if (name === undefined) {
      throw new Error("Document ID does not belong to a projected app table.");
    }
    return name;
  };
  const run = (tableName, operation) => {
    if (!acceptingOperations) {
      const failure = journalBoundaryError(
        new Error(
          "Exact-runtime database operation started after handler settlement.",
        ),
      );
      firstOperationFailure ??= { cause: failure };
      throw failure;
    }
    const execution = operationTail.then(async () => {
      if (firstOperationFailure !== undefined) {
        throw firstOperationFailure.cause;
      }
      try {
        const table = await resolveTableCapability(tableName);
        syscallSequence += 1n;
        const outcome = await table.runPointOperation(
          Object.freeze({ ...operation, syscallSequence }),
        );
        return decodeJournalOutcome(
          outcome,
          operation,
          idsByName.get(tableName),
        );
      } catch (cause) {
        const failure = journalBoundaryError(cause);
        firstOperationFailure ??= { cause: failure };
        throw failure;
      }
    });
    operationTail = execution.then(
      () => undefined,
      () => undefined,
    );
    return execution;
  };
  const database = Object.freeze({
    get: (documentId) =>
      trackCallerPromise(run(
        tableNameForDocumentId(documentId),
        { kind: "get", documentId },
      ).then((outcome) =>
        outcome.kind === "missing" ? null : outcome.document
      )),
    insert: (tableName, fields) => {
      const capturedFields = captureDeveloperFields(fields, "insert fields");
      return trackCallerPromise(run(
        requireTableName(tableName),
        { kind: "insert", fields: capturedFields },
      ).then((outcome) => outcome.documentId));
    },
    patch: (documentId, patch) =>
      trackCallerPromise(run(
        tableNameForDocumentId(documentId),
        {
          kind: "patch",
          documentId,
          patch: capturePatch(patch),
        },
      ).then(() => undefined)),
    replace: (documentId, fields) =>
      trackCallerPromise(run(
        tableNameForDocumentId(documentId),
        {
          kind: "replace",
          documentId,
          fields: captureDeveloperFields(fields, "replacement fields"),
        },
      ).then(() => undefined)),
    delete: (documentId) =>
      trackCallerPromise(run(
        tableNameForDocumentId(documentId),
        { kind: "delete", documentId },
      ).then(() => undefined)),
    query: unsupported("ctx.db.query"),
    normalizeId: unsupported("ctx.db.normalizeId"),
    system: Object.freeze({}),
  });
  return Object.freeze({
    database,
    close: () => {
      acceptingOperations = false;
    },
    drain: async () => {
      let observedTail;
      do {
        observedTail = operationTail;
        await observedTail;
        await Promise.resolve();
      } while (operationTail !== observedTail);
      if (firstOperationFailure !== undefined) {
        throw firstOperationFailure.cause;
      }
    },
  });
}

function trackCallerPromise(promise) {
  void promise.catch(() => undefined);
  return promise;
}

function decodeJournalOutcome(value, operation, expectedTableId) {
  if (!isPlainRecord(value)) {
    throw new Error("Exact-runtime journal returned an invalid outcome.");
  }
  switch (operation.kind) {
    case "get":
      if (value.kind === "missing" && value.document === null) {
        exactKeys(value, ["kind", "document"], "exact-runtime missing outcome");
        return Object.freeze({ kind: "missing", document: null });
      }
      if (value.kind === "present" && "document" in value) {
        exactKeys(value, ["kind", "document"], "exact-runtime present outcome");
        return Object.freeze({
          kind: "present",
          document: normalizeJournalDocument(
            value.document,
            operation.documentId,
            expectedTableId,
          ),
        });
      }
      break;
    case "insert":
      if (
        value.kind === "inserted" &&
        isAppDocumentId(value.documentId) &&
        "document" in value
      ) {
        exactKeys(
          value,
          ["kind", "documentId", "document"],
          "exact-runtime inserted outcome",
        );
        return Object.freeze({
          kind: "inserted",
          documentId: value.documentId,
          document: normalizeJournalDocument(
            value.document,
            value.documentId,
            expectedTableId,
          ),
        });
      }
      break;
    case "patch":
    case "replace":
    case "delete":
      if (value.kind === "unit" && value.operation === operation.kind) {
        exactKeys(value, ["kind", "operation"], "exact-runtime unit outcome");
        return Object.freeze({ kind: "unit", operation: operation.kind });
      }
      break;
  }
  throw new Error("Exact-runtime journal returned an invalid outcome.");
}

async function resolveFunction(path) {
  const separator = path.indexOf(":");
  const moduleName = separator === -1 ? path : path.slice(0, separator);
  const exportName = separator === -1 ? "default" : path.slice(separator + 1);
  let executionModule;
  try {
    executionModule = await executionModulePromise;
  } catch (cause) {
    throw new ExactRuntimeUserCodeError(cause);
  }
  const module = executionModule.default?.[moduleName];
  const fn = module?.[exportName];
  if (fn === undefined) throw new Error(\`Unknown Flarex function: \${path}\`);
  return fn;
}

function requireExactMutation(value) {
  if (!isPlainRecord(value)) {
    throw new Error("Exact-runtime function metadata is unavailable.");
  }
  const kinds = ["isQuery", "isMutation", "isWorkflowMutation", "isAction"]
    .filter((marker) => marker in value);
  const visibilities = ["isPublic", "isInternal"]
    .filter((marker) => marker in value);
  if (
    kinds.length !== 1 ||
    kinds[0] !== "isMutation" ||
    visibilities.length !== 1 ||
    visibilities[0] !== "isPublic"
  ) {
    throw new Error("Exact-runtime target must be exactly one public mutation.");
  }
}

function handlerFor(value) {
  if (
    isPlainRecord(value) &&
    Object.hasOwn(value, "_handler") &&
    typeof value._handler === "function"
  ) {
    return value._handler;
  }
  throw new Error("Exact-runtime mutation handler is not executable.");
}

function normalizeValue(value, path, parentNesting, ancestors) {
  if (value === null || typeof value === "boolean") {
    return { value, semanticBytes: 1, nestingDepth: 0 };
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      return { value, semanticBytes: 9, nestingDepth: 0 };
    }
    return { value, semanticBytes: 9, nestingDepth: 0 };
  }
  if (typeof value === "bigint") {
    if (value < MIN_INT64 || value > MAX_INT64) {
      throw new Error(\`\${path} bigint must fit signed int64.\`);
    }
    return { value, semanticBytes: 9, nestingDepth: 0 };
  }
  if (typeof value === "string") {
    if (!value.isWellFormed()) throw new Error(\`\${path} must be well-formed Unicode.\`);
    const semanticBytes = 2 + textEncoder.encode(value).byteLength;
    assertValueSize(semanticBytes, path);
    return { value, semanticBytes, nestingDepth: 0 };
  }
  if (value instanceof ArrayBuffer) {
    const semanticBytes = 2 + value.byteLength;
    assertValueSize(semanticBytes, path);
    return { value: value.slice(0), semanticBytes, nestingDepth: 0 };
  }
  if (Array.isArray(value)) {
    if (value.length > MAX_ARRAY_ITEMS) {
      throw new Error(\`\${path} has too many array items.\`);
    }
    const nesting = parentNesting + 1;
    assertNesting(nesting, path);
    validateArrayShape(value, path);
    return withAncestor(value, path, ancestors, () => {
      let semanticBytes = 2;
      let childNestingDepth = 0;
      const normalized = [];
      for (let index = 0; index < value.length; index += 1) {
        const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
        if (
          descriptor === undefined ||
          !("value" in descriptor) ||
          descriptor.value === undefined
        ) {
          throw new Error(\`\${path} must be a dense data-property array.\`);
        }
        const child = normalizeValue(
          descriptor.value,
          \`\${path}[\${index}]\`,
          nesting,
          ancestors,
        );
        semanticBytes += child.semanticBytes;
        assertValueSize(semanticBytes, path);
        childNestingDepth = Math.max(
          childNestingDepth,
          child.nestingDepth,
        );
        normalized.push(child.value);
      }
      return {
        value: Object.freeze(normalized),
        semanticBytes,
        nestingDepth: 1 + childNestingDepth,
      };
    });
  }
  if (typeof value === "object" && value !== null) {
    if (!isPlainRecord(value)) {
      throw new Error(\`\${path} must be a plain data object.\`);
    }
    const entries = ownEnumerableDataEntries(value, path)
      .filter((entry) => entry[1] !== undefined);
    if (entries.length > MAX_OBJECT_FIELDS) {
      throw new Error(\`\${path} has too many object fields.\`);
    }
    const nesting = parentNesting + 1;
    assertNesting(nesting, path);
    return withAncestor(value, path, ancestors, () => {
      let semanticBytes = 2;
      let childNestingDepth = 0;
      const normalized = {};
      for (const [key, item] of entries.sort(([left], [right]) =>
        left < right ? -1 : left > right ? 1 : 0
      )) {
        if (!isValidObjectField(key)) {
          throw new Error(\`\${path} has an invalid object field.\`);
        }
        const child = normalizeValue(
          item,
          \`\${path}.\${key}\`,
          nesting,
          ancestors,
        );
        semanticBytes += key.length + 1 + child.semanticBytes;
        assertValueSize(semanticBytes, path);
        childNestingDepth = Math.max(
          childNestingDepth,
          child.nestingDepth,
        );
        Object.defineProperty(normalized, key, {
          value: child.value,
          enumerable: true,
          configurable: false,
          writable: false,
        });
      }
      return {
        value: Object.freeze(normalized),
        semanticBytes,
        nestingDepth: 1 + childNestingDepth,
      };
    });
  }
  throw new Error(\`\${path} is not a Flarex runtime value.\`);
}

function normalizeJournalDocument(value, expectedDocumentId, expectedTableId) {
  const normalized = requireAppDocumentBounds(normalizeValue(
    value,
    "$.journal.document",
    0,
    new WeakSet(),
  ));
  if (!isPlainRecord(normalized.value)) {
    throw new Error("Exact-runtime journal document must be an object.");
  }
  if (
    !Object.hasOwn(normalized.value, "_id") ||
    normalized.value._id !== expectedDocumentId ||
    !isAppDocumentId(normalized.value._id) ||
    normalized.value._id.slice(0, normalized.value._id.indexOf(":")) !==
      expectedTableId ||
    !Object.hasOwn(normalized.value, "_creationTime") ||
    !creationTime(normalized.value._creationTime)
  ) {
    throw new Error("Exact-runtime journal document system fields are invalid.");
  }
  return normalized.value;
}

function captureDeveloperFields(value, label) {
  const normalized = requireAppDocumentBounds(normalizeValue(
    value,
    \`$.\${label}\`,
    0,
    new WeakSet(),
  ));
  if (!isPlainRecord(normalized.value)) {
    throw new Error(\`\${label} must be an object.\`);
  }
  if (
    Object.hasOwn(normalized.value, "_id") ||
    Object.hasOwn(normalized.value, "_creationTime")
  ) {
    throw new Error(\`\${label} must not contain reserved system fields.\`);
  }
  return normalized.value;
}

function capturePatch(value) {
  if (!isPlainRecord(value)) {
    throw new Error("Patch must be a plain object.");
  }
  if (Object.getOwnPropertySymbols(value).length > 0) {
    throw new Error("Patch must not contain symbol fields.");
  }
  const fields = Object.keys(value).sort();
  if (fields.length > MAX_OBJECT_FIELDS) {
    throw new Error("Patch has too many fields.");
  }
  const captured = {};
  let semanticBytes = 2;
  let nestingDepth = 1;
  for (const field of fields) {
    if (
      !isValidObjectField(field) ||
      field === "_id" ||
      field === "_creationTime"
    ) {
      throw new Error(\`Patch field \${field} is invalid.\`);
    }
    const descriptor = Object.getOwnPropertyDescriptor(value, field);
    if (
      descriptor === undefined ||
      !descriptor.enumerable ||
      !("value" in descriptor)
    ) {
      throw new Error(\`Patch field \${field} must be an enumerable data field.\`);
    }
    if (descriptor.value === undefined) {
      semanticBytes += field.length + 2;
      assertValueSize(semanticBytes, "$.patch");
      Object.defineProperty(captured, field, {
        value: undefined,
        enumerable: true,
        configurable: false,
        writable: false,
      });
      continue;
    }
    const child = normalizeValue(
      descriptor.value,
      \`$.patch.\${field}\`,
      1,
      new WeakSet(),
    );
    semanticBytes += field.length + 1 + child.semanticBytes;
    assertValueSize(semanticBytes, "$.patch");
    nestingDepth = Math.max(nestingDepth, 1 + child.nestingDepth);
    if (nestingDepth > MAX_VALUE_NESTING) {
      throw new Error("Patch exceeds the exact-runtime nesting limit.");
    }
    Object.defineProperty(captured, field, {
      value: child.value,
      enumerable: true,
      configurable: false,
      writable: false,
    });
  }
  return Object.freeze(captured);
}

function requireAppDocumentBounds(normalized) {
  assertAppDocumentSize(normalized.semanticBytes, "$.appDocument");
  if (normalized.nestingDepth > MAX_APP_DOCUMENT_NESTING) {
    throw new Error("Value exceeds the app-document nesting limit.");
  }
  return normalized;
}

function assertAppDocumentSize(size, path) {
  if (size > MAX_APP_DOCUMENT_BYTES) {
    throw new Error(\`\${path} exceeds the app-document value byte limit.\`);
  }
}

function isValidObjectField(field) {
  if (
    typeof field !== "string" ||
    field.length > MAX_OBJECT_FIELD_BYTES ||
    field.startsWith("$")
  ) {
    return false;
  }
  for (let index = 0; index < field.length; index += 1) {
    const codeUnit = field.charCodeAt(index);
    if (codeUnit < 0x20 || codeUnit >= 0x7f) return false;
  }
  return true;
}

function ownEnumerableDataEntries(value, label) {
  return Reflect.ownKeys(value).map((key) => {
    if (typeof key !== "string") {
      throw new Error(\`\${label} must not contain symbol properties.\`);
    }
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (
      descriptor === undefined ||
      !descriptor.enumerable ||
      !("value" in descriptor)
    ) {
      throw new Error(\`\${label} must contain only enumerable data properties.\`);
    }
    return [key, descriptor.value];
  });
}

function validateArrayShape(value, label) {
  const keys = Reflect.ownKeys(value);
  if (keys.length !== value.length + 1) {
    throw new Error(\`\${label} must be dense and have no extra properties.\`);
  }
  for (const key of keys) {
    if (key === "length") continue;
    if (
      typeof key !== "string" ||
      !/^(0|[1-9][0-9]*)$/.test(key) ||
      Number(key) >= value.length
    ) {
      throw new Error(\`\${label} contains a non-index array property.\`);
    }
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (
      descriptor === undefined ||
      !descriptor.enumerable ||
      !("value" in descriptor)
    ) {
      throw new Error(\`\${label} must contain enumerable data array items.\`);
    }
  }
}

function exactRecord(value, fields, label) {
  if (!isPlainRecord(value)) throw new Error(\`Invalid \${label}.\`);
  exactKeys(value, fields, label);
  return value;
}

function exactKeys(value, fields, label) {
  const keys = Reflect.ownKeys(value);
  if (
    keys.length !== fields.length ||
    keys.some((key) => typeof key !== "string" || !fields.includes(key))
  ) {
    throw new Error(\`Invalid \${label} fields.\`);
  }
  ownEnumerableDataEntries(value, label);
}

function isPlainRecord(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  return (
    (prototype === Object.prototype || prototype === null) &&
    Object.getOwnPropertySymbols(value).length === 0
  );
}

function withAncestor(value, path, ancestors, body) {
  if (ancestors.has(value)) throw new Error(\`\${path} must be acyclic.\`);
  ancestors.add(value);
  try {
    return body();
  } finally {
    ancestors.delete(value);
  }
}

function assertValueSize(size, path) {
  if (size > MAX_VALUE_BYTES) {
    throw new Error(\`\${path} exceeds the exact-runtime value byte limit.\`);
  }
}

function assertNesting(nesting, path) {
  if (nesting > MAX_VALUE_NESTING) {
    throw new Error(\`\${path} exceeds the exact-runtime nesting limit.\`);
  }
}

function nonblankBoundedText(value) {
  return (
    typeof value === "string" &&
    value.trim().length > 0 &&
    textEncoder.encode(value).byteLength <= MAX_CONTEXT_TEXT_BYTES
  );
}

function nonblankPostgresText(value) {
  return (
    typeof value === "string" &&
    value.trim().length > 0 &&
    !value.includes("\\u0000")
  );
}

function creationTime(value) {
  return (
    typeof value === "number" &&
    Number.isFinite(value) &&
    value > 0 &&
    value < 2 ** 53
  );
}

function isAppDocumentId(value) {
  if (typeof value !== "string") return false;
  const separator = value.indexOf(":");
  if (
    separator <= 0 ||
    separator !== value.lastIndexOf(":") ||
    separator === value.length - 1
  ) {
    return false;
  }
  const tableText = value.slice(0, separator);
  if (!/^[1-9][0-9]*$/.test(tableText)) return false;
  const tableId = Number(tableText);
  if (
    !Number.isSafeInteger(tableId) ||
    tableId < 1 ||
    tableId > MAX_CATALOG_TABLE_ID
  ) {
    return false;
  }
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
    .test(value.slice(separator + 1));
}

function unsupported(capability) {
  return () => {
    throw new Error(\`\${capability} is unavailable during exact point-mutation execution.\`);
  };
}
`;
}
