import {
  POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_FORMAT_V1,
  POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1,
  POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_RESULT_FORMAT_V1,
  POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_RESULT_VERSION_V1,
  POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_VERSION_V1,
  type PointQueryInternalCallExactRuntimeArtifactRefV1,
  type PointQueryInternalCallExactRuntimeFunctionV1,
} from "flarex-protocol/point-query-internal-call-exact-runtime";

export interface PointQueryInternalCallExactRuntimeWorkerSourceOptionsV1 {
  readonly moduleTime: number;
  readonly runtimeTargetSha256Hex: string;
  readonly artifact: PointQueryInternalCallExactRuntimeArtifactRefV1;
  readonly function: PointQueryInternalCallExactRuntimeFunctionV1;
  readonly rootFunctionOrdinal: bigint;
  readonly internalQueryCatalog: ReadonlyArray<Readonly<{
    readonly functionOrdinal: bigint;
    readonly functionPath: string;
    readonly artifactExecutionModule: string;
    readonly exportName: string;
    readonly argsValidator: unknown;
    readonly returnsValidator: unknown;
  }>>;
  readonly snapshotCommitSeq: bigint;
}

export function pointQueryInternalCallExactRuntimeWorkerConfigurationSourceV1(
  options: PointQueryInternalCallExactRuntimeWorkerSourceOptionsV1,
): string {
  return `// Generated by Flarex for one exact point-query Worker.
export const exactQueryRuntimeConfigurationV1 = Object.freeze({
  moduleEvaluationTime: ${JSON.stringify(options.moduleTime)},
  runtimeTargetSha256Hex: ${JSON.stringify(options.runtimeTargetSha256Hex)},
  requestFormat: ${JSON.stringify(POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_FORMAT_V1)},
  requestVersion: ${POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_VERSION_V1},
  resultFormat: ${JSON.stringify(POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_RESULT_FORMAT_V1)},
  resultVersion: ${POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_RESULT_VERSION_V1},
  randomSeedBytes: ${POINT_QUERY_INTERNAL_CALL_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1},
  artifact: Object.freeze(${JSON.stringify(options.artifact)}),
  function: Object.freeze(${JSON.stringify(options.function)}),
  rootFunctionOrdinal: ${JSON.stringify(Number(options.rootFunctionOrdinal))},
  internalQueryCatalog: Object.freeze(${JSON.stringify(
    options.internalQueryCatalog.map(entry => ({
      ordinal: Number(entry.functionOrdinal),
      path: entry.functionPath,
      kind: "query",
      visibility: "internal",
      argsValidator: entry.argsValidator,
      returnsValidator: entry.returnsValidator,
    })),
  )}.map(Object.freeze)),
  snapshotCommitSeq: BigInt(${JSON.stringify(String(options.snapshotCommitSeq))}),
});
`;
}

export function pointQueryInternalCallExactRuntimeExecutionBridgeSourceV1(
  input: Readonly<{
    readonly root: Readonly<{
      readonly artifactExecutionModule: string;
      readonly exportName: string;
      readonly functionPath: string;
    }>;
    readonly internalQueryCatalog: ReadonlyArray<Readonly<{
      readonly functionPath: string;
      readonly artifactExecutionModule: string;
      readonly exportName: string;
    }>>;
  }>,
): string {
  const entries = [
    { ...input.root, visibility: "public" as const },
    ...input.internalQueryCatalog.map(entry => ({
      ...entry,
      visibility: "internal" as const,
    })),
  ];
  const imports: string[] = [];
  const registrations: string[] = [];
  for (let index = 0; index < entries.length; index += 1) {
    const entry = entries[index]!;
    const separator = entry.functionPath.indexOf(":");
    if (separator <= 0 || separator !== entry.functionPath.lastIndexOf(":")) {
      throw new Error("Exact point-query function path is invalid.");
    }
    imports.push(`import * as applicationModule${index}V1 from ${
      JSON.stringify(`../${entry.artifactExecutionModule}`)};`);
    registrations.push(
      `defineV1(${JSON.stringify(entry.functionPath)}, Object.freeze({ ` +
      `isQuery: true, ${entry.visibility === "public"
        ? "isPublic"
        : "isInternal"}: true, _handler: applicationModule${index}V1[${
          JSON.stringify(entry.exportName)}] }));`,
    );
  }
  return `// Generated from authenticated candidate-bound query entries.
${imports.join("\n")}
const registryV1 = Object.create(null);
function defineV1(pathV1, functionV1) {
  const separatorV1 = pathV1.indexOf(":");
  const moduleV1 = pathV1.slice(0, separatorV1);
  const exportV1 = pathV1.slice(separatorV1 + 1);
  const moduleRegistryV1 = registryV1[moduleV1] ?? (registryV1[moduleV1] = Object.create(null));
  if (Object.hasOwn(moduleRegistryV1, exportV1)) throw new Error("Duplicate exact query entry.");
  Object.defineProperty(moduleRegistryV1, exportV1, { value: functionV1, enumerable: true });
}
${registrations.join("\n")}
for (const moduleV1 of Object.values(registryV1)) Object.freeze(moduleV1);
export default Object.freeze(registryV1);
`;
}

export function pointQueryInternalCallExactRuntimePlatformSourceV1(): string {
  return `// Private exact query syscall ABI for one operation-scoped Worker.
const contextsV1 = [];
function currentV1() {
  const contextV1 = contextsV1.at(-1);
  if (contextV1 === undefined) throw new Error("Point-query syscall escaped its invocation context.");
  return contextV1;
}
export async function withPointQueryInternalCallContextV1(contextV1, operationV1) {
  contextsV1.push(contextV1);
  try { return await operationV1(); }
  finally {
    if (contextsV1.pop() !== contextV1) {
      contextsV1.length = 0;
      throw new Error("Concurrent point-query syscall context is unsupported.");
    }
  }
}
export function authGetUserIdentity() { return currentV1().auth.getUserIdentity(); }
export function databaseGet(documentIdV1) { return currentV1().db.get(documentIdV1); }
export function runQuery(referenceV1, argsV1) { return currentV1().runQuery(referenceV1, argsV1); }
`;
}
