import {
  MAX_POINT_MUTATION_EXACT_RUNTIME_AUTH_SEMANTIC_BYTES_V1,
  MAX_POINT_MUTATION_EXACT_RUNTIME_CONTEXT_TEXT_BYTES_V1,
  POINT_MUTATION_EXACT_RUNTIME_FORMAT_V1,
  POINT_MUTATION_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1,
  POINT_MUTATION_EXACT_RUNTIME_RESULT_FORMAT_V1,
  POINT_MUTATION_EXACT_RUNTIME_RESULT_VERSION_V1,
  POINT_MUTATION_EXACT_RUNTIME_VERSION_V1,
} from "flarex-protocol/point-mutation-exact-runtime";
import {
  POINT_MUTATION_EXACT_RUNTIME_HOST_RESPONSE_FORMAT_V2,
  POINT_MUTATION_EXACT_RUNTIME_HOST_RESPONSE_VERSION_V2,
} from "flarex-protocol/point-mutation-exact-runtime-host";
import {
  MAX_POINT_MUTATION_ARGUMENT_ARRAY_SEMANTIC_BYTES_V1,
} from "flarex-protocol/point-mutation-start";
import {
  POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1,
} from "./PointMutationExactRuntimeWorkerCore.generated.ts";

export interface PointMutationExactRuntimeWorkerSourceOptions {
  readonly executionModule: string;
  readonly moduleTime: number;
  readonly moduleRandomSeedHex: string;
}

/**
 * Generates the artifact-specific configuration module consumed by the
 * checked, build-produced exact-runtime core.
 */
export function pointMutationExactRuntimeWorkerConfigurationSource(
  options: PointMutationExactRuntimeWorkerSourceOptions,
): string {
  return `// Generated by Flarex for one exact point-mutation Worker.
export const exactRuntimeConfigurationV1 = Object.freeze({
  executionModule: ${JSON.stringify(options.executionModule)},
  moduleEvaluationTime: ${JSON.stringify(options.moduleTime)},
  pinnedSourcePackageHash: ${JSON.stringify(options.moduleRandomSeedHex)},
  requestFormat: ${JSON.stringify(POINT_MUTATION_EXACT_RUNTIME_FORMAT_V1)},
  requestVersion: ${POINT_MUTATION_EXACT_RUNTIME_VERSION_V1},
  resultFormat: ${JSON.stringify(POINT_MUTATION_EXACT_RUNTIME_RESULT_FORMAT_V1)},
  resultVersion: ${POINT_MUTATION_EXACT_RUNTIME_RESULT_VERSION_V1},
  hostResponseFormat: ${JSON.stringify(POINT_MUTATION_EXACT_RUNTIME_HOST_RESPONSE_FORMAT_V2)},
  hostResponseVersion: ${POINT_MUTATION_EXACT_RUNTIME_HOST_RESPONSE_VERSION_V2},
  maxContextTextBytes: ${MAX_POINT_MUTATION_EXACT_RUNTIME_CONTEXT_TEXT_BYTES_V1},
  maxAuthSemanticBytes: ${MAX_POINT_MUTATION_EXACT_RUNTIME_AUTH_SEMANTIC_BYTES_V1},
  randomSeedBytes: ${POINT_MUTATION_EXACT_RUNTIME_RANDOM_SEED_BYTES_V1},
  maxArgumentArraySemanticBytes: ${MAX_POINT_MUTATION_ARGUMENT_ARRAY_SEMANTIC_BYTES_V1},
});
`;
}

/**
 * Generates the only application-code edge in the runtime-owned graph.
 *
 * The bridge lives one module-map directory below the application modules,
 * so the authenticated execution-module path is resolved from its parent.
 */
export function pointMutationExactRuntimeWorkerExecutionBridgeSource(
  executionModule: string,
): string {
  return `// Generated by Flarex for one exact point-mutation Worker.
export { default } from ${JSON.stringify(`../${executionModule}`)};
`;
}

/**
 * @deprecated Prefer the host-produced main, configuration, and execution
 * bridge module graph. This adapter preserves the former single-runtime-module
 * API for external callers while sourcing its implementation from the checked
 * core artifact.
 */
export function pointMutationExactRuntimeWorkerSource(
  options: PointMutationExactRuntimeWorkerSourceOptions,
): string {
  const configurationSource =
    pointMutationExactRuntimeWorkerConfigurationSource(options).replace(
      "export const exactRuntimeConfigurationV1",
      "const exactRuntimeConfigurationV1",
    );
  const withoutConfigurationImport = replaceExactlyOnce(
    POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1,
    'import { exactRuntimeConfigurationV1 } from "./pointMutationExactRuntimeWorker/flarex-point-mutation-exact-runtime-config-v1.js";',
    configurationSource,
  );
  const withDirectExecutionImport = replaceExactlyOnce(
    withoutConfigurationImport,
    '"./pointMutationExactRuntimeWorker/flarex-point-mutation-exact-runtime-execution-v1.js"',
    JSON.stringify(`./${options.executionModule}`),
  );
  return withDirectExecutionImport.replace(
    /\n\/\/# sourceMappingURL=data:application\/json;base64,[A-Za-z0-9+/=]+\n$/,
    "\n",
  );
}

function replaceExactlyOnce(
  source: string,
  search: string,
  replacement: string,
): string {
  const firstIndex = source.indexOf(search);
  if (
    firstIndex === -1 ||
    source.indexOf(search, firstIndex + search.length) !== -1
  ) {
    throw new Error("Exact-runtime compatibility source marker drifted.");
  }
  return source.slice(0, firstIndex) + replacement +
    source.slice(firstIndex + search.length);
}
