// Generated by scripts/buildIdentity.ts. Do not edit by hand.
export const GENERATED_PRIVATE_ANALYZER_IDENTITY_V1 = Object.freeze({
  implementationIdentityMarker:
    "__FLAREX_PRIVATE_ANALYZER_IMPLEMENTATION_V1__8654996ddb4620dc505b31a5d25293d53186891f8bc64c11650a8d06fb948ced__END__",
  implementationIdentityOffset: 45,
  implementationIdentityLength: 64,
  configurationIdentity:
    "62b0a1e20b0b3a06c98c4220cb0f2fd6008c677bbc8ec1e24c986e9fa2c1768a",
  toolchain: Object.freeze({
    wrangler: "4.100.0",
    typescript: "7.0.2",
    effect: "4.0.0-beta.90",
    workersTypes: "4.20260613.1",
    esbuild: "0.27.3",
  }),
});
