// Generated by scripts/buildIdentity.ts. Do not edit by hand.
export const GENERATED_PRIVATE_ANALYZER_IDENTITY_V1 = Object.freeze({
  implementationIdentityMarker:
    "__FLAREX_PRIVATE_ANALYZER_IMPLEMENTATION_V1__b9b9c0588b17197ada79f6dc541211cfcb4a73058ca3380e41039e998774f1ea__END__",
  implementationIdentityOffset: 45,
  implementationIdentityLength: 64,
  configurationIdentity:
    "e9f86d9ee5b5f818adf6df9868729e465a1f7fe3e864e879d2776935bea00196",
  toolchain: Object.freeze({
    wrangler: "4.100.0",
    typescript: "7.0.2",
    effect: "4.0.0-beta.90",
    workersTypes: "4.20260613.1",
    esbuild: "0.27.3",
  }),
});
