import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { transformWithOxc } from "vite";

const PACKAGE_ROOT = fileURLToPath(new URL("..", import.meta.url));
const CORE = path.join(
  PACKAGE_ROOT,
  "src",
  "artifactRuntime",
  "EdgeActionExactRuntimeWorkerCore.ts",
);
const GENERATED = path.join(
  PACKAGE_ROOT,
  "src",
  "artifactRuntime",
  "EdgeActionExactRuntimeWorkerCore.generated.ts",
);

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
) {
  const mode = process.argv[2];
  if (mode !== "update" && mode !== "check") {
    throw new Error("Usage: buildEdgeActionExactRuntimeCore.ts <update|check>");
  }
  const receipt = await buildTwice();
  if (mode === "update") await writeFile(GENERATED, render(receipt), "utf8");
  else if (await readFile(GENERATED, "utf8") !== render(receipt)) {
    throw new Error(
      "Generated edge-action exact runtime core is stale; run edge-action-exact-runtime-core:update.",
    );
  }
  console.log(`Verified edge-action exact runtime core ${receipt.sha256}.`);
}

async function buildTwice() {
  const first = await buildOnce();
  const second = await buildOnce();
  if (first.source !== second.source || first.sha256 !== second.sha256) {
    throw new Error("Edge-action exact runtime core build is not deterministic.");
  }
  return first;
}

async function buildOnce() {
  const input = (await readFile(CORE, "utf8")).replace(/\r\n?/g, "\n");
  const output = await transformWithOxc(
    input,
    "EdgeActionExactRuntimeWorkerCore.ts",
    { sourcemap: true },
  );
  if (output.map === undefined || output.map === null) {
    throw new Error("Edge-action exact runtime core omitted its source map.");
  }
  const map = Buffer.from(JSON.stringify(output.map), "utf8").toString("base64");
  const source = `${output.code}//# sourceMappingURL=data:application/json;base64,${map}\n`;
  return Object.freeze({
    source,
    sha256: createHash("sha256").update(source, "utf8").digest("hex"),
  });
}

function render(receipt: Readonly<{ readonly source: string; readonly sha256: string }>) {
  const lines = receipt.source.match(/[^\n]*\n|[^\n]+$/g) ?? [];
  return [
    "// Generated by scripts/buildEdgeActionExactRuntimeCore.ts. Do not edit by hand.",
    "export const EDGE_ACTION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1 = [",
    ...lines.map(line => `  ${JSON.stringify(line)},`),
    "].join(\"\");",
    "",
    "export const EDGE_ACTION_EXACT_RUNTIME_WORKER_CORE_SHA256_V1 =",
    `  ${JSON.stringify(receipt.sha256)};`,
    "",
  ].join("\n");
}
