import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { transformWithOxc } from "vite";

const PACKAGE_ROOT = fileURLToPath(new URL("..", import.meta.url));
const CORE_PATH = path.join(
  PACKAGE_ROOT,
  "src",
  "artifactRuntime",
  "PointMutationExactRuntimeWorkerCore.ts",
);
const VIRTUAL_CORE_FILENAME = "PointMutationExactRuntimeWorkerCore.ts";
const GENERATED_PATH = path.join(
  PACKAGE_ROOT,
  "src",
  "artifactRuntime",
  "PointMutationExactRuntimeWorkerCore.generated.ts",
);
interface CoreBuildReceipt {
  readonly source: string;
  readonly sha256: string;
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
) {
  const mode = process.argv[2];
  if (mode !== "update" && mode !== "check") {
    throw new Error(
      "Usage: buildPointMutationExactRuntimeCore.ts <update|check>",
    );
  }
  const receipt = mode === "update"
    ? await updatePointMutationExactRuntimeCore()
    : await checkPointMutationExactRuntimeCore();
  console.log(
    `Verified exact point-mutation runtime core ${receipt.sha256} ` +
      "with two byte-identical clean builds.",
  );
}

export async function updatePointMutationExactRuntimeCore(): Promise<
  CoreBuildReceipt
> {
  const receipt = await buildTwice();
  await writeFile(GENERATED_PATH, renderGeneratedModule(receipt), "utf8");
  return receipt;
}

export async function checkPointMutationExactRuntimeCore(): Promise<
  CoreBuildReceipt
> {
  const expected = await buildTwice();
  const generatedUrl = `${pathToFileURL(GENERATED_PATH).href}?check=${Date.now()}`;
  const generated: unknown = await import(generatedUrl);
  if (!isGeneratedCoreModule(generated)) {
    throw new Error("Generated exact-runtime core module has an invalid shape.");
  }
  if (
    generated.POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1 !==
      expected.source ||
    generated.POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SHA256_V1 !==
      expected.sha256
  ) {
    throw new Error(
      "Generated exact point-mutation runtime core is stale; run " +
        "`pnpm exact-runtime-core:update` in packages/flarex-backend.",
    );
  }
  return expected;
}

async function buildTwice(): Promise<CoreBuildReceipt> {
  const first = await buildOnce();
  const second = await buildOnce();
  if (first.source !== second.source || first.sha256 !== second.sha256) {
    throw new Error(
      "Exact point-mutation runtime core builds are not byte-for-byte stable.",
    );
  }
  return first;
}

async function buildOnce(): Promise<CoreBuildReceipt> {
  const input = (await readFile(CORE_PATH, "utf8")).replace(/\r\n?/g, "\n");
  const result = await transformWithOxc(input, VIRTUAL_CORE_FILENAME, {
    sourcemap: true,
  });
  if (result.map === undefined || result.map === null) {
    throw new Error("Exact-runtime core build did not emit a source map.");
  }
  const inlineSourceMap = Buffer.from(
    JSON.stringify(result.map),
    "utf8",
  ).toString("base64");
  const source = `${result.code}//# sourceMappingURL=data:application/json;base64,${inlineSourceMap}\n`;
  return Object.freeze({
    source,
    sha256: createHash("sha256").update(source, "utf8").digest("hex"),
  });
}

function isGeneratedCoreModule(value: unknown): value is Readonly<{
  readonly POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1: string;
  readonly POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SHA256_V1: string;
}> {
  return (
    typeof value === "object" &&
    value !== null &&
    "POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1" in value &&
    typeof value.POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1 ===
      "string" &&
    "POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SHA256_V1" in value &&
    typeof value.POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SHA256_V1 ===
      "string"
  );
}

function renderGeneratedModule(receipt: CoreBuildReceipt): string {
  const sourceLines = receipt.source.match(/[^\n]*\n|[^\n]+$/g) ?? [];
  const renderedLines = sourceLines.map((line) => `  ${JSON.stringify(line)},`);
  return [
    "// Generated by scripts/buildPointMutationExactRuntimeCore.ts. Do not edit by hand.",
    "export const POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SOURCE_V1 = [",
    ...renderedLines,
    '].join("");',
    "",
    "export const POINT_MUTATION_EXACT_RUNTIME_WORKER_CORE_SHA256_V1 =",
    `  ${JSON.stringify(receipt.sha256)};`,
    "",
  ].join("\n");
}
