import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "vite";

const PACKAGE_ROOT = fileURLToPath(new URL("..", import.meta.url));
const ENTRY = path.join(
  PACKAGE_ROOT,
  "..",
  "function-runtime",
  "src",
  "pointQueryInternalCall.ts",
);
const GENERATED = path.join(
  PACKAGE_ROOT, "src", "artifactRuntime", "PointQueryInternalCallRuntimeKernel.generated.ts",
);

if (process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const mode = process.argv[2];
  if (mode !== "update" && mode !== "check") {
    throw new Error("Usage: buildPointQueryInternalCallRuntimeKernel.ts <update|check>");
  }
  const receipt = await buildTwice();
  if (mode === "update") await writeFile(GENERATED, render(receipt), "utf8");
  else {
    const current = await readFile(GENERATED, "utf8");
    if (current !== render(receipt)) throw new Error(
      "Generated internal-call point-query runtime kernel is stale; run point-query-internal-call-runtime-kernel:update.",
    );
  }
  console.log(`Verified internal-call point-query runtime kernel ${receipt.sha256}.`);
}

async function buildTwice() {
  const first = await buildOnce();
  const second = await buildOnce();
  if (first.source !== second.source || first.sha256 !== second.sha256) {
    throw new Error("Internal-call point-query runtime kernel build is not deterministic.");
  }
  return first;
}

async function buildOnce() {
  const output = await build({
    configFile: false,
    logLevel: "silent",
    build: {
      write: false,
      target: "es2022",
      minify: false,
      sourcemap: "inline",
      lib: { entry: ENTRY, formats: ["es"], fileName: () => "kernel.js" },
      rollupOptions: { treeshake: true },
    },
  });
  if (!Array.isArray(output) || output.length !== 1 ||
    !Array.isArray(output[0].output)) {
    throw new Error("Point-query runtime kernel build returned an invalid result.");
  }
  const chunk = output[0].output.find(item => item.type === "chunk");
  if (chunk === undefined || /^\s*import\s/m.test(chunk.code)) {
    throw new Error("Point-query runtime kernel retained a runtime import.");
  }
  const source = chunk.code.replace(/\r\n?/g, "\n");
  return Object.freeze({
    source,
    sha256: createHash("sha256").update(source, "utf8").digest("hex"),
  });
}

function render(receipt: Readonly<{ readonly source: string; readonly sha256: string }>) {
  const lines = receipt.source.match(/[^\n]*\n|[^\n]+$/g) ?? [];
  return [
    "// Generated by scripts/buildPointQueryInternalCallRuntimeKernel.ts. Do not edit by hand.",
    "export const POINT_QUERY_INTERNAL_CALL_RUNTIME_KERNEL_SOURCE_V1 = [",
    ...lines.map(line => `  ${JSON.stringify(line)},`),
    '].join("");',
    "",
    "export const POINT_QUERY_INTERNAL_CALL_RUNTIME_KERNEL_SHA256_V1 =",
    `  ${JSON.stringify(receipt.sha256)};`,
    "",
  ].join("\n");
}
