import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { transformWithOxc } from "vite";

const PACKAGE_ROOT = fileURLToPath(new URL("..", import.meta.url));
const CORE = path.join(
  PACKAGE_ROOT,
  "..",
  "function-runtime",
  "src",
  "functionApiCore.ts",
);
const GENERATED = path.join(
  PACKAGE_ROOT,
  "src",
  "artifactRuntime",
  "FunctionApiCore.generated.ts",
);
const MODULE_SPECIFIER = "flarex:function-api-core/v1";

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
) {
  const mode = process.argv[2];
  if (mode !== "update" && mode !== "check") {
    throw new Error("Usage: buildFunctionApiCore.ts <update|check>");
  }
  const receipt = await buildTwice();
  if (mode === "update") {
    await writeFile(GENERATED, render(receipt), "utf8");
  } else {
    const current = await readFile(GENERATED, "utf8");
    if (current !== render(receipt)) {
      throw new Error(
        "Generated function API core is stale; run function-api-core:update.",
      );
    }
  }
  console.log(`Verified function API core ${receipt.sha256}.`);
}

async function buildTwice(): Promise<Readonly<{
  readonly source: string;
  readonly sha256: string;
}>> {
  const first = await buildOnce();
  const second = await buildOnce();
  if (first.source !== second.source || first.sha256 !== second.sha256) {
    throw new Error("Function API core build is not deterministic.");
  }
  return first;
}

async function buildOnce(): Promise<Readonly<{
  readonly source: string;
  readonly sha256: string;
}>> {
  const input = (await readFile(CORE, "utf8")).replace(/\r\n?/g, "\n");
  const output = await transformWithOxc(input, "functionApiCore.ts", {
    sourcemap: true,
  });
  if (output.map === undefined || output.map === null) {
    throw new Error("Function API core omitted its source map.");
  }
  if (/(?:^|\n)\s*import\b|\bimport\s*\(/m.test(output.code)) {
    throw new Error(
      "Function API core must remain a self-contained exact-graph module.",
    );
  }
  const map = Buffer.from(JSON.stringify(output.map), "utf8").toString("base64");
  const source = `${output.code}//# sourceMappingURL=data:application/json;base64,${map}\n`;
  return Object.freeze({
    source,
    sha256: createHash("sha256").update(source, "utf8").digest("hex"),
  });
}

function render(receipt: Readonly<{
  readonly source: string;
  readonly sha256: string;
}>): string {
  const lines = receipt.source.match(/[^\n]*\n|[^\n]+$/g) ?? [];
  return [
    "// Generated by scripts/buildFunctionApiCore.ts. Do not edit by hand.",
    "export const FUNCTION_API_CORE_MODULE_V1 =",
    `  ${JSON.stringify(MODULE_SPECIFIER)};`,
    "",
    "export const FUNCTION_API_CORE_SOURCE_V1 = [",
    ...lines.map(line => `  ${JSON.stringify(line)},`),
    '].join("");',
    "",
    "export const FUNCTION_API_CORE_SHA256_V1 =",
    `  ${JSON.stringify(receipt.sha256)};`,
    "",
  ].join("\n");
}
