import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { transformWithOxc } from "vite";

const PACKAGE_ROOT = fileURLToPath(new URL("..", import.meta.url));
const KERNEL_PATH = path.join(
  PACKAGE_ROOT,
  "..",
  "function-runtime",
  "src",
  "pointMutation.ts",
);
const VIRTUAL_KERNEL_FILENAME = "pointMutation.ts";
const GENERATED_PATH = path.join(
  PACKAGE_ROOT,
  "src",
  "artifactRuntime",
  "PointMutationRuntimeKernel.generated.ts",
);

interface KernelBuildReceipt {
  readonly source: string;
  readonly sha256: string;
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
) {
  const mode = process.argv[2];
  if (mode !== "update" && mode !== "check") {
    throw new Error(
      "Usage: buildPointMutationRuntimeKernel.ts <update|check>",
    );
  }
  const receipt = mode === "update"
    ? await updatePointMutationRuntimeKernel()
    : await checkPointMutationRuntimeKernel();
  console.log(
    `Verified point-mutation runtime kernel ${receipt.sha256} ` +
      "with two byte-identical clean builds.",
  );
}

export async function updatePointMutationRuntimeKernel(): Promise<
  KernelBuildReceipt
> {
  const receipt = await buildTwice();
  await writeFile(GENERATED_PATH, renderGeneratedModule(receipt), "utf8");
  return receipt;
}

export async function checkPointMutationRuntimeKernel(): Promise<
  KernelBuildReceipt
> {
  const expected = await buildTwice();
  const generatedUrl =
    `${pathToFileURL(GENERATED_PATH).href}?check=${Date.now()}`;
  const generated: unknown = await import(generatedUrl);
  if (!isGeneratedKernelModule(generated)) {
    throw new Error(
      "Generated point-mutation runtime kernel module has an invalid shape.",
    );
  }
  if (
    generated.POINT_MUTATION_RUNTIME_KERNEL_SOURCE_V1 !== expected.source ||
    generated.POINT_MUTATION_RUNTIME_KERNEL_SHA256_V1 !== expected.sha256
  ) {
    throw new Error(
      "Generated point-mutation runtime kernel is stale; run " +
        "`pnpm point-mutation-runtime-kernel:update` in packages/flarex-backend.",
    );
  }
  return expected;
}

async function buildTwice(): Promise<KernelBuildReceipt> {
  const first = await buildOnce();
  const second = await buildOnce();
  if (first.source !== second.source || first.sha256 !== second.sha256) {
    throw new Error(
      "Point-mutation runtime kernel builds are not byte-for-byte stable.",
    );
  }
  return first;
}

async function buildOnce(): Promise<KernelBuildReceipt> {
  const input = (await readFile(KERNEL_PATH, "utf8")).replace(/\r\n?/g, "\n");
  const result = await transformWithOxc(input, VIRTUAL_KERNEL_FILENAME, {
    sourcemap: true,
  });
  if (result.map === undefined || result.map === null) {
    throw new Error("Point-mutation runtime kernel build omitted its source map.");
  }
  if (/^\s*import\s/m.test(result.code)) {
    throw new Error(
      "Point-mutation runtime kernel must not retain runtime imports.",
    );
  }
  const inlineSourceMap = Buffer.from(
    JSON.stringify(result.map),
    "utf8",
  ).toString("base64");
  const source =
    `${result.code}//# sourceMappingURL=data:application/json;base64,${inlineSourceMap}\n`;
  return Object.freeze({
    source,
    sha256: createHash("sha256").update(source, "utf8").digest("hex"),
  });
}

function isGeneratedKernelModule(value: unknown): value is Readonly<{
  readonly POINT_MUTATION_RUNTIME_KERNEL_SOURCE_V1: string;
  readonly POINT_MUTATION_RUNTIME_KERNEL_SHA256_V1: string;
}> {
  return (
    typeof value === "object" &&
    value !== null &&
    "POINT_MUTATION_RUNTIME_KERNEL_SOURCE_V1" in value &&
    typeof value.POINT_MUTATION_RUNTIME_KERNEL_SOURCE_V1 === "string" &&
    "POINT_MUTATION_RUNTIME_KERNEL_SHA256_V1" in value &&
    typeof value.POINT_MUTATION_RUNTIME_KERNEL_SHA256_V1 === "string"
  );
}

function renderGeneratedModule(receipt: KernelBuildReceipt): string {
  const sourceLines = receipt.source.match(/[^\n]*\n|[^\n]+$/g) ?? [];
  const renderedLines = sourceLines.map((line) => `  ${JSON.stringify(line)},`);
  return [
    "// Generated by scripts/buildPointMutationRuntimeKernel.ts. Do not edit by hand.",
    "export const POINT_MUTATION_RUNTIME_KERNEL_SOURCE_V1 = [",
    ...renderedLines,
    '].join("");',
    "",
    "export const POINT_MUTATION_RUNTIME_KERNEL_SHA256_V1 =",
    `  ${JSON.stringify(receipt.sha256)};`,
    "",
  ].join("\n");
}
