import { createHash } from "node:crypto";
import { build } from "vite";

export const MAX_EXACT_RUNTIME_KERNEL_BYTES = 4 * 1024 * 1024;

export interface RuntimeKernelBuildReceipt {
  readonly source: string;
  readonly sha256: string;
  readonly sourceBytes: number;
}

export interface RuntimeKernelBuildOptions {
  readonly entry: string;
  readonly label: string;
  readonly minify: false | "esbuild";
  readonly maximumBytes?: number;
}

export async function buildRuntimeKernelTwice(
  options: RuntimeKernelBuildOptions,
): Promise<RuntimeKernelBuildReceipt> {
  const first = await buildRuntimeKernelOnce(options);
  const second = await buildRuntimeKernelOnce(options);
  if (first.source !== second.source || first.sha256 !== second.sha256) {
    throw new Error(`${options.label} builds are not byte-for-byte stable.`);
  }
  return first;
}

export function renderRuntimeKernelModule(input: {
  readonly generatedBy: string;
  readonly receipt: RuntimeKernelBuildReceipt;
  readonly sourceExport: string;
  readonly sha256Export: string;
}): string {
  const sourceLines = input.receipt.source.match(/[^\n]*\n|[^\n]+$/g) ?? [];
  return [
    `// Generated by ${input.generatedBy}. Do not edit by hand.`,
    `export const ${input.sourceExport} = [`,
    ...sourceLines.map((line) => `  ${JSON.stringify(line)},`),
    '].join("");',
    "",
    `export const ${input.sha256Export} =`,
    `  ${JSON.stringify(input.receipt.sha256)};`,
    "",
  ].join("\n");
}

async function buildRuntimeKernelOnce(
  options: RuntimeKernelBuildOptions,
): Promise<RuntimeKernelBuildReceipt> {
  const output = await build({
    configFile: false,
    logLevel: "silent",
    build: {
      write: false,
      target: "es2022",
      minify: options.minify,
      sourcemap: "inline",
      lib: {
        entry: options.entry,
        formats: ["es"],
        fileName: () => "kernel.js",
      },
      rollupOptions: { treeshake: true },
    },
  });
  if (!Array.isArray(output) || output.length !== 1 ||
    !Array.isArray(output[0].output)) {
    throw new Error(`${options.label} build returned an invalid result.`);
  }
  const emitted = output[0].output;
  if (emitted.length !== 1 || emitted[0]?.type !== "chunk") {
    throw new Error(`${options.label} must emit exactly one JavaScript chunk.`);
  }
  const chunk = emitted[0];
  if (chunk.imports.length !== 0 || chunk.dynamicImports.length !== 0) {
    throw new Error(`${options.label} must not retain runtime imports.`);
  }
  const source = chunk.code.replace(/\r\n?/g, "\n");
  const sourceBytes = Buffer.byteLength(source, "utf8");
  const maximumBytes = options.maximumBytes ?? MAX_EXACT_RUNTIME_KERNEL_BYTES;
  if (sourceBytes > maximumBytes) {
    throw new Error(
      `${options.label} is ${sourceBytes} bytes and exceeds the ` +
        `${maximumBytes}-byte target ceiling.`,
    );
  }
  return Object.freeze({
    source,
    sourceBytes,
    sha256: createHash("sha256").update(source, "utf8").digest("hex"),
  });
}
