import { Result } from "effect";
import { describe, expect, it } from "vitest";

import {
  produceInternalStandardApplicationSourceWithRelations,
  produceStandardApplicationSource,
  STANDARD_APPLICATION_SCHEMA_MODULE_PATH,
  type StandardApplicationSource,
} from "../src/applicationSource";
import {
  StandardApplicationRelationDefinitionError,
} from "../src/relationDefinition/Errors";
import {
  prepareStandardApplicationRelations,
} from "../src/relationDefinition/Preparation";
import { prepareStandardApplicationDefinitionV1 } from "../src/v1";
import * as publicApplicationSource from "../src/applicationSourcePublic";

const UTF8 = new TextDecoder();
const AUTHOR_RELATION_CANONICAL_TEXT =
  '{"format":"flarex.relation-declaration","inverse":{"cardinality":"many","name":"posts"},"localized":false,"onTargetDelete":"restrict","source":{"forwardName":"author","path":[{"kind":"field","name":"author"}],"table":"posts"},"target":{"table":"users"},"value":{"cardinality":"one","required":true},"version":1}';

describe("Standard Application relation definitions", () => {
  it("keeps the relation producer off the established public subpath", () => {
    expect(publicApplicationSource).not.toHaveProperty(
      "produceInternalStandardApplicationSourceWithRelations",
    );
    expect(publicApplicationSource).not.toHaveProperty(
      "ProduceInternalStandardApplicationRelationSourceError",
    );
  });

  it("preserves the established zero-relation schema source exactly", () => {
    const established = Result.getOrThrow(
      produceStandardApplicationSource(preparedDefinition()),
    );
    const throughRelationProducer = Result.getOrThrow(
      produceInternalStandardApplicationSourceWithRelations(
        preparedDefinition(),
        [],
      ),
    );

    expect(schemaSource(established)).toBe([
      "// Generated by @flarex/standard-application-definition.",
      'import { definePartitionTable, defineSchema } from "flarex/server";',
      'import { v } from "flarex/values";',
      'export default defineSchema({ "posts": definePartitionTable(v.object({  })), "users": definePartitionTable(v.object({  })) });',
      "",
    ].join("\n"));
    expect(throughRelationProducer).toEqual(established);
  });

  it("canonicalizes relation order independently of caller order", () => {
    const definition = preparedDefinition();
    const author = oneRelation("author", "posts");
    const editor = oneRelation("editor", "editedPosts");

    const first = Result.getOrThrow(
      produceInternalStandardApplicationSourceWithRelations(
        definition,
        [author, editor],
      ),
    );
    const second = Result.getOrThrow(
      produceInternalStandardApplicationSourceWithRelations(
        definition,
        [editor, author],
      ),
    );

    expect(schemaSource(first)).toBe(schemaSource(second));
  });

  it("owns nested declaration values before publishing canonical evidence", () => {
    const relation = oneRelation("author", "posts");
    const input = [relation];
    const prepared = Result.getOrThrow(
      prepareStandardApplicationRelations(input),
    );

    relation.source.table = "mutated_posts";
    relation.source.path[0]!.name = "mutated_author";
    input.push(oneRelation("editor", "editedPosts"));

    const captured = prepared.declarations[0];
    expect(captured?.canonicalText).toBe(AUTHOR_RELATION_CANONICAL_TEXT);
    expect(captured?.declaration.source.table).toBe("posts");
    expect(captured?.declaration.source.path[0]?.name).toBe("author");
    expect(prepared.declarations).toHaveLength(1);
    expect(Object.isFrozen(prepared)).toBe(true);
    expect(Object.isFrozen(prepared.declarations)).toBe(true);
    expect(Object.isFrozen(captured?.declaration.source.path)).toBe(true);
  });

  it("rejects duplicate canonical declarations with a Standard error", () => {
    const relation = oneRelation("author", "posts");
    const result = prepareStandardApplicationRelations([
      relation,
      structuredClone(relation),
    ]);

    expect(Result.isFailure(result)).toBe(true);
    if (Result.isFailure(result)) {
      expect(result.failure).toBeInstanceOf(
        StandardApplicationRelationDefinitionError,
      );
      expect(result.failure).toMatchObject({
        operation: "prepare",
        reason: "duplicateDeclaration",
        path: "relations[1]",
        conflictsWithPath: "relations[0]",
      });
    }
  });

  it("preserves protocol rejection for an unsupported relation shape", () => {
    const relation = oneRelation("author", "posts");
    const result = prepareStandardApplicationRelations([{
      ...relation,
      localized: true,
    }]);

    expect(Result.isFailure(result)).toBe(true);
    if (Result.isFailure(result)) {
      expect(result.failure).not.toBeInstanceOf(
        StandardApplicationRelationDefinitionError,
      );
      expect(result.failure).toMatchObject({
        _tag: "RelationDeclarationV1Error",
      });
    }
  });

  it("emits the exact executable schema wrapper without a relation API import", () => {
    const source = Result.getOrThrow(
      produceInternalStandardApplicationSourceWithRelations(
        preparedDefinition(),
        [oneRelation("author", "posts")],
      ),
    );
    const generated = schemaSource(source);

    expect(generated).toBe([
      "// Generated by @flarex/standard-application-definition.",
      'import { definePartitionTable, defineSchema } from "flarex/server";',
      'import { v } from "flarex/values";',
      'const schema = defineSchema({ "posts": definePartitionTable(v.object({  })), "users": definePartitionTable(v.object({  })) });',
      `export default { tables: schema.tables, relations: [${AUTHOR_RELATION_CANONICAL_TEXT}] };`,
      "",
    ].join("\n"));
    expect(generated.match(/^import .+;$/gm)).toEqual([
      'import { definePartitionTable, defineSchema } from "flarex/server";',
      'import { v } from "flarex/values";',
    ]);
    expect(generated).not.toContain("relation.one");
    expect(generated).not.toContain("flarex-protocol");
  });
});

function oneRelation(forwardName: string, inverseName: string) {
  return {
    format: "flarex.relation-declaration",
    version: 1,
    source: {
      table: "posts",
      path: [{ kind: "field", name: forwardName }],
      forwardName,
    },
    target: { table: "users" },
    value: { cardinality: "one", required: true },
    inverse: { cardinality: "many", name: inverseName },
    localized: false,
    onTargetDelete: "restrict",
  };
}

function preparedDefinition() {
  return Result.getOrThrow(prepareStandardApplicationDefinitionV1({
    programBudgetInput: {
      maximumModules: 1,
      maximumFunctions: 0,
      maximumIdentifierUtf8Bytes: 1_024,
      maximumValidatorNodes: 32,
      maximumValidatorDepth: 8,
      maximumValidatorStringUtf8Bytes: 1_024,
    },
    programInput: {
      format: "flarex.declarative-program/v1",
      version: 1,
      schema: {
        tables: ["posts", "users"].map(logicalName => ({
          logicalName,
          definition: {
            kind: "appDocument" as const,
            definitionVersion: 1 as const,
            documentType: { type: "object" as const, value: {} },
          },
        })),
        indexes: [],
      },
      modules: [{ modulePath: "empty", functions: [] }],
    },
    materializationBudgetInput: {
      maximumModules: 1,
      maximumEntryBindings: 1,
      maximumSourceBytes: 128,
      maximumSourceMapBytes: 0,
      maximumBytesMaterialized: 4_096,
      maximumSemanticRecords: 8,
      maximumSemanticRecordBytes: 1_024,
      maximumSemanticStreamBytes: 4_096,
    },
    graphInput: {
      modules: [{
        path: "functions/empty.js",
        roles: ["function", "execution"],
        sourceBytes: new TextEncoder().encode("export {};\n"),
        sourceMapBytes: null,
      }],
      functionEntries: [{
        logicalModulePath: "empty",
        artifactModulePath: "functions/empty.js",
      }],
      executionPath: "functions/empty.js",
      schemaPath: null,
      authPath: null,
    },
  }));
}

function schemaSource(
  source: StandardApplicationSource,
): string {
  const module = source.modules.find(
    candidate => candidate.path === STANDARD_APPLICATION_SCHEMA_MODULE_PATH,
  );
  if (module === undefined) throw new Error("Generated schema module is missing.");
  return UTF8.decode(module.sourceBytes);
}
