import { Effect, Schema } from "effect";
import { BigNumber } from "@medusajs/utils/totals/big-number";
import { commerceError } from "@flarex/persistence-postgres/internal/commerce-values";
import { commerceDecoder } from "./commerce-decoder";

const Numeric = Schema.Union([Schema.String, Schema.Number]);
const Raw = Schema.Struct({
  value: Schema.String,
  precision: Schema.Number.check(Schema.isInt(), Schema.isBetween({ minimum: 1, maximum: 100 })),
}).annotate({ parseOptions: { onExcessProperty: "ignore" } });
const decodeInput = commerceDecoder(Numeric, "invalidInput");
const decodeStored = commerceDecoder(Numeric, "storedCorruption");
const decodeRaw = commerceDecoder(Raw, "storedCorruption");
export { Raw as ExactNumericRaw };

/** Native precision semantics, with no number round trip before storage. Raw
 * companions are generated by this owner, never accepted as caller write data. */
export const encodeExactNumeric = Effect.fn("MedusaAdapter.encodeExactNumeric")(function* (input: unknown) {
  const value = yield* Effect.fromResult(decodeInput(input));
  const numeric = yield* Effect.try({ try: () => new BigNumber(value), catch: cause => commerceError("invalidInput", cause) });
  const raw = numeric.raw;
  if (raw === undefined || !Number.isFinite(numeric.numeric) || typeof raw.value !== "string") {
    return yield* Effect.fail(commerceError("invalidInput"));
  }
  return { value: raw.value, raw };
});

/** Call for selected numeric columns only. Physical raw nullability never
 * excuses a missing companion for a present numeric value. */
export const decodeExactNumeric = Effect.fn("MedusaAdapter.decodeExactNumeric")(function* (
  value: unknown, rawValue: unknown, nullable = false,
) {
  if (value === null && rawValue === null && nullable) return null;
  const storedValue = yield* Effect.fromResult(decodeStored(value));
  const raw = yield* Effect.fromResult(decodeRaw(rawValue));
  const numeric = yield* Effect.try({ try: () => new BigNumber(raw), catch: cause => commerceError("storedCorruption", cause) });
  const stored = yield* Effect.try({ try: () => new BigNumber(storedValue), catch: cause => commerceError("storedCorruption", cause) });
  if (!Number.isFinite(numeric.numeric) || numeric.bigNumber === undefined || stored.bigNumber === undefined || !numeric.bigNumber.eq(stored.bigNumber)) {
    return yield* Effect.fail(commerceError("storedCorruption"));
  }
  return numeric.numeric;
});
