import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

export type FlarexGenerateOptions = {
  root: string;
  appDir?: string;
  generatedDir?: string;
  workerName?: string;
};

type DiscoveredFunction = {
  moduleName: string;
  exportName: string;
  kind: string;
};

async function discoverFunctions(functionsDir: string): Promise<DiscoveredFunction[]> {
  const entries = await readdir(functionsDir, { recursive: true, withFileTypes: true }).catch(error => {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  });
  const functions: DiscoveredFunction[] = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
    const absolute = path.join(entry.parentPath, entry.name);
    const source = await readFile(absolute, "utf8");
    const relative = path.relative(functionsDir, absolute).replaceAll("\\", "/").replace(/\.ts$/, "");
    const expression =
      /export\s+const\s+(\w+)\s*=\s*(query|mutation|workflowMutation|action)\s*\(/g;
    for (const match of source.matchAll(expression)) {
      functions.push({ moduleName: relative, exportName: match[1]!, kind: match[2]! });
    }
  }

  return functions.sort((a, b) =>
    `${a.moduleName}:${a.exportName}`.localeCompare(`${b.moduleName}:${b.exportName}`),
  );
}

function typedApi(functions: DiscoveredFunction[]): string {
  const modules = [...new Set(functions.map(fn => fn.moduleName))];
  const imports = modules
    .map(
      (moduleName, index) =>
        `import type * as module${index} from "../functions/${moduleName}";`,
    )
    .join("\n");
  const moduleTypes = modules
    .map((moduleName, index) => `  ${JSON.stringify(moduleName)}: typeof module${index};`)
    .join("\n");

  return `// Generated by flarex-backend. Do not edit.
import { anyApi, type ApiFromModules } from "flarex/server";
${imports}

export const api = anyApi as unknown as ApiFromModules<{
${moduleTypes}
}>;
`;
}

function dataModelSource(): string {
  return `// Generated by flarex-backend. Do not edit.
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
} from "flarex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type Doc<TableName extends TableNamesInDataModel<DataModel>> =
  DocumentByName<DataModel, TableName>;
export type TableNames = TableNamesInDataModel<DataModel>;
`;
}

function serverSource(): string {
  return `// Generated by flarex-backend. Do not edit.
import {
  actionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  mutationGeneric,
  queryGeneric,
  workflowMutationGeneric,
  type ActionBuilder,
  type ActionCtx as GenericActionCtx,
  type MutationBuilder,
  type MutationCtx as GenericMutationCtx,
  type QueryBuilder,
  type QueryCtx as GenericQueryCtx,
} from "flarex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as unknown as QueryBuilder<DataModel, "public">;
export const internalQuery =
  internalQueryGeneric as unknown as QueryBuilder<DataModel, "internal">;
export const mutation = mutationGeneric as unknown as MutationBuilder<DataModel, "public">;
export const internalMutation =
  internalMutationGeneric as unknown as MutationBuilder<DataModel, "internal">;
export const workflowMutation: MutationBuilder<
  DataModel,
  "public",
  "workflowMutation"
> = workflowMutationGeneric as unknown as MutationBuilder<
  DataModel,
  "public",
  "workflowMutation"
>;
export const action = actionGeneric as unknown as ActionBuilder<DataModel, "public">;

export type { DataModel } from "./dataModel";
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
`;
}

function functionMetadataSource(functions: DiscoveredFunction[]): string {
  const modules = [...new Set(functions.map(fn => fn.moduleName))];
  const imports = modules
    .map((moduleName, index) => `import * as module${index} from "../functions/${moduleName}";`)
    .join("\n");
  const registry = functions
    .map(fn => {
      const moduleIndex = modules.indexOf(fn.moduleName);
      return `  ${JSON.stringify(`${fn.moduleName}:${fn.exportName}`)}: module${moduleIndex}.${fn.exportName},`;
    })
    .join("\n");

  return `// Generated by flarex-backend. Do not edit.
import {
  functionArgsToValidatorJson,
  validatorToJson,
  type RegisteredFunction,
} from "flarex/server";
${imports}

const functions: Record<string, RegisteredFunction> = {
${registry}
};

export const functionMetadata = Object.entries(functions).map(([path, fn]) => ({
  path,
  kind: fn.kind,
  visibility: fn.visibility,
  args: functionArgsToValidatorJson(fn.args),
  returns: fn.returns === null ? null : validatorToJson(fn.returns),
}));

export default functionMetadata;
`;
}

function workerSource(functions: DiscoveredFunction[]): string {
  const modules = [...new Set(functions.map(fn => fn.moduleName))];
  const imports = modules
    .map((moduleName, index) => `import * as module${index} from "../functions/${moduleName}";`)
    .join("\n");
  const registry = functions
    .map(fn => {
      const moduleIndex = modules.indexOf(fn.moduleName);
      return `  ${JSON.stringify(`${fn.moduleName}:${fn.exportName}`)}: module${moduleIndex}.${fn.exportName},`;
    })
    .join("\n");

  return `// Generated by flarex-backend. Do not edit.
import { DurableObject } from "cloudflare:workers";
import {
  createQueryInitializer,
  parseFlarexId,
  validateFunctionArgs,
  validateValue,
  type DatabaseQueryRequest,
  type DatabaseQueryResult,
  type DatabaseWriter,
  type RegisteredFunction,
} from "flarex/server";
import schema from "../schema";
${imports}

const functions: Record<string, RegisteredFunction> = {
${registry}
};

const tableMetadata = Object.fromEntries(
  Object.entries(schema.tables)
    .filter(([, definition]) => definition.kind === "table")
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name], index) => [name, { tableId: index + 1, name }]),
) as Record<string, { tableId: number; name: string }>;

const tableNamesById = new Map(
  Object.values(tableMetadata).map(table => [table.tableId, table.name] as const),
);

export interface Env {
  CONNECTIONS: DurableObjectNamespace<ConnectionDO>;
  FLAREX_BACKEND: Fetcher;
  FLAREX_DEPLOYMENT_ID?: string;
}

export class ConnectionDO extends DurableObject<Env> {
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade") !== "websocket") {
      return Response.json({ service: "flarex-connection", status: "ok" });
    }
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair) as [WebSocket, WebSocket];
    this.ctx.acceptWebSocket(server);
    server.send(JSON.stringify({ type: "Connected", protocol: "flarex-v0" }));
    return new Response(null, { status: 101, webSocket: client });
  }
}

function validateFunctionReturn(validator: RegisteredFunction["returns"], value: unknown): void {
  if (validator === null) return;
  validateValue(validator, value, "$return", { validateId: validateTableNameId });
}

function validateTableNameId(tableName: string, value: string, path: string): void {
  const expected = tableMetadata[tableName];
  if (!expected) {
    throw new Error(\`\${path}: Unknown table \${tableName} for ID validator.\`);
  }
  const parsed = parseFlarexId(value);
  if (parsed === null) {
    throw new Error(\`\${path}: Expected an ID for table \${tableName}.\`);
  }
  if (parsed.tableId !== expected.tableId) {
    const actualTableName = tableNamesById.get(parsed.tableId);
    const suffix = actualTableName === undefined ? "" : \`, got an ID for table \${actualTableName}\`;
    throw new Error(\`\${path}: Expected an ID for table \${tableName}\${suffix}.\`);
  }
}

type InvokeBody = {
  path: string;
  args: unknown;
  partitionKey?: string;
  deploymentId?: string;
  idempotencyKey?: string;
};

type ExecutionStartResponse = {
  sessionId: string;
  kind: "query" | "mutation";
};

async function invokeWithBackend(body: InvokeBody, env: Env, request: Request): Promise<unknown> {
  const fn = functions[body.path];
  if (!fn) throw new Error(\`Unknown Flarex function: \${body.path}\`);
  if (fn.kind !== "query" && fn.kind !== "mutation") {
    throw new Error(\`\${fn.kind} execution is not implemented by /invoke\`);
  }
  validateFunctionArgs(fn.args, body.args, { validateId: validateTableNameId });

  const deploymentId =
    request.headers.get("x-flarex-deployment") ?? body.deploymentId ?? env.FLAREX_DEPLOYMENT_ID;
  if (!deploymentId) throw new Error("A deploymentId or x-flarex-deployment header is required.");
  const partitionKey = request.headers.get("x-flarex-partition") ?? body.partitionKey;
  if (!partitionKey) throw new Error("A partitionKey or x-flarex-partition header is required.");

  const start = await postBackend<ExecutionStartResponse>(
    env.FLAREX_BACKEND,
    \`/deployments/\${deploymentId}/executions/start\`,
    {
      path: body.path,
      args: body.args,
      kind: fn.kind,
      partitionKey,
      ...(body.idempotencyKey === undefined ? {} : { idempotencyKey: body.idempotencyKey }),
    },
  );
  try {
    const db = databaseForSession(env.FLAREX_BACKEND, deploymentId, start.sessionId, start.kind);
    const value = await fn.handler({ db } as never, body.args as never);
    validateFunctionReturn(fn.returns, value);
    return await postBackend(env.FLAREX_BACKEND, \`/deployments/\${deploymentId}/executions/\${start.sessionId}/finish\`, {
      value,
    });
  } catch (error) {
    await postBackend(env.FLAREX_BACKEND, \`/deployments/\${deploymentId}/executions/\${start.sessionId}/abort\`, {}).catch(
      () => undefined,
    );
    throw error;
  }
}

function databaseForSession(
  backend: Fetcher,
  deploymentId: string,
  sessionId: string,
  kind: "query" | "mutation",
): DatabaseWriter {
  const syscall = (body: unknown) =>
    postBackend<unknown>(backend, \`/deployments/\${deploymentId}/executions/\${sessionId}/syscall\`, body);
  const query = (request: DatabaseQueryRequest) =>
    syscall({ op: "query", request }) as Promise<DatabaseQueryResult>;
  return {
    get: id => syscall({ op: "get", id }) as never,
    query: table => createQueryInitializer(table, query),
    insert: async (table, value) => {
      if (kind !== "mutation") throw new Error("Cannot insert during a query.");
      return (await syscall({ op: "insert", table, value })) as never;
    },
    patch: async (id, value) => {
      if (kind !== "mutation") throw new Error("Cannot patch during a query.");
      await syscall({ op: "patch", id, value });
    },
    delete: async id => {
      if (kind !== "mutation") throw new Error("Cannot delete during a query.");
      await syscall({ op: "delete", id });
    },
  };
}

async function postBackend<T>(backend: Fetcher, path: string, body: unknown): Promise<T> {
  const response = await backend.fetch(\`https://flarex-backend.internal\${path}\`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const value = await response.json().catch(() => null);
  if (!response.ok) {
    const message =
      typeof value === "object" && value !== null && "error" in value
        ? String((value as { error: unknown }).error)
        : \`Backend request failed with status \${response.status}\`;
    throw new Error(message);
  }
  return value as T;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/sync") {
      const session = request.headers.get("x-flarex-session") ?? crypto.randomUUID();
      return env.CONNECTIONS.getByName(session).fetch(request);
    }
    if (url.pathname === "/invoke" && request.method === "POST") {
      try {
        return Response.json(await invokeWithBackend(await request.json<InvokeBody>(), env, request));
      } catch (error) {
        return Response.json(
          { error: error instanceof Error ? error.message : String(error) },
          { status: 400 },
        );
      }
    }
    if (url.pathname === "/health") {
      return Response.json({ service: "flarex", status: "ok" });
    }
    return Response.json({ error: "Not implemented." }, { status: 501 });
  },
} satisfies ExportedHandler<Env>;
`;
}

export async function generateFlarex(options: FlarexGenerateOptions): Promise<void> {
  const appDir = path.resolve(options.root, options.appDir ?? "flarex");
  const generatedDir = path.resolve(appDir, options.generatedDir ?? "_generated");
  const functions = await discoverFunctions(path.join(appDir, "functions"));
  await mkdir(generatedDir, { recursive: true });

  await writeFile(
    path.join(generatedDir, "server.ts"),
    serverSource(),
  );
  await writeFile(path.join(generatedDir, "dataModel.ts"), dataModelSource());
  await writeFile(
    path.join(generatedDir, "api.ts"),
    typedApi(functions),
  );
  await writeFile(path.join(generatedDir, "functionMetadata.ts"), functionMetadataSource(functions));
  await writeFile(path.join(generatedDir, "worker.ts"), workerSource(functions));

  const wrangler = {
    $schema: "node_modules/wrangler/config-schema.json",
    name: options.workerName ?? "flarex-example",
    main: "flarex/_generated/worker.ts",
    compatibility_date: "2026-06-14",
    durable_objects: {
      bindings: [
        { name: "CONNECTIONS", class_name: "ConnectionDO" },
      ],
    },
    services: [{ binding: "FLAREX_BACKEND", service: "flarex-backend" }],
    migrations: [{ tag: "v1", new_sqlite_classes: ["ConnectionDO"] }],
  };
  await writeFile(
    path.join(options.root, "wrangler.generated.jsonc"),
    `${JSON.stringify(wrangler, null, 2)}\n`,
  );
}
