import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

export type FlarexGenerateOptions = {
  root: string;
  appDir?: string;
  generatedDir?: string;
  workerName?: string;
};

type DiscoveredFunction = {
  moduleName: string;
  exportName: string;
  kind: string;
};

async function discoverFunctions(functionsDir: string): Promise<DiscoveredFunction[]> {
  const entries = await readdir(functionsDir, { recursive: true, withFileTypes: true }).catch(error => {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  });
  const functions: DiscoveredFunction[] = [];

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
    const absolute = path.join(entry.parentPath, entry.name);
    const source = await readFile(absolute, "utf8");
    const relative = path.relative(functionsDir, absolute).replaceAll("\\", "/").replace(/\.ts$/, "");
    const expression =
      /export\s+const\s+(\w+)\s*=\s*(query|mutation|workflowMutation|action)\s*\(/g;
    for (const match of source.matchAll(expression)) {
      functions.push({ moduleName: relative, exportName: match[1]!, kind: match[2]! });
    }
  }

  return functions.sort((a, b) =>
    `${a.moduleName}:${a.exportName}`.localeCompare(`${b.moduleName}:${b.exportName}`),
  );
}

function typedApi(functions: DiscoveredFunction[]): string {
  const modules = [...new Set(functions.map(fn => fn.moduleName))];
  const imports = modules
    .map(
      (moduleName, index) =>
        `import type * as module${index} from "../functions/${moduleName}";`,
    )
    .join("\n");
  const moduleTypes = modules
    .map((moduleName, index) => `  ${JSON.stringify(moduleName)}: typeof module${index};`)
    .join("\n");

  return `// Generated by flarex-backend. Do not edit.
import { anyApi, type ApiFromModules } from "flarex/server";
${imports}

export const api = anyApi as unknown as ApiFromModules<{
${moduleTypes}
}>;
`;
}

function dataModelSource(): string {
  return `// Generated by flarex-backend. Do not edit.
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
} from "flarex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type Doc<TableName extends TableNamesInDataModel<DataModel>> =
  DocumentByName<DataModel, TableName>;
export type TableNames = TableNamesInDataModel<DataModel>;
`;
}

function serverSource(): string {
  return `// Generated by flarex-backend. Do not edit.
import {
  actionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  mutationGeneric,
  queryGeneric,
  workflowMutationGeneric,
  type ActionBuilder,
  type ActionCtx as GenericActionCtx,
  type MutationBuilder,
  type MutationCtx as GenericMutationCtx,
  type QueryBuilder,
  type QueryCtx as GenericQueryCtx,
} from "flarex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as unknown as QueryBuilder<DataModel, "public">;
export const internalQuery =
  internalQueryGeneric as unknown as QueryBuilder<DataModel, "internal">;
export const mutation = mutationGeneric as unknown as MutationBuilder<DataModel, "public">;
export const internalMutation =
  internalMutationGeneric as unknown as MutationBuilder<DataModel, "internal">;
export const workflowMutation: MutationBuilder<
  DataModel,
  "public",
  "workflowMutation"
> = workflowMutationGeneric as unknown as MutationBuilder<
  DataModel,
  "public",
  "workflowMutation"
>;
export const action = actionGeneric as unknown as ActionBuilder<DataModel, "public">;

export type { DataModel } from "./dataModel";
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
`;
}

function functionMetadataSource(functions: DiscoveredFunction[]): string {
  const modules = [...new Set(functions.map(fn => fn.moduleName))];
  const imports = modules
    .map((moduleName, index) => `import * as module${index} from "../functions/${moduleName}";`)
    .join("\n");
  const registry = functions
    .map(fn => {
      const moduleIndex = modules.indexOf(fn.moduleName);
      return `  ${JSON.stringify(`${fn.moduleName}:${fn.exportName}`)}: module${moduleIndex}.${fn.exportName},`;
    })
    .join("\n");

  return `// Generated by flarex-backend. Do not edit.
import {
  functionArgsToValidatorJson,
  validatorToJson,
  type RegisteredFunction,
} from "flarex/server";
${imports}

const functions: Record<string, RegisteredFunction> = {
${registry}
};

export const functionMetadata = Object.entries(functions).map(([path, fn]) => ({
  path,
  kind: fn.kind,
  visibility: fn.visibility,
  args: functionArgsToValidatorJson(fn.args),
  returns: fn.returns === null ? null : validatorToJson(fn.returns),
}));

export default functionMetadata;
`;
}

function workerSource(functions: DiscoveredFunction[]): string {
  const modules = [...new Set(functions.map(fn => fn.moduleName))];
  const imports = modules
    .map((moduleName, index) => `import * as module${index} from "../functions/${moduleName}";`)
    .join("\n");
  const registry = functions
    .map(fn => {
      const moduleIndex = modules.indexOf(fn.moduleName);
      return `  ${JSON.stringify(`${fn.moduleName}:${fn.exportName}`)}: module${moduleIndex}.${fn.exportName},`;
    })
    .join("\n");

  return `// Generated by flarex-backend. Do not edit.
import { DurableObject } from "cloudflare:workers";
import {
  createQueryInitializer,
  encodeFlarexId,
  parseFlarexId,
  validateFunctionArgs,
  validateValue,
  type DatabaseQueryRequest,
  type DatabaseWriter,
  type RegisteredFunction,
} from "flarex/server";
import schema from "../schema";
${imports}

const functions: Record<string, RegisteredFunction> = {
${registry}
};

const tableMetadata = Object.fromEntries(
  Object.entries(schema.tables)
    .filter(([, definition]) => definition.kind === "table")
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name], index) => [name, { tableId: index + 1, name }]),
) as Record<string, { tableId: number; name: string }>;

const tableNamesById = new Map(
  Object.values(tableMetadata).map(table => [table.tableId, table.name] as const),
);

export interface Env {
  CONNECTIONS: DurableObjectNamespace<ConnectionDO>;
  PARTITIONS: DurableObjectNamespace<PartitionDO>;
}

export class ConnectionDO extends DurableObject<Env> {
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade") !== "websocket") {
      return Response.json({ service: "flarex-connection", status: "ok" });
    }
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair) as [WebSocket, WebSocket];
    this.ctx.acceptWebSocket(server);
    server.send(JSON.stringify({ type: "Connected", protocol: "flarex-v0" }));
    return new Response(null, { status: 101, webSocket: client });
  }
}

export class PartitionDO extends DurableObject<Env> {
  private readonly sql = this.ctx.storage.sql;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.sql.exec(\`
      CREATE TABLE IF NOT EXISTS documents (
        id TEXT PRIMARY KEY,
        table_name TEXT NOT NULL,
        value TEXT NOT NULL,
        updated_at INTEGER NOT NULL
      );
      CREATE INDEX IF NOT EXISTS documents_by_table ON documents(table_name);
    \`);
  }

  private database(): DatabaseWriter {
    const query = async (request: DatabaseQueryRequest) => {
      const rows = this.sql.exec<{ value: string }>(
        "SELECT value FROM documents WHERE table_name = ? ORDER BY updated_at, id",
        request.table,
      ).toArray();
      const documents = rows.map(row => JSON.parse(row.value) as Record<string, unknown>);
      const expressions = request.range?.expressions ?? [];
      const filtered = documents.filter(document =>
        expressions.every(expression =>
          matchesExpression(fieldValue(document, expression.field), expression.op, expression.value),
        ),
      );
      const ordered = filtered.sort((left, right) =>
        String(left._id).localeCompare(String(right._id)),
      );
      if (request.order === "desc") ordered.reverse();
      const afterCursor =
        request.cursor === undefined
          ? ordered
          : ordered.filter(document =>
              request.order === "desc"
                ? String(document._id) < request.cursor!
                : String(document._id) > request.cursor!,
            );
      const limit = request.limit ?? afterCursor.length;
      const page = afterCursor.slice(0, limit);
      return {
        page,
        isDone: afterCursor.length <= limit,
        continueCursor: String(page.at(-1)?._id ?? request.cursor ?? ""),
      };
    };
    return {
      get: async id => {
        const rows = this.sql.exec<{ value: string }>(
          "SELECT value FROM documents WHERE id = ?",
          id,
        ).toArray();
        return rows[0] ? JSON.parse(rows[0].value) : null;
      },
      query: table => createQueryInitializer(table, query),
      insert: async (table, value) => {
        validateTableValue(table, value);
        const metadata = tableMetadata[table];
        if (!metadata) throw new Error(\`Unknown table: \${table}\`);
        const id = encodeFlarexId(metadata.tableId);
        this.sql.exec(
          "INSERT INTO documents (id, table_name, value, updated_at) VALUES (?, ?, ?, ?)",
          id,
          table,
          JSON.stringify({ ...(value as object), _id: id }),
          Date.now(),
        );
        return id as never;
      },
      patch: async (id, value) => {
        const current = await this.database().get(id);
        if (current === null) throw new Error(\`Document not found: \${id}\`);
        const next = { ...(current as object), ...(value as object) };
        validateTableValue(tableNameForId(id), withoutSystemFields(next));
        this.sql.exec(
          "UPDATE documents SET value = ?, updated_at = ? WHERE id = ?",
          JSON.stringify({ ...(current as object), ...(value as object), _id: id }),
          Date.now(),
          id,
        );
      },
      delete: async id => {
        this.sql.exec("DELETE FROM documents WHERE id = ?", id);
      },
    };
  }

  private async invoke(path: string, args: unknown): Promise<unknown> {
    const fn = functions[path];
    if (!fn) throw new Error(\`Unknown Flarex function: \${path}\`);
    validateFunctionArgs(fn.args, args, { validateId: validateTableNameId });
    const execute = async () => {
      const value = await fn.handler({ db: this.database() } as never, args as never);
      validateFunctionReturn(fn.returns, value);
      return value;
    };
    if (fn.kind === "query") return execute();
    if (fn.kind !== "mutation") {
      throw new Error(\`\${fn.kind} execution is not implemented in the partition runtime\`);
    }

    return this.ctx.storage.transaction(async () => execute());
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/health") {
      return Response.json({ service: "flarex-partition", status: "ok" });
    }
    if (url.pathname === "/invoke" && request.method === "POST") {
      try {
        const body = await request.json<{ path: string; args: unknown }>();
        return Response.json({ value: await this.invoke(body.path, body.args) });
      } catch (error) {
        return Response.json(
          { error: error instanceof Error ? error.message : String(error) },
          { status: 400 },
        );
      }
    }
    return Response.json({ error: "Not implemented." }, { status: 501 });
  }
}

function validateFunctionReturn(validator: RegisteredFunction["returns"], value: unknown): void {
  if (validator === null) return;
  validateValue(validator, value, "$return", { validateId: validateTableNameId });
}

function validateTableValue(table: string, value: unknown): void {
  const definition = Object.entries(schema.tables).find(([name]) => name === table)?.[1];
  if (!definition || definition.kind !== "table") throw new Error(\`Unknown table: \${table}\`);
  validateValue(definition.validator, value, \`$document(\${table})\`, {
    validateId: validateTableNameId,
  });
}

function validateTableNameId(tableName: string, value: string, path: string): void {
  const expected = tableMetadata[tableName];
  if (!expected) {
    throw new Error(\`\${path}: Unknown table \${tableName} for ID validator.\`);
  }
  const parsed = parseFlarexId(value);
  if (parsed === null) {
    throw new Error(\`\${path}: Expected an ID for table \${tableName}.\`);
  }
  if (parsed.tableId !== expected.tableId) {
    const actualTableName = tableNamesById.get(parsed.tableId);
    const suffix = actualTableName === undefined ? "" : \`, got an ID for table \${actualTableName}\`;
    throw new Error(\`\${path}: Expected an ID for table \${tableName}\${suffix}.\`);
  }
}

function tableNameForId(id: string): string {
  const parsed = parseFlarexId(id);
  if (parsed === null) throw new Error(\`Invalid document ID: \${id}\`);
  const tableName = tableNamesById.get(parsed.tableId);
  if (tableName === undefined) throw new Error(\`Unknown table id \${parsed.tableId} in document ID: \${id}\`);
  return tableName;
}

function withoutSystemFields(value: object): object {
  const { _id: _ignoredId, _creationTime: _ignoredCreationTime, ...document } =
    value as Record<string, unknown>;
  return document;
}

function fieldValue(value: Record<string, unknown>, field: string): unknown {
  let cursor: unknown = value;
  for (const segment of field.split(".")) {
    if (typeof cursor !== "object" || cursor === null || Array.isArray(cursor)) return undefined;
    cursor = (cursor as Record<string, unknown>)[segment];
  }
  return cursor;
}

function matchesExpression(left: unknown, op: string, right: unknown): boolean {
  if (op === "eq") return left === right;
  if (
    (typeof left !== "string" && typeof left !== "number") ||
    (typeof right !== "string" && typeof right !== "number")
  ) {
    return false;
  }
  if (op === "gt") return (left as any) > right;
  if (op === "gte") return (left as any) >= right;
  if (op === "lt") return (left as any) < right;
  if (op === "lte") return (left as any) <= right;
  return false;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/sync") {
      const session = request.headers.get("x-flarex-session") ?? crypto.randomUUID();
      return env.CONNECTIONS.getByName(session).fetch(request);
    }
    if (url.pathname === "/invoke" && request.method === "POST") {
      const body = await request.json<{ path: string; args: unknown; partitionKey?: string }>();
      const partitionKey = request.headers.get("x-flarex-partition") ?? body.partitionKey;
      if (!partitionKey) {
        return Response.json(
          { error: "A partitionKey or x-flarex-partition header is required." },
          { status: 400 },
        );
      }
      return env.PARTITIONS.getByName(partitionKey).fetch("https://flarex.internal/invoke", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ path: body.path, args: body.args }),
      });
    }
    if (url.pathname === "/health") {
      return Response.json({ service: "flarex", status: "ok" });
    }
    return Response.json({ error: "Not implemented." }, { status: 501 });
  },
} satisfies ExportedHandler<Env>;
`;
}

export async function generateFlarex(options: FlarexGenerateOptions): Promise<void> {
  const appDir = path.resolve(options.root, options.appDir ?? "flarex");
  const generatedDir = path.resolve(appDir, options.generatedDir ?? "_generated");
  const functions = await discoverFunctions(path.join(appDir, "functions"));
  await mkdir(generatedDir, { recursive: true });

  await writeFile(
    path.join(generatedDir, "server.ts"),
    serverSource(),
  );
  await writeFile(path.join(generatedDir, "dataModel.ts"), dataModelSource());
  await writeFile(
    path.join(generatedDir, "api.ts"),
    typedApi(functions),
  );
  await writeFile(path.join(generatedDir, "functionMetadata.ts"), functionMetadataSource(functions));
  await writeFile(path.join(generatedDir, "worker.ts"), workerSource(functions));

  const wrangler = {
    $schema: "node_modules/wrangler/config-schema.json",
    name: options.workerName ?? "flarex-example",
    main: "flarex/_generated/worker.ts",
    compatibility_date: "2026-06-14",
    durable_objects: {
      bindings: [
        { name: "CONNECTIONS", class_name: "ConnectionDO" },
        { name: "PARTITIONS", class_name: "PartitionDO" },
      ],
    },
    migrations: [{ tag: "v1", new_sqlite_classes: ["ConnectionDO", "PartitionDO"] }],
  };
  await writeFile(
    path.join(options.root, "wrangler.generated.jsonc"),
    `${JSON.stringify(wrangler, null, 2)}\n`,
  );
}
