import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  listFunctionModules,
  type AnalyzedFunction,
  type AnalyzedModule,
  type AnalyzedSchema,
  type DeploymentAnalysis,
  type FunctionModule,
} from "./analyze.ts";
import { LocalMiniflareExecutionArtifactAdapter } from "./executionArtifact.ts";
import {
  bundleSourcePackage,
  type SourcePackage,
} from "./sourcePackage.ts";

export type FlarexGenerateOptions = {
  root: string;
  appDir?: string;
  generatedDir?: string;
};

export type FlarexGenerationContext = {
  options: FlarexGenerateOptions;
  appDir: string;
  generatedDir: string;
  functionsDir: string;
  functionModules: FunctionModule[];
};

function typedApi(modules: string[], metadataByPath: Record<string, unknown> = {}): string {
  const imports = modules
    .map(
      (moduleName, index) =>
        `import type * as module${index} from "../functions/${moduleName}";`,
    )
    .join("\n");
  const moduleTypes = modules
    .map((moduleName, index) => `  ${JSON.stringify(moduleName)}: typeof module${index};`)
    .join("\n");

  return `// Generated by flarex-dev. Do not edit.
import { createApi, type ApiFromModules } from "flarex/server";
${imports}

export const api = createApi(${JSON.stringify(metadataByPath, null, 2)}) as unknown as ApiFromModules<{
${moduleTypes}
}>;
`;
}

function dataModelSource(): string {
  return `// Generated by flarex-dev. Do not edit.
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
} from "flarex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type Doc<TableName extends TableNamesInDataModel<DataModel>> =
  DocumentByName<DataModel, TableName>;
export type TableNames = TableNamesInDataModel<DataModel>;
`;
}

function serverSource(schema?: AnalyzedSchema): string {
  const modelSource = schema === undefined
    ? dynamicPartitionModelSource()
    : concretePartitionModelSource(schema);
  return `// Generated by flarex-dev. Do not edit.
import {
  actionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  mutationGeneric,
  queryGeneric,
  routeFromArgs,
  workflowMutationGeneric,
  type ActionBuilder,
  type ActionCtx as GenericActionCtx,
  type MutationBuilder,
  type MutationCtx as GenericMutationCtx,
  type QueryBuilder,
  type QueryCtx as GenericQueryCtx,
} from "flarex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as unknown as QueryBuilder<DataModel, "public">;
export const internalQuery =
  internalQueryGeneric as unknown as QueryBuilder<DataModel, "internal">;
export const mutation = mutationGeneric as unknown as MutationBuilder<DataModel, "public">;
export const internalMutation =
  internalMutationGeneric as unknown as MutationBuilder<DataModel, "internal">;
export const workflowMutation: MutationBuilder<
  DataModel,
  "public",
  "workflowMutation"
> = workflowMutationGeneric as unknown as MutationBuilder<
  DataModel,
  "public",
  "workflowMutation"
>;
export const action = actionGeneric as unknown as ActionBuilder<DataModel, "public">;
export { routeFromArgs };

${modelSource}

export type { DataModel } from "./dataModel";
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;
`;
}

function functionMetadataSource(modules: AnalyzedModule[]): string {
  const metadata = modules.flatMap(module =>
    module.functions.map(fn => ({
      path: functionPath(fn),
      kind: fn.kind,
      visibility: fn.visibility,
      args: fn.args,
      returns: fn.returns,
      route: fn.route ?? null,
      partition: fn.partition ?? null,
      ...(fn.position === undefined ? {} : { position: fn.position }),
    })),
  );
  return `// Generated by flarex-dev. Do not edit.
import type { ValidatorJSON } from "flarex/values";

export type FunctionMetadata = {
  path: string;
  kind: "query" | "mutation" | "workflowMutation" | "action";
  visibility: "public" | "internal";
  args: ValidatorJSON;
  returns: ValidatorJSON | null;
  route: { type: "args"; field: string } | null;
  partition: {
    type: "partition";
    table: string;
    selector: string;
    partitionField: string;
    argField: string;
  } | null;
  position?: {
    path: string;
    startLine: number;
    startColumn: number;
  };
};

export const functionMetadata: FunctionMetadata[] = ${JSON.stringify(metadata, null, 2)};

export default functionMetadata;
`;
}

function dynamicPartitionModelSource(): string {
  return `const partitionFieldForSelector = (selector: string) => {
  if (selector === "byId") return "_id";
  if (!selector.startsWith("by") || selector.length <= 2) return "partition";
  const suffix = selector.slice(2);
  return \`\${suffix[0].toLowerCase()}\${suffix.slice(1)}\`;
};

const dynamicPartitionTable = (table: string) => new Proxy({}, {
  get(_target, property) {
    if (typeof property !== "string") return undefined;
    return (argField: string) => ({
      type: "partition",
      table,
      selector: property,
      partitionField: partitionFieldForSelector(property),
      argField,
    } as const);
  },
}) as Record<string, (argField: string) => {
  type: "partition";
  table: string;
  selector: string;
  partitionField: string;
  argField: string;
}>;

export const model = new Proxy({}, {
  get(_target, property) {
    if (typeof property !== "string") return undefined;
    return dynamicPartitionTable(property);
  },
}) as Record<string, ReturnType<typeof dynamicPartitionTable>>;`;
}

function concretePartitionModelSource(schema: AnalyzedSchema): string {
  const entries = schema.tables
    .flatMap(table => {
      if (table.placement.kind !== "partitionBy") return [];
      const selector = selectorNameForPartitionField(table.placement.field);
      return [`  ${propertyKey(table.name)}: {
    ${propertyKey(selector)}: (argField: string) => ({
      type: "partition",
      table: ${JSON.stringify(table.name)},
      selector: ${JSON.stringify(selector)},
      partitionField: ${JSON.stringify(table.placement.field)},
      argField,
    } as const),
  },`];
    });
  return `export const model = {
${entries.join("\n")}
} as const;`;
}

function selectorNameForPartitionField(field: string): string {
  if (field === "_id") return "byId";
  const suffix = field
    .split(/[^A-Za-z0-9]+/)
    .filter(part => part.length > 0)
    .map(capitalize)
    .join("");
  return suffix.length === 0 ? "byPartition" : `by${suffix}`;
}

function capitalize(value: string): string {
  return value.length === 0 ? value : `${value[0]!.toUpperCase()}${value.slice(1)}`;
}

function propertyKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function functionRegistrySource(modules: AnalyzedModule[]): string {
  const activeModules = modules.filter(module => module.functions.length > 0);
  const imports = activeModules
    .map(
      (module, index) => `import * as module${index} from "../functions/${module.moduleName}";`,
    )
    .join("\n");
  const registry = activeModules
    .flatMap((module, moduleIndex) =>
      module.functions.map(
        fn =>
          `  ${JSON.stringify(functionPath(fn))}: module${moduleIndex}.${fn.exportName},`,
      ),
    )
    .join("\n");
  return `// Generated by flarex-dev. Do not edit.
import type { RegisteredFunction } from "flarex/server";
${imports}

export const functions: Record<string, RegisteredFunction> = {
${registry}
};
`;
}

function deploymentSchemaSource(schema: AnalyzedSchema): string {
  return `// Generated by flarex-dev. Do not edit.
import type { ValidatorJSON } from "flarex/values";

type DeploymentSchema = {
  version: number;
  tables: Array<{
    tableId: number;
    name: string;
    state?: "active" | "hidden" | "deleted";
    validator: ValidatorJSON;
    placement:
      | { kind: "partitionBy"; field: string }
      | { kind: "colocateWith"; table: string; field: string }
      | { kind: "global" };
  }>;
  indexes: Array<{
    indexId: number;
    tableId: number;
    name: string;
    fields: string[];
    state?: "enabled" | "staged" | "disabled";
  }>;
};

export const deploymentSchema: DeploymentSchema = ${JSON.stringify(schema, null, 2)};

export default deploymentSchema;
`;
}

function workerSource(): string {
  return `// Generated by flarex-dev. Do not edit.
import { DurableObject } from "cloudflare:workers";
import {
  createQueryInitializer,
  parseFlarexId,
  validateValue,
  type DatabaseQueryRequest,
  type DatabaseQueryResult,
  type DatabaseWriter,
} from "flarex/server";
import { deploymentSchema } from "./deploymentSchema";
import { functionMetadata } from "./functionMetadata";
import { functions } from "./functionRegistry";

const functionMetadataByPath = new Map(
  functionMetadata.map(metadata => [metadata.path, metadata] as const),
);

const tableMetadata = Object.fromEntries(
  deploymentSchema.tables
    .filter(table => table.state !== "deleted")
    .map(table => [table.name, { tableId: table.tableId, name: table.name }]),
) as Record<string, { tableId: number; name: string }>;

const tableNamesById = new Map(
  Object.values(tableMetadata).map(table => [table.tableId, table.name] as const),
);

export interface Env {
  CONNECTIONS: DurableObjectNamespace<ConnectionDO>;
  FLAREX_BACKEND: Fetcher;
  FLAREX_DEPLOYMENT_ID?: string;
  FLAREX_INTERNAL_TOKEN?: string;
}

export class ConnectionDO extends DurableObject<Env> {
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade") !== "websocket") {
      return Response.json({ service: "flarex-connection", status: "ok" });
    }
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair) as [WebSocket, WebSocket];
    this.ctx.acceptWebSocket(server);
    server.send(JSON.stringify({ type: "Connected", protocol: "flarex-v0" }));
    return new Response(null, { status: 101, webSocket: client });
  }
}

function validateFunctionReturn(
  validator: (typeof functionMetadata)[number]["returns"],
  value: unknown,
): void {
  if (validator === null) return;
  validateValue(validator, value, "$return", { validateId: validateTableNameId });
}

function validateTableNameId(tableName: string, value: string, path: string): void {
  const expected = tableMetadata[tableName];
  if (!expected) {
    throw new Error(\`\${path}: Unknown table \${tableName} for ID validator.\`);
  }
  const parsed = parseFlarexId(value);
  if (parsed === null) {
    throw new Error(\`\${path}: Expected an ID for table \${tableName}.\`);
  }
  if (parsed.tableId !== expected.tableId) {
    const actualTableName = tableNamesById.get(parsed.tableId);
    const suffix = actualTableName === undefined ? "" : \`, got an ID for table \${actualTableName}\`;
    throw new Error(\`\${path}: Expected an ID for table \${tableName}\${suffix}.\`);
  }
}

type InvokeBody = {
  path: string;
  args: unknown;
  partitionKey?: string;
  deploymentId?: string;
  idempotencyKey?: string;
};

type ExecutionStartResponse = {
  sessionId: string;
  kind: "query" | "mutation";
};

async function invokeWithBackend(body: InvokeBody, env: Env, request: Request): Promise<unknown> {
  const fn = functions[body.path];
  if (!fn) throw new Error(\`Unknown Flarex function: \${body.path}\`);
  const metadata = functionMetadataByPath.get(body.path);
  if (!metadata) throw new Error(\`Missing analyzed metadata for Flarex function: \${body.path}\`);
  if (metadata.kind !== "query" && metadata.kind !== "mutation") {
    throw new Error(\`\${metadata.kind} execution is not implemented by /invoke\`);
  }
  validateValue(metadata.args, body.args, "$args", { validateId: validateTableNameId });

  const deploymentId =
    request.headers.get("x-flarex-deployment") ?? body.deploymentId ?? env.FLAREX_DEPLOYMENT_ID;
  if (!deploymentId) throw new Error("A deploymentId or x-flarex-deployment header is required.");
  const partitionKey = request.headers.get("x-flarex-partition") ?? body.partitionKey;
  if (!partitionKey) throw new Error("A partitionKey or x-flarex-partition header is required.");

  const start = await postBackend<ExecutionStartResponse>(
    env.FLAREX_BACKEND,
    \`/deployments/\${deploymentId}/executions/start\`,
    {
      path: body.path,
      args: body.args,
      kind: metadata.kind,
      partitionKey,
      ...(body.idempotencyKey === undefined ? {} : { idempotencyKey: body.idempotencyKey }),
    },
  );
  try {
    const db = databaseForSession(env.FLAREX_BACKEND, deploymentId, start.sessionId, start.kind);
    const value = await fn._handler({ db } as never, body.args as never);
    validateFunctionReturn(metadata.returns, value);
    return await postBackend(env.FLAREX_BACKEND, \`/deployments/\${deploymentId}/executions/\${start.sessionId}/finish\`, {
      value,
    });
  } catch (error) {
    await postBackend(env.FLAREX_BACKEND, \`/deployments/\${deploymentId}/executions/\${start.sessionId}/abort\`, {}).catch(
      () => undefined,
    );
    throw error;
  }
}

function databaseForSession(
  backend: Fetcher,
  deploymentId: string,
  sessionId: string,
  kind: "query" | "mutation",
): DatabaseWriter {
  const syscall = (body: unknown) =>
    postBackend<unknown>(backend, \`/deployments/\${deploymentId}/executions/\${sessionId}/syscall\`, body);
  const query = (request: DatabaseQueryRequest) =>
    syscall({ op: "query", request }) as Promise<DatabaseQueryResult>;
  return {
    get: id => syscall({ op: "get", id }) as never,
    query: table => createQueryInitializer(table, query),
    insert: async (table, value) => {
      if (kind !== "mutation") throw new Error("Cannot insert during a query.");
      return (await syscall({ op: "insert", table, value })) as never;
    },
    patch: async (id, value) => {
      if (kind !== "mutation") throw new Error("Cannot patch during a query.");
      await syscall({ op: "patch", id, value });
    },
    delete: async id => {
      if (kind !== "mutation") throw new Error("Cannot delete during a query.");
      await syscall({ op: "delete", id });
    },
  };
}

async function postBackend<T>(backend: Fetcher, path: string, body: unknown): Promise<T> {
  const response = await backend.fetch(\`https://flarex-backend.internal\${path}\`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const value = await response.json().catch(() => null);
  if (!response.ok) {
    const message =
      typeof value === "object" && value !== null && "error" in value
        ? String((value as { error: unknown }).error)
        : \`Backend request failed with status \${response.status}\`;
    throw new Error(message);
  }
  return value as T;
}

function authorizeInternalRequest(request: Request, env: Env): Response | null {
  if (env.FLAREX_INTERNAL_TOKEN === undefined) return null;
  const expected = \`Bearer \${env.FLAREX_INTERNAL_TOKEN}\`;
  if (request.headers.get("authorization") === expected) return null;
  return Response.json({ error: "Unauthorized internal Flarex request." }, { status: 401 });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/__flarex_internal/")) {
      const unauthorized = authorizeInternalRequest(request, env);
      if (unauthorized !== null) return unauthorized;
    }
    if (url.pathname === "/sync") {
      const session = request.headers.get("x-flarex-session") ?? crypto.randomUUID();
      return env.CONNECTIONS.getByName(session).fetch(request);
    }
    if (
      (url.pathname === "/invoke" || url.pathname === "/__flarex_internal/invoke") &&
      request.method === "POST"
    ) {
      try {
        return Response.json(await invokeWithBackend(await request.json<InvokeBody>(), env, request));
      } catch (error) {
        return Response.json(
          { error: error instanceof Error ? error.message : String(error) },
          { status: 400 },
        );
      }
    }
    if (url.pathname === "/health") {
      return Response.json({ service: "flarex", status: "ok" });
    }
    if (url.pathname === "/__flarex_internal/metadata") {
      return Response.json({ schema: deploymentSchema, functions: functionMetadata });
    }
    return Response.json({ error: "Not implemented." }, { status: 501 });
  },
} satisfies ExportedHandler<Env>;
`;
}

export async function generateFlarex(options: FlarexGenerateOptions): Promise<void> {
  const context = await initialCodegen(options);
  const sourcePackage = await bundleFlarexSourcePackage(context);
  const analysis = await new LocalMiniflareExecutionArtifactAdapter().analyze(sourcePackage);
  await finalCodegen(context, analysis);
}

export async function initialCodegen(
  options: FlarexGenerateOptions,
): Promise<FlarexGenerationContext> {
  const appDir = path.resolve(options.root, options.appDir ?? "flarex");
  const generatedDir = path.resolve(appDir, options.generatedDir ?? "_generated");
  const functionsDir = path.join(appDir, "functions");
  const functionModules = await listFunctionModules(functionsDir);
  const moduleNames = functionModules.map(module => module.moduleName);
  await mkdir(generatedDir, { recursive: true });

  await writeFile(path.join(generatedDir, "dataModel.ts"), dataModelSource());
  await writeFile(path.join(generatedDir, "server.ts"), serverSource());
  await writeFile(path.join(generatedDir, "api.ts"), typedApi(moduleNames));
  return { options, appDir, generatedDir, functionsDir, functionModules };
}

export function bundleFlarexSourcePackage(
  context: FlarexGenerationContext,
): Promise<SourcePackage> {
  return bundleSourcePackage({
    appDir: context.appDir,
    functionModules: context.functionModules,
  });
}

export async function finalCodegen(
  context: FlarexGenerationContext,
  analysis: DeploymentAnalysis,
): Promise<void> {
  const { generatedDir } = context;
  const functions = analysis.functions;
  await writeFile(path.join(generatedDir, "dataModel.ts"), dataModelSource());
  await writeFile(path.join(generatedDir, "server.ts"), serverSource(analysis.schema));
  await writeFile(
    path.join(generatedDir, "api.ts"),
    typedApi(functions.map(module => module.moduleName), referenceMetadataMapSource(functions)),
  );
  await writeFile(path.join(generatedDir, "functionRegistry.ts"), functionRegistrySource(functions));
  await writeFile(path.join(generatedDir, "functionMetadata.ts"), functionMetadataSource(functions));
  await writeFile(path.join(generatedDir, "deploymentSchema.ts"), deploymentSchemaSource(analysis.schema));
  await writeFile(path.join(generatedDir, "worker.ts"), workerSource());
  await cleanupStaleGeneratedEntries(generatedDir, [
    "api.ts",
    "dataModel.ts",
    "deploymentSchema.ts",
    "functionMetadata.ts",
    "functionRegistry.ts",
    "server.ts",
    "worker.ts",
  ]);
}

function functionPath(fn: AnalyzedFunction): string {
  return fn.exportName === "default" ? fn.moduleName : `${fn.moduleName}:${fn.exportName}`;
}

function referenceMetadataMapSource(modules: AnalyzedModule[]): Record<string, unknown> {
  return Object.fromEntries(
    modules.flatMap(module =>
      module.functions.flatMap(fn => {
        if (
          (fn.route === null || fn.route === undefined) &&
          (fn.partition === null || fn.partition === undefined)
        ) {
          return [];
        }
        return [[
          functionPath(fn),
          {
            route: fn.route ?? null,
            partition: fn.partition ?? null,
          },
        ]];
      }),
    ),
  );
}

async function cleanupStaleGeneratedEntries(
  generatedDir: string,
  writtenFiles: string[],
): Promise<void> {
  const entries = await readdir(generatedDir, { withFileTypes: true });
  await Promise.all(
    entries
      .filter(entry => !writtenFiles.includes(entry.name))
      .map(entry => rm(path.join(generatedDir, entry.name), { recursive: true, force: true })),
  );
}
