import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  listFunctionModules,
  type AnalyzedFunction,
  type AnalyzedFunctionPartitionCreateRootPolicy,
  type AnalyzedFunctionPartitionPolicy,
  type AnalyzedModule,
  type AnalyzedSchema,
  type DeploymentAnalysis,
  type FunctionModule,
} from "./analyze.ts";
import { LocalMiniflareExecutionArtifactAdapter } from "./executionArtifact.ts";
import {
  bundleSourcePackage,
  type SourcePackage,
} from "./sourcePackage.ts";

export type FlarexGenerateOptions = {
  root: string;
  appDir?: string;
  generatedDir?: string;
};

export type FlarexGenerationContext = {
  options: FlarexGenerateOptions;
  appDir: string;
  generatedDir: string;
  functionsDir: string;
  functionModules: FunctionModule[];
};

function typedApi(modules: string[], metadataByPath: Record<string, unknown> = {}): string {
  const imports = modules
    .map(
      (moduleName, index) =>
        `import type * as module${index} from "../functions/${moduleName}";`,
    )
    .join("\n");
  const moduleTypes = modules
    .map((moduleName, index) => `  ${JSON.stringify(moduleName)}: typeof module${index};`)
    .join("\n");

  return `// Generated by flarex-dev. Do not edit.
import { createApi, justInternal, justPublic, type ApiFromModules } from "flarex/server";
${imports}

const fullApi = createApi(${JSON.stringify(metadataByPath, null, 2)}) as unknown as ApiFromModules<{
${moduleTypes}
}>;

export const api = justPublic(fullApi);
export const internal = justInternal(fullApi);
`;
}

function dataModelSource(): string {
  return `// Generated by flarex-dev. Do not edit.
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
} from "flarex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type Doc<TableName extends TableNamesInDataModel<DataModel>> =
  DocumentByName<DataModel, TableName>;
export type TableNames = TableNamesInDataModel<DataModel>;
`;
}

function serverSource(schema?: AnalyzedSchema): string {
  const modelSource = schema === undefined
    ? dynamicPartitionModelSource()
    : concretePartitionModelSource(schema);
  const partitionScopesSource = schema === undefined
    ? dynamicPartitionScopesSource()
    : concretePartitionScopesSource(schema);
  return `// Generated by flarex-dev. Do not edit.
import {
  actionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  mutationGeneric,
  queryGeneric,
  workflowMutationGeneric,
  type ActionBuilder,
  type ActionCtx as GenericActionCtx,
  type MutationCtxForTables as GenericMutationCtxForTables,
  type MutationBuilder,
  type MutationCtx as GenericMutationCtx,
  type PartitionScopeMap,
  type QueryBuilder,
  type QueryCtx as GenericQueryCtx,
} from "flarex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as unknown as QueryBuilder<DataModel, "public">;
export const internalQuery =
  internalQueryGeneric as unknown as QueryBuilder<DataModel, "internal">;
export const mutation =
  mutationGeneric as unknown as MutationBuilder<DataModel, "public", "mutation", PartitionScopes>;
export const internalMutation =
  internalMutationGeneric as unknown as MutationBuilder<
    DataModel,
    "internal",
    "mutation",
    PartitionScopes
  >;
export const workflowMutation: MutationBuilder<
  DataModel,
  "public",
  "workflowMutation",
  PartitionScopes
> = workflowMutationGeneric as unknown as MutationBuilder<
  DataModel,
  "public",
  "workflowMutation",
  PartitionScopes
>;
export const action = actionGeneric as unknown as ActionBuilder<DataModel, "public">;

${modelSource}

${partitionScopesSource}

export type { DataModel } from "./dataModel";
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type PartitionMutationCtx<PartitionTable extends keyof PartitionScopes & string> =
  GenericMutationCtxForTables<
    DataModel,
    Extract<PartitionScopes[PartitionTable], keyof DataModel & string>
  >;
export type ActionCtx = GenericActionCtx<DataModel>;
`;
}

function functionMetadataSource(modules: AnalyzedModule[]): string {
  const metadata = modules.flatMap(module =>
    module.functions.map(fn => ({
      path: functionPath(fn),
      kind: fn.kind,
      visibility: fn.visibility,
      args: fn.args,
      returns: fn.returns,
      partition: runnablePartition(fn),
      ...(fn.position === undefined ? {} : { position: fn.position }),
    })),
  );
  return `// Generated by flarex-dev. Do not edit.
import type { ValidatorJSON } from "flarex/values";

export type FunctionMetadata = {
  path: string;
  kind: "query" | "mutation" | "workflowMutation" | "action";
  visibility: "public" | "internal";
  args: ValidatorJSON;
  returns: ValidatorJSON | null;
  partition: {
    type: "partition";
    table: string;
    selector: string;
    partitionField: string;
    argField: string;
  } | {
    type: "partitionCreateRoot";
    table: string;
    partitionField: "_id";
  } | null;
  position?: {
    path: string;
    startLine: number;
    startColumn: number;
  };
};

export const functionMetadata: FunctionMetadata[] = ${JSON.stringify(metadata, null, 2)};

export default functionMetadata;
`;
}

function dynamicPartitionModelSource(): string {
  return `const partitionFieldForSelector = (selector: string) => {
  if (selector === "byId") return "_id";
  if (!selector.startsWith("by") || selector.length <= 2) return "partition";
  const suffix = selector.slice(2);
  return \`\${suffix[0].toLowerCase()}\${suffix.slice(1)}\`;
};

type DynamicPartitionSelector = (argField: string) => {
  type: "partition";
  table: string;
  selector: string;
  partitionField: string;
  argField: string;
};

type DynamicPartitionRoot = {
  type: "partitionRoot";
  table: string;
  partitionField: "_id";
} & Record<string, DynamicPartitionSelector>;

const dynamicPartitionTable = (table: string) => new Proxy({
  type: "partitionRoot",
  table,
  partitionField: "_id",
} as DynamicPartitionRoot, {
  get(_target, property) {
    if (typeof property !== "string") return undefined;
    if (property === "type") return "partitionRoot";
    if (property === "table") return table;
    if (property === "partitionField") return "_id";
    if (property === "toJSON") return undefined;
    return (argField: string) => ({
      type: "partition",
      table,
      selector: property,
      partitionField: partitionFieldForSelector(property),
      argField,
    } as const);
  },
}) as DynamicPartitionRoot;

export const model = new Proxy({}, {
  get(_target, property) {
    if (typeof property !== "string") return undefined;
    return dynamicPartitionTable(property);
  },
}) as Record<string, ReturnType<typeof dynamicPartitionTable>>;`;
}

function concretePartitionModelSource(schema: AnalyzedSchema): string {
  const entries = schema.tables
    .flatMap(table => {
      if (table.placement.kind !== "partitionBy") return [];
      const selector = selectorNameForPartitionField(table.placement.field);
      return [`  ${propertyKey(table.name)}: {
    type: "partitionRoot",
    table: ${JSON.stringify(table.name)},
    partitionField: ${JSON.stringify(table.placement.field)},
    ${propertyKey(selector)}: (argField: string) => ({
      type: "partition",
      table: ${JSON.stringify(table.name)},
      selector: ${JSON.stringify(selector)},
      partitionField: ${JSON.stringify(table.placement.field)},
      argField,
    } as const),
  },`];
    });
  return `export const model = {
${entries.join("\n")}
} as const;`;
}

function dynamicPartitionScopesSource(): string {
  return `export type PartitionScopes = PartitionScopeMap<DataModel>;`;
}

function concretePartitionScopesSource(schema: AnalyzedSchema): string {
  const scopes = partitionScopesForSchema(schema);
  const entries = Object.entries(scopes).map(([root, tables]) => {
    const writable = tables.map(table => JSON.stringify(table)).join(" | ");
    return `  ${propertyKey(root)}: ${writable.length === 0 ? "never" : writable};`;
  });
  return `export type PartitionScopes = {
${entries.join("\n")}
};
type _PartitionScopesCheck = PartitionScopes extends PartitionScopeMap<DataModel> ? true : never;`;
}

function partitionScopesForSchema(schema: AnalyzedSchema): Record<string, string[]> {
  const tableByName = new Map(schema.tables.map(table => [table.name, table] as const));
  const roots = schema.tables
    .filter(table => table.placement.kind === "partitionBy")
    .map(table => table.name);
  const scopes = Object.fromEntries(roots.map(root => [root, [root]])) as Record<string, string[]>;

  for (const table of schema.tables) {
    if (table.placement.kind !== "colocateWith") continue;
    const root = partitionRootForTable(table.placement.table, tableByName);
    if (root === null) continue;
    scopes[root] ??= [root];
    if (!scopes[root].includes(table.name)) scopes[root].push(table.name);
  }

  return Object.fromEntries(
    Object.entries(scopes).map(([root, tables]) => [root, tables.sort()]),
  );
}

function partitionRootForTable(
  tableName: string,
  tableByName: Map<string, AnalyzedSchema["tables"][number]>,
  seen = new Set<string>(),
): string | null {
  if (seen.has(tableName)) return null;
  seen.add(tableName);
  const table = tableByName.get(tableName);
  if (table === undefined) return null;
  if (table.placement.kind === "partitionBy") return table.name;
  if (table.placement.kind === "colocateWith") {
    return partitionRootForTable(table.placement.table, tableByName, seen);
  }
  return null;
}

function selectorNameForPartitionField(field: string): string {
  if (field === "_id") return "byId";
  const suffix = field
    .split(/[^A-Za-z0-9]+/)
    .filter(part => part.length > 0)
    .map(capitalize)
    .join("");
  return suffix.length === 0 ? "byPartition" : `by${suffix}`;
}

function capitalize(value: string): string {
  return value.length === 0 ? value : `${value[0]!.toUpperCase()}${value.slice(1)}`;
}

function propertyKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function functionRegistrySource(modules: AnalyzedModule[]): string {
  const activeModules = modules.filter(module => module.functions.length > 0);
  const imports = activeModules
    .map(
      (module, index) => `import * as module${index} from "../functions/${module.moduleName}";`,
    )
    .join("\n");
  const registry = activeModules
    .flatMap((module, moduleIndex) =>
      module.functions.map(
        fn =>
          `  ${JSON.stringify(functionPath(fn))}: module${moduleIndex}.${fn.exportName},`,
      ),
    )
    .join("\n");
  return `// Generated by flarex-dev. Do not edit.
import type { RegisteredFunction } from "flarex/server";
${imports}

export const functions: Record<string, RegisteredFunction> = {
${registry}
};
`;
}

function deploymentSchemaSource(schema: AnalyzedSchema): string {
  return `// Generated by flarex-dev. Do not edit.
import type { ValidatorJSON } from "flarex/values";

type DeploymentSchema = {
  version: number;
  tables: Array<{
    tableId: number;
    name: string;
    state?: "active" | "hidden" | "deleted";
    validator: ValidatorJSON;
    placement:
      | { kind: "partitionBy"; field: string }
      | { kind: "colocateWith"; table: string; field: string }
      | { kind: "global" };
  }>;
  indexes: Array<{
    indexId: number;
    tableId: number;
    name: string;
    fields: string[];
    state?: "enabled" | "staged" | "disabled";
  }>;
};

export const deploymentSchema: DeploymentSchema = ${JSON.stringify(schema, null, 2)};

export default deploymentSchema;
`;
}

function workerSource(): string {
  return `// Generated by flarex-dev. Do not edit.
import { DurableObject } from "cloudflare:workers";
import {
  createQueryInitializer,
  parseFlarexId,
  validateValue,
  type DatabaseQueryRequest,
  type DatabaseQueryResult,
  type DatabaseWriter,
} from "flarex/server";
import { deploymentSchema } from "./deploymentSchema";
import { functionMetadata } from "./functionMetadata";
import { functions } from "./functionRegistry";

const functionMetadataByPath = new Map(
  functionMetadata.map(metadata => [metadata.path, metadata] as const),
);

const tableMetadata = Object.fromEntries(
  deploymentSchema.tables
    .filter(table => table.state !== "deleted")
    .map(table => [table.name, { tableId: table.tableId, name: table.name }]),
) as Record<string, { tableId: number; name: string }>;

const tableNamesById = new Map(
  Object.values(tableMetadata).map(table => [table.tableId, table.name] as const),
);

export interface Env {
  CONNECTIONS: DurableObjectNamespace<ConnectionDO>;
  FLAREX_BACKEND: Fetcher;
  FLAREX_DEPLOYMENT_ID?: string;
  FLAREX_PROJECT_ID?: string;
  FLAREX_EXECUTOR_TRANSPORT?: string;
  FLAREX_EXECUTOR_TOKEN?: string;
  FLAREX_INVOKE_MAX_ATTEMPTS?: string;
  FLAREX_INTERNAL_TOKEN?: string;
}

export class ConnectionDO extends DurableObject<Env> {
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade") !== "websocket") {
      return Response.json({ service: "flarex-connection", status: "ok" });
    }
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair) as [WebSocket, WebSocket];
    this.ctx.acceptWebSocket(server);
    server.send(JSON.stringify({ type: "Connected", protocol: "flarex-v0" }));
    return new Response(null, { status: 101, webSocket: client });
  }
}

function validateFunctionReturn(
  validator: (typeof functionMetadata)[number]["returns"],
  value: unknown,
): void {
  if (validator === null) return;
  validateValue(validator, value, "$return", { validateId: validateTableNameId });
}

function validateTableNameId(tableName: string, value: string, path: string): void {
  const expected = tableMetadata[tableName];
  if (!expected) {
    throw new Error(\`\${path}: Unknown table \${tableName} for ID validator.\`);
  }
  const parsed = parseFlarexId(value);
  if (parsed === null) {
    throw new Error(\`\${path}: Expected an ID for table \${tableName}.\`);
  }
  if (parsed.tableId !== expected.tableId) {
    const actualTableName = tableNamesById.get(parsed.tableId);
    const suffix = actualTableName === undefined ? "" : \`, got an ID for table \${actualTableName}\`;
    throw new Error(\`\${path}: Expected an ID for table \${tableName}\${suffix}.\`);
  }
}

type InvokeBody = {
  path: string;
  args: unknown;
  partitionKey?: string;
  deploymentId?: string;
  projectId?: string;
  idempotencyKey?: string;
};

type ExecutorTransport = "legacy" | "postgres";

type ExecutionStartResponse = {
  sessionId: string;
  kind?: "query" | "mutation";
  function?: { kind: "query" | "mutation" };
};

const DEFAULT_INVOKE_MAX_ATTEMPTS = 8;
const RETRYABLE_INVOKE_ERROR_CODES = new Set([
  "InvokeSessionOccConflictError",
  "InvokeSessionTableOccConflictError",
  "InvokeSessionIndexOccConflictError",
  "40001",
]);

class BackendRequestError extends Error {
  readonly status: number;
  readonly code: string | undefined;

  constructor(status: number, code: string | undefined, message: string) {
    super(message);
    this.name = "BackendRequestError";
    this.status = status;
    this.code = code;
  }
}

class InvokeRetryExhaustedError extends Error {
  readonly attempts: number;

  constructor(attempts: number, cause: unknown) {
    super("Flarex invoke retry exhausted after " + attempts + " attempts: " + invokeErrorMessage(cause));
    this.name = "InvokeRetryExhaustedError";
    this.attempts = attempts;
  }
}

async function invokeWithBackend(body: InvokeBody, env: Env, request: Request): Promise<unknown> {
  const fn = functions[body.path];
  if (!fn) throw new Error(\`Unknown Flarex function: \${body.path}\`);
  const metadata = functionMetadataByPath.get(body.path);
  if (!metadata) throw new Error(\`Missing analyzed metadata for Flarex function: \${body.path}\`);
  if (metadata.kind !== "query" && metadata.kind !== "mutation") {
    throw new Error(\`\${metadata.kind} execution is not implemented by /invoke\`);
  }
  validateValue(metadata.args, body.args, "$args", { validateId: validateTableNameId });

  const deploymentId =
    request.headers.get("x-flarex-deployment") ?? body.deploymentId ?? env.FLAREX_DEPLOYMENT_ID;
  if (!deploymentId) throw new Error("A deploymentId or x-flarex-deployment header is required.");
  const transport = executorTransport(request, env);
  const projectId = projectIdForTransport(transport, body, env, request);
  const partitionKey = request.headers.get("x-flarex-partition") ?? body.partitionKey;
  const maxAttempts = invokeMaxAttempts(transport, metadata.kind, env);
  const expectedVisibility =
    new URL(request.url).pathname === "/__flarex_internal/invoke"
      ? metadata.visibility
      : "public";

  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    const start = await startExecution(env.FLAREX_BACKEND, {
      transport,
      deploymentId,
      ...(projectId === undefined ? {} : { projectId }),
      ...(env.FLAREX_EXECUTOR_TOKEN === undefined ? {} : { executorToken: env.FLAREX_EXECUTOR_TOKEN }),
      path: body.path,
      args: body.args,
      kind: metadata.kind,
      visibility: expectedVisibility,
      ...(partitionKey === undefined ? {} : { partitionKey }),
      ...(body.idempotencyKey === undefined ? {} : { idempotencyKey: body.idempotencyKey }),
    });
    const startedKind = executionKind(start);
    try {
      const db = databaseForSession(
        env.FLAREX_BACKEND,
        deploymentId,
        start.sessionId,
        startedKind,
        transport,
        projectId,
        env.FLAREX_EXECUTOR_TOKEN,
      );
      const value = normalizeReturnValue(await fn._handler({ db } as never, body.args as never));
      validateFunctionReturn(metadata.returns, value);
      return await finishExecution(env.FLAREX_BACKEND, {
        transport,
        deploymentId,
        ...(projectId === undefined ? {} : { projectId }),
        ...(env.FLAREX_EXECUTOR_TOKEN === undefined ? {} : { executorToken: env.FLAREX_EXECUTOR_TOKEN }),
        sessionId: start.sessionId,
        value,
      });
    } catch (error) {
      await abortExecution(env.FLAREX_BACKEND, {
        transport,
        deploymentId,
        ...(projectId === undefined ? {} : { projectId }),
        ...(env.FLAREX_EXECUTOR_TOKEN === undefined ? {} : { executorToken: env.FLAREX_EXECUTOR_TOKEN }),
        sessionId: start.sessionId,
      }).catch(() => undefined);
      if (isRetryableInvokeAttempt(transport, startedKind, error)) {
        if (attempt < maxAttempts) {
          continue;
        }
        throw new InvokeRetryExhaustedError(maxAttempts, error);
      }
      throw error;
    }
  }

  throw new Error("Flarex invoke retry policy did not run any attempts.");
}

function executorTransport(request: Request, env: Env): ExecutorTransport {
  const transport =
    request.headers.get("x-flarex-executor-transport") ?? env.FLAREX_EXECUTOR_TRANSPORT ?? "legacy";
  if (transport === "legacy" || transport === "postgres") return transport;
  throw new Error(\`Unsupported Flarex executor transport: \${transport}\`);
}

function projectIdForTransport(
  transport: ExecutorTransport,
  body: InvokeBody,
  env: Env,
  request: Request,
): string | undefined {
  if (transport === "legacy") return undefined;
  const projectId = request.headers.get("x-flarex-project") ?? body.projectId ?? env.FLAREX_PROJECT_ID;
  if (!projectId) {
    throw new Error("A projectId, x-flarex-project header, or FLAREX_PROJECT_ID binding is required for postgres executor transport.");
  }
  return projectId;
}

async function startExecution(
  backend: Fetcher,
  input: {
    transport: ExecutorTransport;
    deploymentId: string;
    projectId?: string;
    executorToken?: string;
    path: string;
    args: unknown;
    kind: "query" | "mutation";
    visibility: (typeof functionMetadata)[number]["visibility"];
    partitionKey?: string;
    idempotencyKey?: string;
  },
): Promise<ExecutionStartResponse> {
  if (input.transport === "postgres") {
    return await postBackend<ExecutionStartResponse>(backend, "/invoke/start", {
      deploymentId: input.deploymentId,
      projectId: input.projectId,
      path: input.path,
      args: input.args,
      kind: input.kind,
      visibility: input.visibility,
      ...(input.partitionKey === undefined ? {} : { partitionKey: input.partitionKey }),
      ...(input.idempotencyKey === undefined ? {} : { idempotencyKey: input.idempotencyKey }),
    }, executorHeaders(input.executorToken));
  }
  return await postBackend<ExecutionStartResponse>(
    backend,
    \`/deployments/\${input.deploymentId}/executions/start\`,
    {
      path: input.path,
      args: input.args,
      kind: input.kind,
      ...(input.partitionKey === undefined ? {} : { partitionKey: input.partitionKey }),
      ...(input.idempotencyKey === undefined ? {} : { idempotencyKey: input.idempotencyKey }),
    },
  );
}

function executionKind(start: ExecutionStartResponse): "query" | "mutation" {
  const kind = start.kind ?? start.function?.kind;
  if (kind === "query" || kind === "mutation") return kind;
  throw new Error("Backend execution start response did not include a query or mutation kind.");
}

function invokeMaxAttempts(
  transport: ExecutorTransport,
  kind: "query" | "mutation",
  env: Env,
): number {
  if (transport !== "postgres" || kind !== "mutation") return 1;
  if (env.FLAREX_INVOKE_MAX_ATTEMPTS === undefined) {
    return DEFAULT_INVOKE_MAX_ATTEMPTS;
  }
  const value = Number(env.FLAREX_INVOKE_MAX_ATTEMPTS);
  if (!Number.isFinite(value) || !Number.isInteger(value) || value <= 0) {
    throw new Error("FLAREX_INVOKE_MAX_ATTEMPTS must be a positive integer.");
  }
  return value;
}

function isRetryableInvokeAttempt(
  transport: ExecutorTransport,
  kind: "query" | "mutation",
  error: unknown,
): boolean {
  return (
    transport === "postgres" &&
    kind === "mutation" &&
    isRetryableInvokeError(error)
  );
}

function isRetryableInvokeError(error: unknown): boolean {
  if (error instanceof BackendRequestError) {
    return error.status === 409 && error.code !== undefined && RETRYABLE_INVOKE_ERROR_CODES.has(error.code);
  }
  if (!isRecord(error)) return false;
  const name = error.name;
  const code = error.code;
  return (
    (typeof name === "string" && RETRYABLE_INVOKE_ERROR_CODES.has(name)) ||
    (typeof code === "string" && RETRYABLE_INVOKE_ERROR_CODES.has(code))
  );
}

async function finishExecution(
  backend: Fetcher,
  input: {
    transport: ExecutorTransport;
    deploymentId: string;
    projectId?: string;
    executorToken?: string;
    sessionId: string;
    value: unknown;
  },
): Promise<unknown> {
  if (input.transport === "postgres") {
    return await postBackend(backend, "/invoke/finish", {
      deploymentId: input.deploymentId,
      projectId: input.projectId,
      sessionId: input.sessionId,
      value: input.value,
    }, executorHeaders(input.executorToken));
  }
  return await postBackend(
    backend,
    \`/deployments/\${input.deploymentId}/executions/\${input.sessionId}/finish\`,
    { value: input.value },
  );
}

async function abortExecution(
  backend: Fetcher,
  input: {
    transport: ExecutorTransport;
    deploymentId: string;
    projectId?: string;
    executorToken?: string;
    sessionId: string;
  },
): Promise<void> {
  if (input.transport === "postgres") {
    await postBackend(
      backend,
      "/invoke/abort",
      {
        deploymentId: input.deploymentId,
        projectId: input.projectId,
        sessionId: input.sessionId,
      },
      executorHeaders(input.executorToken),
    ).catch(() => undefined);
    return;
  }
  await postBackend(
    backend,
    \`/deployments/\${input.deploymentId}/executions/\${input.sessionId}/abort\`,
    {},
  ).catch(() => undefined);
}

function databaseForSession(
  backend: Fetcher,
  deploymentId: string,
  sessionId: string,
  kind: "query" | "mutation",
  transport: ExecutorTransport,
  projectId?: string,
  executorToken?: string,
): DatabaseWriter {
  const syscall = async (body: Record<string, unknown>) => {
    if (transport === "postgres") {
      const response = await postBackend<{ value: unknown }>(backend, "/invoke/syscall", {
        deploymentId,
        projectId,
        sessionId,
        ...body,
      }, executorHeaders(executorToken));
      return response.value;
    }
    return await postBackend<unknown>(
      backend,
      \`/deployments/\${deploymentId}/executions/\${sessionId}/syscall\`,
      body,
    );
  };
  const query = (request: DatabaseQueryRequest) =>
    syscall({ op: "query", request }) as Promise<DatabaseQueryResult>;
  return {
    get: id => syscall({ op: "get", id }) as never,
    query: table => createQueryInitializer(table, query),
    insert: async (table, value) => {
      if (kind !== "mutation") throw new Error("Cannot insert during a query.");
      return (await syscall({ op: "insert", table, value })) as never;
    },
    patch: async (id, value) => {
      if (kind !== "mutation") throw new Error("Cannot patch during a query.");
      await syscall({ op: "patch", id, value });
    },
    replace: async (id, value) => {
      if (kind !== "mutation") throw new Error("Cannot replace during a query.");
      await syscall({ op: "replace", id, value });
    },
    delete: async id => {
      if (kind !== "mutation") throw new Error("Cannot delete during a query.");
      await syscall({ op: "delete", id });
    },
  };
}

function executorHeaders(executorToken: string | undefined): Record<string, string> {
  return executorToken === undefined ? {} : { authorization: \`Bearer \${executorToken}\` };
}

function normalizeReturnValue(value: unknown): unknown {
  return value === undefined ? null : value;
}

async function postBackend<T>(
  backend: Fetcher,
  path: string,
  body: unknown,
  headers: Record<string, string> = {},
): Promise<T> {
  const response = await backend.fetch(\`https://flarex-backend.internal\${path}\`, {
    method: "POST",
    headers: { "content-type": "application/json", ...headers },
    body: JSON.stringify(body),
  });
  const value = await response.json().catch(() => null);
  if (!response.ok) {
    const code = backendErrorCode(value);
    const message =
      backendErrorMessage(value) ??
      code ??
      \`Backend request failed with status \${response.status}\`;
    throw new BackendRequestError(response.status, code, message);
  }
  return value as T;
}

function backendErrorCode(value: unknown): string | undefined {
  if (isRecord(value) && typeof value.error === "string") {
    return value.error;
  }
  return undefined;
}

function backendErrorMessage(value: unknown): string | undefined {
  if (isRecord(value) && typeof value.message === "string") {
    return value.message;
  }
  return undefined;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function invokeErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function authorizeInternalRequest(request: Request, env: Env): Response | null {
  if (env.FLAREX_INTERNAL_TOKEN === undefined) return null;
  const expected = \`Bearer \${env.FLAREX_INTERNAL_TOKEN}\`;
  if (request.headers.get("authorization") === expected) return null;
  return Response.json({ error: "Unauthorized internal Flarex request." }, { status: 401 });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/__flarex_internal/")) {
      const unauthorized = authorizeInternalRequest(request, env);
      if (unauthorized !== null) return unauthorized;
    }
    if (url.pathname === "/sync") {
      const session = request.headers.get("x-flarex-session") ?? crypto.randomUUID();
      return env.CONNECTIONS.getByName(session).fetch(request);
    }
    if (
      (url.pathname === "/invoke" || url.pathname === "/__flarex_internal/invoke") &&
      request.method === "POST"
    ) {
      try {
        return Response.json(await invokeWithBackend(await request.json<InvokeBody>(), env, request));
      } catch (error) {
        return Response.json(
          { error: error instanceof Error ? error.message : String(error) },
          { status: 400 },
        );
      }
    }
    if (url.pathname === "/health") {
      return Response.json({ service: "flarex", status: "ok" });
    }
    if (url.pathname === "/__flarex_internal/metadata") {
      return Response.json({ schema: deploymentSchema, functions: functionMetadata });
    }
    return Response.json({ error: "Not implemented." }, { status: 501 });
  },
} satisfies ExportedHandler<Env>;
`;
}

export async function generateFlarex(options: FlarexGenerateOptions): Promise<void> {
  const context = await initialCodegen(options);
  const sourcePackage = await bundleFlarexSourcePackage(context);
  const analysis = await new LocalMiniflareExecutionArtifactAdapter().analyze(sourcePackage);
  await finalCodegen(context, analysis);
}

export async function initialCodegen(
  options: FlarexGenerateOptions,
): Promise<FlarexGenerationContext> {
  const appDir = path.resolve(options.root, options.appDir ?? "flarex");
  const generatedDir = path.resolve(appDir, options.generatedDir ?? "_generated");
  const functionsDir = path.join(appDir, "functions");
  const functionModules = await listFunctionModules(functionsDir);
  const moduleNames = functionModules.map(module => module.moduleName);
  await mkdir(generatedDir, { recursive: true });

  await writeFile(path.join(generatedDir, "dataModel.ts"), dataModelSource());
  await writeFile(path.join(generatedDir, "server.ts"), serverSource());
  await writeFile(path.join(generatedDir, "api.ts"), typedApi(moduleNames));
  return { options, appDir, generatedDir, functionsDir, functionModules };
}

export function bundleFlarexSourcePackage(
  context: FlarexGenerationContext,
): Promise<SourcePackage> {
  return bundleSourcePackage({
    appDir: context.appDir,
    functionModules: context.functionModules,
  });
}

export async function finalCodegen(
  context: FlarexGenerationContext,
  analysis: DeploymentAnalysis,
): Promise<void> {
  const { generatedDir } = context;
  const functions = analysis.functions;
  await writeFile(path.join(generatedDir, "dataModel.ts"), dataModelSource());
  await writeFile(path.join(generatedDir, "server.ts"), serverSource(analysis.schema));
  await writeFile(
    path.join(generatedDir, "api.ts"),
    typedApi(functions.map(module => module.moduleName), referenceMetadataMapSource(functions)),
  );
  await writeFile(path.join(generatedDir, "functionRegistry.ts"), functionRegistrySource(functions));
  await writeFile(path.join(generatedDir, "functionMetadata.ts"), functionMetadataSource(functions));
  await writeFile(path.join(generatedDir, "deploymentSchema.ts"), deploymentSchemaSource(analysis.schema));
  await writeFile(path.join(generatedDir, "worker.ts"), workerSource());
  await cleanupStaleGeneratedEntries(generatedDir, [
    "api.ts",
    "dataModel.ts",
    "deploymentSchema.ts",
    "functionMetadata.ts",
    "functionRegistry.ts",
    "server.ts",
    "worker.ts",
  ]);
}

function functionPath(fn: AnalyzedFunction): string {
  return fn.exportName === "default" ? fn.moduleName : `${fn.moduleName}:${fn.exportName}`;
}

function referenceMetadataMapSource(modules: AnalyzedModule[]): Record<string, unknown> {
  return Object.fromEntries(
    modules.flatMap(module =>
      module.functions.flatMap(fn => {
        const partition = runnablePartition(fn);
        if (partition === null) return [];
        return [[
          functionPath(fn),
          { partition },
        ]];
      }),
    ),
  );
}

function runnablePartition(
  fn: AnalyzedFunction,
): AnalyzedFunctionPartitionPolicy | AnalyzedFunctionPartitionCreateRootPolicy | null {
  if (fn.partition === null || fn.partition === undefined) return null;
  if (fn.partition.type === "partition") return fn.partition;
  if (fn.partition.type === "partitionCreateRoot") return fn.partition;
  throw new Error(
    `${functionPath(fn)}.partition: unresolved partition root policy reached final codegen.`,
  );
}

async function cleanupStaleGeneratedEntries(
  generatedDir: string,
  writtenFiles: string[],
): Promise<void> {
  const entries = await readdir(generatedDir, { withFileTypes: true });
  await Promise.all(
    entries
      .filter(entry => !writtenFiles.includes(entry.name))
      .map(entry => rm(path.join(generatedDir, entry.name), { recursive: true, force: true })),
  );
}
