import type { Dirent } from "node:fs";
import { cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import {
  generatedProjectWorkerExecutorBridgeSource,
} from "flarex-backend/artifact-runtime";
import type {
  DeploymentAnalysis as BackendDeploymentAnalysis,
} from "flarex-backend/types";
import { selectorNameForPartitionField } from "flarex-protocol/partition-selector";
import {
  listFunctionModules,
  type AnalyzedFunction,
  type AnalyzedFunctionPartitionCreateRootPolicy,
  type AnalyzedFunctionPartitionPolicy,
  type AnalyzedModule,
  type AnalyzedSchema,
  type DeploymentAnalysis,
  type FunctionModule,
} from "./analyze.ts";
import {
  devFinishPushErrorMessage,
  devFinishPushRejectionHint,
  devPushStatusErrorMessage,
  LocalExecutionArtifactBackendAnalyzer,
  type BackendPushCoordinator,
  type BackendSourceAnalyzer,
  type DevFinishPushResponse,
  type DevPushStatus,
} from "./backendPush.ts";
import {
  bundleSourcePackage,
  type SourcePackage,
} from "./sourcePackage.ts";
import { errorMessageFromUnknown } from "./errorMessage.ts";

export type FlarexGenerateOptions = {
  root: string;
  appDir?: string;
  generatedDir?: string;
};

export type FlarexCodegenOptions = FlarexGenerateOptions & {
  pushCoordinator?: BackendPushCoordinator;
  sourceAnalyzer?: BackendSourceAnalyzer;
};

export type FlarexAnalyzedPushStatus = DevPushStatus & {
  state: "analyzed";
  analysis: BackendDeploymentAnalysis;
  codegenAnalysis: DeploymentAnalysis;
};

export type FlarexActivatedPushStatus = DevPushStatus & {
  state: "activated";
};

export type FlarexDeployOptions = FlarexGenerateOptions & {
  pushCoordinator: BackendPushCoordinator;
  beforeFinish?: (started: FlarexAnalyzedPushStatus) => Promise<void>;
};

export type FlarexDeployResult = {
  started: FlarexAnalyzedPushStatus;
  finished: FlarexActivatedPushStatus;
};

export type FlarexDeployRejectedFinishResponse =
  Extract<DevFinishPushResponse, { result: "rejected" }>;

export class FlarexDeployFinishRejectedError extends Error {
  readonly response: FlarexDeployRejectedFinishResponse;
  readonly remediation: string;

  constructor(response: FlarexDeployRejectedFinishResponse, message: string) {
    super(devFinishPushErrorMessage(response, message));
    this.name = "FlarexDeployFinishRejectedError";
    this.response = response;
    this.remediation = devFinishPushRejectionHint(response.code);
  }
}

export type FlarexGenerationContext = {
  options: FlarexGenerateOptions;
  appDir: string;
  generatedDir: string;
  functionsDir: string;
  functionModules: FunctionModule[];
};

const FINAL_GENERATED_FILE_NAMES = [
  "dataModel.ts",
  "server.ts",
  "api.ts",
  "functionRegistry.ts",
  "functionMetadata.ts",
  "deploymentSchema.ts",
  "worker.ts",
] as const;

export type FinalGeneratedFileName = (typeof FINAL_GENERATED_FILE_NAMES)[number];

const PRESERVED_GENERATED_ENTRIES = new Set(["ai"]);

export function isPreservedGeneratedEntry(name: string): boolean {
  return PRESERVED_GENERATED_ENTRIES.has(name);
}

export type GeneratedFile = {
  name: FinalGeneratedFileName;
  contents: string;
};

export type GeneratedFileWrite = GeneratedFile & {
  path: string;
};

export type StaleGeneratedEntry = {
  name: string;
  path: string;
  kind: "file" | "directory" | "other";
};

export type FlarexCodegenDryRun = {
  writes: readonly GeneratedFileWrite[];
  deletes: readonly StaleGeneratedEntry[];
};

function typedApi(modules: string[], metadataByPath: Record<string, unknown> = {}): string {
  const imports = modules
    .map(
      (moduleName, index) =>
        `import type * as module${index} from "../functions/${moduleName}";`,
    )
    .join("\n");
  const moduleTypes = modules
    .map((moduleName, index) => `  ${JSON.stringify(moduleName)}: typeof module${index};`)
    .join("\n");

  return `// Generated by flarex-dev. Do not edit.
import { createApi, justInternal, justPublic, type ApiFromModules } from "flarex/server";
${imports}

const fullApi = createApi(${JSON.stringify(metadataByPath, null, 2)}) as unknown as ApiFromModules<{
${moduleTypes}
}>;

export const api = justPublic(fullApi);
export const internal = justInternal(fullApi);
`;
}

function dataModelSource(): string {
  return `// Generated by flarex-dev. Do not edit.
import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
} from "flarex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type Doc<TableName extends TableNamesInDataModel<DataModel>> =
  DocumentByName<DataModel, TableName>;
export type TableNames = TableNamesInDataModel<DataModel>;
`;
}

function serverSource(schema?: AnalyzedSchema): string {
  const modelSource = schema === undefined
    ? dynamicPartitionModelSource()
    : concretePartitionModelSource(schema);
  const partitionScopesSource = schema === undefined
    ? dynamicPartitionScopesSource()
    : concretePartitionScopesSource(schema);
  return `// Generated by flarex-dev. Do not edit.
import {
  actionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  mutationGeneric,
  queryGeneric,
  workflowMutationGeneric,
  type ActionBuilder,
  type ActionCtx as GenericActionCtx,
  type MutationCtxForTables as GenericMutationCtxForTables,
  type MutationBuilder,
  type MutationCtx as GenericMutationCtx,
  type PartitionScopeMap,
  type QueryBuilder,
  type QueryCtx as GenericQueryCtx,
} from "flarex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as unknown as QueryBuilder<DataModel, "public">;
export const internalQuery =
  internalQueryGeneric as unknown as QueryBuilder<DataModel, "internal">;
export const mutation =
  mutationGeneric as unknown as MutationBuilder<DataModel, "public", "mutation", PartitionScopes>;
export const internalMutation =
  internalMutationGeneric as unknown as MutationBuilder<
    DataModel,
    "internal",
    "mutation",
    PartitionScopes
  >;
export const workflowMutation: MutationBuilder<
  DataModel,
  "public",
  "workflowMutation",
  PartitionScopes
> = workflowMutationGeneric as unknown as MutationBuilder<
  DataModel,
  "public",
  "workflowMutation",
  PartitionScopes
>;
export const action = actionGeneric as unknown as ActionBuilder<DataModel, "public">;

${modelSource}

${partitionScopesSource}

export type { DataModel } from "./dataModel";
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type PartitionMutationCtx<PartitionTable extends keyof PartitionScopes & string> =
  GenericMutationCtxForTables<
    DataModel,
    Extract<PartitionScopes[PartitionTable], keyof DataModel & string>
  >;
export type ActionCtx = GenericActionCtx<DataModel>;
`;
}

function functionMetadataSource(modules: readonly AnalyzedModule[]): string {
  const metadata = modules.flatMap(module =>
    module.functions.map(fn => ({
      path: functionPath(fn),
      kind: fn.kind,
      visibility: fn.visibility,
      args: fn.args,
      returns: fn.returns,
      partition: runnablePartition(fn),
      ...(fn.position === undefined ? {} : { position: fn.position }),
    })),
  );
  return `// Generated by flarex-dev. Do not edit.
import type { ValidatorJSON } from "flarex/values";

export type FunctionMetadata = {
  path: string;
  kind: "query" | "mutation" | "workflowMutation" | "action";
  visibility: "public" | "internal";
  args: ValidatorJSON;
  returns: ValidatorJSON | null;
  partition: {
    type: "partition";
    table: string;
    selector: string;
    partitionField: string;
    argField: string;
  } | {
    type: "partitionCreateRoot";
    table: string;
    partitionField: "_id";
  } | null;
  position?: {
    path: string;
    startLine: number;
    startColumn: number;
  };
};

export const functionMetadata: FunctionMetadata[] = ${JSON.stringify(metadata, null, 2)};

export default functionMetadata;
`;
}

function dynamicPartitionModelSource(): string {
  return `const partitionFieldForSelector = (selector: string) => {
  if (selector === "byId") return "_id";
  if (!selector.startsWith("by") || selector.length <= 2) return "partition";
  const suffix = selector.slice(2);
  return \`\${suffix[0].toLowerCase()}\${suffix.slice(1)}\`;
};

type DynamicPartitionSelector = (argField: string) => {
  type: "partition";
  table: string;
  selector: string;
  partitionField: string;
  argField: string;
};

type DynamicPartitionRoot = {
  type: "partitionRoot";
  table: string;
  partitionField: "_id";
} & Record<string, DynamicPartitionSelector>;

const dynamicPartitionTable = (table: string) => new Proxy({
  type: "partitionRoot",
  table,
  partitionField: "_id",
} as DynamicPartitionRoot, {
  get(_target, property) {
    if (typeof property !== "string") return undefined;
    if (property === "type") return "partitionRoot";
    if (property === "table") return table;
    if (property === "partitionField") return "_id";
    if (property === "toJSON") return undefined;
    return (argField: string) => ({
      type: "partition",
      table,
      selector: property,
      partitionField: partitionFieldForSelector(property),
      argField,
    } as const);
  },
}) as DynamicPartitionRoot;

export const model = new Proxy({}, {
  get(_target, property) {
    if (typeof property !== "string") return undefined;
    return dynamicPartitionTable(property);
  },
}) as Record<string, ReturnType<typeof dynamicPartitionTable>>;`;
}

function concretePartitionModelSource(schema: AnalyzedSchema): string {
  const entries = schema.tables
    .flatMap(table => {
      if (table.placement.kind !== "partitionBy") return [];
      const selector = selectorNameForPartitionField(table.placement.field);
      return [`  ${propertyKey(table.name)}: {
    type: "partitionRoot",
    table: ${JSON.stringify(table.name)},
    partitionField: ${JSON.stringify(table.placement.field)},
    ${propertyKey(selector)}: (argField: string) => ({
      type: "partition",
      table: ${JSON.stringify(table.name)},
      selector: ${JSON.stringify(selector)},
      partitionField: ${JSON.stringify(table.placement.field)},
      argField,
    } as const),
  },`];
    });
  return `export const model = {
${entries.join("\n")}
} as const;`;
}

function dynamicPartitionScopesSource(): string {
  return `export type PartitionScopes = PartitionScopeMap<DataModel>;`;
}

function concretePartitionScopesSource(schema: AnalyzedSchema): string {
  const scopes = partitionScopesForSchema(schema);
  const entries = Object.entries(scopes).map(([root, tables]) => {
    const writable = tables.map(table => JSON.stringify(table)).join(" | ");
    return `  ${propertyKey(root)}: ${writable.length === 0 ? "never" : writable};`;
  });
  return `export type PartitionScopes = {
${entries.join("\n")}
};
type _PartitionScopesCheck = PartitionScopes extends PartitionScopeMap<DataModel> ? true : never;`;
}

function partitionScopesForSchema(schema: AnalyzedSchema): Record<string, string[]> {
  const tableByName = new Map(schema.tables.map(table => [table.name, table] as const));
  const roots = schema.tables
    .filter(table => table.placement.kind === "partitionBy")
    .map(table => table.name);
  const scopes = Object.fromEntries(roots.map(root => [root, [root]])) as Record<string, string[]>;

  for (const table of schema.tables) {
    if (table.placement.kind !== "colocateWith") continue;
    const root = partitionRootForTable(table.placement.table, tableByName);
    if (root === null) continue;
    scopes[root] ??= [root];
    if (!scopes[root].includes(table.name)) scopes[root].push(table.name);
  }

  return Object.fromEntries(
    Object.entries(scopes).map(([root, tables]) => [root, tables.sort()]),
  );
}

function partitionRootForTable(
  tableName: string,
  tableByName: Map<string, AnalyzedSchema["tables"][number]>,
  seen = new Set<string>(),
): string | null {
  if (seen.has(tableName)) return null;
  seen.add(tableName);
  const table = tableByName.get(tableName);
  if (table === undefined) return null;
  if (table.placement.kind === "partitionBy") return table.name;
  if (table.placement.kind === "colocateWith") {
    return partitionRootForTable(table.placement.table, tableByName, seen);
  }
  return null;
}

function propertyKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function functionRegistrySource(modules: readonly AnalyzedModule[]): string {
  const activeModules = modules.filter(module => module.functions.length > 0);
  const imports = activeModules
    .map(
      (module, index) => `import * as module${index} from "../functions/${module.moduleName}";`,
    )
    .join("\n");
  const registry = activeModules
    .flatMap((module, moduleIndex) =>
      module.functions.map(
        fn =>
          `  ${JSON.stringify(functionPath(fn))}: module${moduleIndex}.${fn.exportName},`,
      ),
    )
    .join("\n");
  return `// Generated by flarex-dev. Do not edit.
import type { RegisteredFunction } from "flarex/server";
${imports}

export const functions: Record<string, RegisteredFunction> = {
${registry}
};
`;
}

function deploymentSchemaSource(schema: AnalyzedSchema): string {
  return `// Generated by flarex-dev. Do not edit.
import type { ValidatorJSON } from "flarex/values";

type DeploymentSchema = {
  version: number;
  tables: Array<{
    tableId: number;
    name: string;
    state?: "active" | "hidden" | "deleted";
    validator: ValidatorJSON;
    placement:
      | { kind: "partitionBy"; field: string }
      | { kind: "colocateWith"; table: string; field: string }
      | { kind: "global" };
  }>;
  indexes: Array<{
    indexId: number;
    tableId: number;
    name: string;
    fields: string[];
    state?: "enabled" | "staged" | "disabled";
  }>;
};

export const deploymentSchema: DeploymentSchema = ${JSON.stringify(schema, null, 2)};

export default deploymentSchema;
`;
}

function workerSource(): string {
  return `// Generated by flarex-dev. Do not edit.
import { DurableObject } from "cloudflare:workers";
import {
  createQueryInitializer,
  getFunctionName,
  parseFlarexId,
  validateValue,
  type DatabaseQueryRequest,
  type DatabaseQueryResult,
  type DatabaseWriter,
} from "flarex/server";
import { deploymentSchema } from "./deploymentSchema";
import { functionMetadata } from "./functionMetadata";
import { functions } from "./functionRegistry";

const functionMetadataByPath = new Map(
  functionMetadata.map(metadata => [metadata.path, metadata] as const),
);

const tableMetadata = Object.fromEntries(
  deploymentSchema.tables
    .filter(table => table.state !== "deleted")
    .map(table => [table.name, { tableId: table.tableId, name: table.name }]),
) as Record<string, { tableId: number; name: string }>;

const tableNamesById = new Map(
  Object.values(tableMetadata).map(table => [table.tableId, table.name] as const),
);

export interface Env {
  CONNECTIONS: DurableObjectNamespace<ConnectionDO>;
  FLAREX_BACKEND: Fetcher;
  FLAREX_DEPLOYMENT_ID?: string;
  FLAREX_PROJECT_ID?: string;
  FLAREX_EXECUTOR_TRANSPORT?: string;
  FLAREX_EXECUTOR_TOKEN?: string;
  FLAREX_INVOKE_MAX_ATTEMPTS?: string;
  FLAREX_INTERNAL_TOKEN?: string;
}

export class ConnectionDO extends DurableObject<Env> {
  async fetch(request: Request): Promise<Response> {
    if (request.headers.get("Upgrade") !== "websocket") {
      return Response.json({ service: "flarex-connection", status: "ok" });
    }
    const pair = new WebSocketPair();
    const [client, server] = Object.values(pair) as [WebSocket, WebSocket];
    this.ctx.acceptWebSocket(server);
    server.send(JSON.stringify({ type: "Connected", protocol: "flarex-v0" }));
    return new Response(null, { status: 101, webSocket: client });
  }
}

function validateFunctionReturn(
  validator: (typeof functionMetadata)[number]["returns"],
  value: unknown,
): void {
  if (validator === null) return;
  validateValue(validator, value, "$return", { validateId: validateTableNameId });
}

function validateTableNameId(tableName: string, value: string, path: string): void {
  const expected = tableMetadata[tableName];
  if (!expected) {
    throw new Error(\`\${path}: Unknown table \${tableName} for ID validator.\`);
  }
  const parsed = parseFlarexId(value);
  if (parsed === null) {
    throw new Error(\`\${path}: Expected an ID for table \${tableName}.\`);
  }
  if (parsed.tableId !== expected.tableId) {
    const actualTableName = tableNamesById.get(parsed.tableId);
    const suffix = actualTableName === undefined ? "" : \`, got an ID for table \${actualTableName}\`;
    throw new Error(\`\${path}: Expected an ID for table \${tableName}\${suffix}.\`);
  }
}

${generatedProjectWorkerExecutorBridgeSource({ backendBaseUrl: "https://flarex-backend.internal" })}
class InvokeRequestJsonError extends Error {
  readonly cause: unknown;

  constructor(cause: unknown) {
    super("Invoke request body must be valid JSON.");
    this.name = "InvokeRequestJsonError";
    this.cause = cause;
  }
}

function authorizeInternalRequest(request: Request, env: Env): Response | null {
  if (env.FLAREX_INTERNAL_TOKEN === undefined) return null;
  const expected = \`Bearer \${env.FLAREX_INTERNAL_TOKEN}\`;
  if (request.headers.get("authorization") === expected) return null;
  return Response.json({ error: "Unauthorized internal Flarex request." }, { status: 401 });
}

async function readInvokeRequestJson(request: Request): Promise<InvokeBody> {
  try {
    return await request.json<InvokeBody>();
  } catch (cause) {
    throw new InvokeRequestJsonError(cause);
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/__flarex_internal/")) {
      const unauthorized = authorizeInternalRequest(request, env);
      if (unauthorized !== null) return unauthorized;
    }
    if (url.pathname === "/sync") {
      const session = request.headers.get("x-flarex-session") ?? crypto.randomUUID();
      return env.CONNECTIONS.getByName(session).fetch(request);
    }
    if (
      (url.pathname === "/invoke" || url.pathname === "/__flarex_internal/invoke") &&
      request.method === "POST"
    ) {
      try {
        return Response.json(
          await invokeWithBackend(await readInvokeRequestJson(request), env, request),
        );
      } catch (error) {
        return Response.json(
          { error: error instanceof Error ? error.message : String(error) },
          { status: 400 },
        );
      }
    }
    if (url.pathname === "/health") {
      return Response.json({ service: "flarex", status: "ok" });
    }
    if (url.pathname === "/__flarex_internal/metadata") {
      return Response.json({ schema: deploymentSchema, functions: functionMetadata });
    }
    return Response.json({ error: "Not implemented." }, { status: 501 });
  },
} satisfies ExportedHandler<Env>;
`;
}

export async function generateFlarex(options: FlarexCodegenOptions): Promise<void> {
  const context = await initialCodegen(options);
  const sourcePackage = await bundleFlarexSourcePackage(context);
  const analysis = await analyzeFlarexSourcePackage(sourcePackage, options);
  await finalCodegen(context, analysis);
}

export async function deployFlarex(options: FlarexDeployOptions): Promise<FlarexDeployResult> {
  const context = await initialCodegen(options);
  const sourcePackage = await bundleFlarexSourcePackage(context);
  const started = analyzedPushStatus(await options.pushCoordinator.start(sourcePackage));
  await finalCodegen(context, started.codegenAnalysis);
  try {
    await options.beforeFinish?.(started);
  } catch (error) {
    try {
      await options.pushCoordinator.abandon?.(started.pushId, {
        reason: deployAbandonReason(error),
      });
    } catch {
      // Preserve the developer-facing validation failure. Abandon is cleanup.
    }
    throw error;
  }
  const finished = activatedPushStatus(await options.pushCoordinator.finish(started.pushId));
  return { started, finished };
}

export async function dryRunFlarexCodegen(
  options: FlarexCodegenOptions,
): Promise<FlarexCodegenDryRun> {
  const appDirOption = options.appDir ?? "flarex";
  const generatedDirOption = options.generatedDir ?? "_generated";
  if (path.isAbsolute(generatedDirOption)) {
    throw new Error("Dry-run codegen requires --generated-dir to be relative to the Flarex app directory.");
  }

  const appDir = path.resolve(options.root, appDirOption);
  const generatedDir = path.resolve(appDir, generatedDirOption);
  const tempRoot = await mkdtemp(path.join(tmpdir(), "flarex-codegen-dry-run-"));
  try {
    const tempAppDir = path.join(tempRoot, "flarex");
    await copyAppDirIfExists(appDir, tempAppDir);
    const context = await initialCodegen({
      root: tempRoot,
      appDir: "flarex",
      generatedDir: generatedDirOption,
    });
    const sourcePackage = await bundleFlarexSourcePackage(context);
    const analysis = await analyzeFlarexSourcePackage(sourcePackage, options);
    const files = finalGeneratedFiles(analysis);
    return {
      writes: await generatedFileWrites(generatedDir, files),
      deletes: await staleGeneratedEntries(generatedDir, files.map(file => file.name)),
    };
  } finally {
    await rm(tempRoot, { recursive: true, force: true });
  }
}

export async function analyzeFlarexSourcePackage(
  sourcePackage: SourcePackage,
  options: Pick<FlarexCodegenOptions, "pushCoordinator" | "sourceAnalyzer"> | BackendSourceAnalyzer | undefined = {},
): Promise<DeploymentAnalysis> {
  const analysisOptions = options ?? {};
  if ("analyze" in analysisOptions) {
    return (await analysisOptions.analyze(sourcePackage)).analysis;
  }
  if (analysisOptions.pushCoordinator !== undefined) {
    const started = await analysisOptions.pushCoordinator.start(sourcePackage);
    return analyzedPushStatus(started).codegenAnalysis;
  }
  const sourceAnalyzer = analysisOptions.sourceAnalyzer ?? new LocalExecutionArtifactBackendAnalyzer();
  return (await sourceAnalyzer.analyze(sourcePackage)).analysis;
}

function analyzedPushStatus(started: DevPushStatus): FlarexAnalyzedPushStatus {
  if (started.state !== "analyzed") {
    throw new Error(`Flarex push ${started.pushId} is not ready for codegen: ${started.state}.`);
  }
  if (started.analysis === undefined) {
    throw new Error(`Flarex push ${started.pushId} did not return backend analysis.`);
  }
  if (started.codegenAnalysis === undefined) {
    throw new Error(`Flarex push ${started.pushId} did not return codegen analysis.`);
  }
  return {
    ...started,
    state: "analyzed",
    analysis: started.analysis,
    codegenAnalysis: started.codegenAnalysis,
  };
}

function activatedPushStatus(finished: DevFinishPushResponse): FlarexActivatedPushStatus {
  if (finished.result !== "activated") {
    throw new FlarexDeployFinishRejectedError(
      finished,
      `Flarex push ${finished.push.pushId} did not activate`,
    );
  }
  return {
    ...finished.push,
  };
}

function deployAbandonReason(error: unknown): string {
  const message = errorMessageFromUnknown(error);
  return message.length === 0
    ? "Generated output validation failed before activation."
    : `Generated output validation failed before activation: ${message}`;
}

export async function initialCodegen(
  options: FlarexGenerateOptions,
): Promise<FlarexGenerationContext> {
  const appDir = path.resolve(options.root, options.appDir ?? "flarex");
  const generatedDir = path.resolve(appDir, options.generatedDir ?? "_generated");
  const functionsDir = path.join(appDir, "functions");
  const functionModules = await listFunctionModules(functionsDir);
  const moduleNames = functionModules.map(module => module.moduleName);
  await mkdir(generatedDir, { recursive: true });

  await writeFile(path.join(generatedDir, "dataModel.ts"), dataModelSource());
  await writeFile(path.join(generatedDir, "server.ts"), serverSource());
  await writeFile(path.join(generatedDir, "api.ts"), typedApi(moduleNames));
  return { options, appDir, generatedDir, functionsDir, functionModules };
}

export function bundleFlarexSourcePackage(
  context: FlarexGenerationContext,
): Promise<SourcePackage> {
  return bundleSourcePackage({
    appDir: context.appDir,
    functionModules: context.functionModules,
  });
}

export async function finalCodegen(
  context: FlarexGenerationContext,
  analysis: DeploymentAnalysis,
): Promise<void> {
  const { generatedDir } = context;
  const files = finalGeneratedFiles(analysis);
  for (const file of files) {
    await writeFile(path.join(generatedDir, file.name), file.contents);
  }
  await cleanupStaleGeneratedEntries(generatedDir, files.map(file => file.name));
}

export function finalGeneratedFiles(analysis: DeploymentAnalysis): readonly GeneratedFile[] {
  const functions = analysis.functions;
  return [
    { name: "dataModel.ts", contents: dataModelSource() },
    { name: "server.ts", contents: serverSource(analysis.schema) },
    {
      name: "api.ts",
      contents: typedApi(
        functions.map(module => module.moduleName),
        referenceMetadataMapSource(functions),
      ),
    },
    { name: "functionRegistry.ts", contents: functionRegistrySource(functions) },
    { name: "functionMetadata.ts", contents: functionMetadataSource(functions) },
    { name: "deploymentSchema.ts", contents: deploymentSchemaSource(analysis.schema) },
    { name: "worker.ts", contents: workerSource() },
  ];
}

export async function generatedFileWrites(
  generatedDir: string,
  files: readonly GeneratedFile[],
): Promise<readonly GeneratedFileWrite[]> {
  const writes = await Promise.all(
    files.map(async file => {
      const filePath = path.join(generatedDir, file.name);
      const existing = await readFileIfExists(filePath);
      return existing === file.contents ? undefined : { ...file, path: filePath };
    }),
  );
  return writes.filter((write): write is GeneratedFileWrite => write !== undefined);
}

function functionPath(fn: AnalyzedFunction): string {
  return fn.exportName === "default" ? fn.moduleName : `${fn.moduleName}:${fn.exportName}`;
}

function referenceMetadataMapSource(modules: readonly AnalyzedModule[]): Record<string, unknown> {
  return Object.fromEntries(
    modules.flatMap(module =>
      module.functions.flatMap(fn => {
        const partition = runnablePartition(fn);
        if (partition === null) return [];
        return [[
          functionPath(fn),
          { partition },
        ]];
      }),
    ),
  );
}

function runnablePartition(
  fn: AnalyzedFunction,
): AnalyzedFunctionPartitionPolicy | AnalyzedFunctionPartitionCreateRootPolicy | null {
  if (fn.partition === null || fn.partition === undefined) return null;
  if (fn.partition.type === "partition") return fn.partition;
  if (fn.partition.type === "partitionCreateRoot") return fn.partition;
  throw new Error(
    `${functionPath(fn)}.partition: unresolved partition root policy reached final codegen.`,
  );
}

async function cleanupStaleGeneratedEntries(
  generatedDir: string,
  writtenFiles: string[],
): Promise<void> {
  const entries = await staleGeneratedEntries(generatedDir, writtenFiles);
  await Promise.all(
    entries.map(entry => rm(entry.path, { recursive: true, force: true })),
  );
}

export async function staleGeneratedEntries(
  generatedDir: string,
  writtenFiles: readonly string[],
): Promise<readonly StaleGeneratedEntry[]> {
  const entries = await readdirIfExists(generatedDir);
  return entries
    .filter(entry => !isPreservedGeneratedEntry(entry.name))
    .filter(entry => !writtenFiles.includes(entry.name))
    .map(entry => ({
      name: entry.name,
      path: path.join(generatedDir, entry.name),
      kind: generatedEntryKind(entry),
    }));
}

function generatedEntryKind(entry: Dirent): StaleGeneratedEntry["kind"] {
  if (entry.isFile()) return "file";
  if (entry.isDirectory()) return "directory";
  return "other";
}

async function readFileIfExists(filePath: string): Promise<string | undefined> {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (isMissingPathError(error)) return undefined;
    throw error;
  }
}

async function readdirIfExists(dirPath: string): Promise<Dirent[]> {
  try {
    return await readdir(dirPath, { withFileTypes: true });
  } catch (error) {
    if (isMissingPathError(error)) return [];
    throw error;
  }
}

async function copyAppDirIfExists(sourceDir: string, targetDir: string): Promise<void> {
  try {
    await cp(sourceDir, targetDir, { recursive: true });
  } catch (error) {
    if (isMissingPathError(error)) {
      await mkdir(targetDir, { recursive: true });
      return;
    }
    throw error;
  }
}

function isMissingPathError(error: unknown): boolean {
  return isErrorWithCode(error) && error.code === "ENOENT";
}

function isErrorWithCode(error: unknown): error is Error & { code: unknown } {
  return error instanceof Error && "code" in error;
}
