import { Miniflare } from "miniflare";
import type {
  ExecutionArtifactMaterializer,
  MaterializedExecutionArtifactPayload,
  MaterializedExecutionArtifact,
} from "flarex-backend/artifact-runtime";
import type { InvokeResponse } from "flarex-backend/types";

export type RuntimeBackendDispatcher = (request: Request) => Response | Promise<Response>;

export type LocalMiniflareExecutionArtifactMaterializerOptions = {
  backend: RuntimeBackendDispatcher;
  internalToken?: string;
  compatibilityDate?: string;
};

export class LocalMiniflareExecutionArtifactMaterializer implements ExecutionArtifactMaterializer {
  private readonly backend: RuntimeBackendDispatcher;
  private readonly internalToken: string | undefined;
  private readonly compatibilityDate: string;

  constructor(options: LocalMiniflareExecutionArtifactMaterializerOptions) {
    this.backend = options.backend;
    this.internalToken = options.internalToken;
    this.compatibilityDate = options.compatibilityDate ?? "2026-06-14";
  }

  async materialize(
    payload: MaterializedExecutionArtifactPayload,
  ): Promise<MaterializedExecutionArtifact> {
    const artifact = new Miniflare({
      modules: [
        {
          type: "ESModule",
          path: "worker.js",
          contents: runtimeWorkerSource(payload.sourcePackage.execution),
        },
        ...payload.sourcePackage.modules.map(module => {
          if (module.source === undefined) {
            throw new Error(`Source package module ${module.path} has no source.`);
          }
          return {
            type: "ESModule" as const,
            path: module.path,
            contents: module.source,
          };
        }),
      ],
      compatibilityDate: this.compatibilityDate,
      ...(this.internalToken === undefined
        ? {}
        : { bindings: { FLAREX_INTERNAL_TOKEN: this.internalToken } }),
      serviceBindings: {
        FLAREX_BACKEND: async (request: Request) => this.backend(request),
      },
    });
    return new LocalMiniflareMaterializedExecutionArtifact(artifact, this.internalToken);
  }
}

class LocalMiniflareMaterializedExecutionArtifact implements MaterializedExecutionArtifact {
  private readonly artifact: Miniflare;
  private readonly internalToken: string | undefined;

  constructor(artifact: Miniflare, internalToken: string | undefined) {
    this.artifact = artifact;
    this.internalToken = internalToken;
  }

  async invoke(payload: MaterializedExecutionArtifactPayload): Promise<InvokeResponse> {
    const response = await this.artifact.dispatchFetch(
      "https://flarex-artifact.internal/__flarex_internal/invoke",
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "x-flarex-artifact-id": payload.ref.artifactId,
          "x-flarex-source-package-hash": payload.ref.sourcePackageHash,
          ...(this.internalToken === undefined
            ? {}
            : { authorization: `Bearer ${this.internalToken}` }),
        },
        body: JSON.stringify({
          deploymentId: payload.deploymentId,
          ...payload.request,
        }),
      },
    );
    const body = await response.json().catch(() => null);
    if (!response.ok) {
      const message =
        typeof body === "object" && body !== null && "error" in body
          ? String((body as { error: unknown }).error)
          : `Materialized execution artifact failed with status ${response.status}`;
      const error = new Error(message) as Error & { status?: number };
      error.status = response.status;
      throw error;
    }
    return body as InvokeResponse;
  }

  async dispose(): Promise<void> {
    await this.artifact.dispose();
  }
}

function runtimeWorkerSource(executionModule: string): string {
  return `// Generated by flarex-dev for local execution-artifact runtime materialization.
const executionModulePromise = import(${JSON.stringify(`./${executionModule}`)});

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/__flarex_internal/")) {
      const unauthorized = authorizeInternalRequest(request, env);
      if (unauthorized !== null) return unauthorized;
    }
    if (url.pathname === "/__flarex_internal/invoke" && request.method === "POST") {
      try {
        return Response.json(await invokeWithBackend(await request.json(), env, request));
      } catch (error) {
        return Response.json({ error: errorMessage(error) }, { status: 400 });
      }
    }
    return Response.json({ error: "Not found." }, { status: 404 });
  },
};

function authorizeInternalRequest(request, env) {
  if (env.FLAREX_INTERNAL_TOKEN === undefined) return null;
  const expected = \`Bearer \${env.FLAREX_INTERNAL_TOKEN}\`;
  if (request.headers.get("authorization") === expected) return null;
  return Response.json({ error: "Unauthorized internal Flarex request." }, { status: 401 });
}

async function invokeWithBackend(body, env, request) {
  const fn = await resolveFunction(body.path);
  const kind = functionKind(fn);
  if (kind !== "query" && kind !== "mutation") {
    throw new Error(\`\${kind ?? "unknown"} execution is not implemented by execution artifacts.\`);
  }
  const deploymentId = request.headers.get("x-flarex-deployment") ?? body.deploymentId;
  if (!deploymentId) throw new Error("A deploymentId or x-flarex-deployment header is required.");
  const partitionKey = request.headers.get("x-flarex-partition") ?? body.partitionKey;
  if (!partitionKey) throw new Error("A partitionKey or x-flarex-partition header is required.");

  const start = await postBackend(env.FLAREX_BACKEND, \`/deployments/\${deploymentId}/executions/start\`, {
    path: body.path,
    args: body.args ?? null,
    kind,
    partitionKey,
    ...(body.idempotencyKey === undefined ? {} : { idempotencyKey: body.idempotencyKey }),
  });
  try {
    const handler = handlerFor(fn);
    const db = databaseForSession(env.FLAREX_BACKEND, deploymentId, start.sessionId, start.kind);
    const value = await handler({ db }, body.args ?? null);
    return await postBackend(env.FLAREX_BACKEND, \`/deployments/\${deploymentId}/executions/\${start.sessionId}/finish\`, {
      value,
    });
  } catch (error) {
    await postBackend(env.FLAREX_BACKEND, \`/deployments/\${deploymentId}/executions/\${start.sessionId}/abort\`, {}).catch(
      () => undefined,
    );
    throw error;
  }
}

async function resolveFunction(path) {
  const separator = path.indexOf(":");
  const moduleName = separator === -1 ? path : path.slice(0, separator);
  const exportName = separator === -1 ? "default" : path.slice(separator + 1);
  const executionModule = await executionModulePromise;
  const module = executionModule.default?.[moduleName];
  const fn = module?.[exportName];
  if (fn === undefined) throw new Error(\`Unknown Flarex function: \${path}\`);
  return fn;
}

function functionKind(value) {
  if (!isRecord(value)) return null;
  const kinds = [
    ["isQuery", "query"],
    ["isMutation", "mutation"],
    ["isWorkflowMutation", "workflowMutation"],
    ["isAction", "action"],
  ];
  const marked = kinds.filter(([marker]) => marker in value);
  return marked.length === 1 ? marked[0][1] : null;
}

function handlerFor(value) {
  if (isRecord(value) && "_handler" in value && typeof value._handler === "function") {
    return value._handler;
  }
  if (typeof value === "function") return value;
  throw new Error("Flarex function handler is not executable.");
}

function databaseForSession(backend, deploymentId, sessionId, kind) {
  const syscall = (body) =>
    postBackend(backend, \`/deployments/\${deploymentId}/executions/\${sessionId}/syscall\`, body);
  const query = (queryRequest) =>
    syscall({ op: "query", request: queryRequest });
  return {
    get: id => syscall({ op: "get", id }),
    query: table => createQueryInitializer(table, query),
    insert: async (table, value) => {
      if (kind !== "mutation") throw new Error("Cannot insert during a query.");
      return await syscall({ op: "insert", table, value });
    },
    patch: async (id, value) => {
      if (kind !== "mutation") throw new Error("Cannot patch during a query.");
      await syscall({ op: "patch", id, value });
    },
    delete: async id => {
      if (kind !== "mutation") throw new Error("Cannot delete during a query.");
      await syscall({ op: "delete", id });
    },
  };
}

function createQueryInitializer(table, query, index, range, limit, cursor, order = "asc") {
  const execute = (nextLimit, nextCursor) => {
    const resolvedLimit = nextLimit ?? limit;
    const resolvedCursor = nextCursor ?? cursor;
    return query({
      table,
      ...(index === undefined ? {} : { index }),
      ...(range === undefined ? {} : { range }),
      ...(resolvedLimit === undefined ? {} : { limit: resolvedLimit }),
      ...(resolvedCursor === undefined ? {} : { cursor: resolvedCursor }),
      order,
    });
  };
  return {
    withIndex: (nextIndex, buildRange) => {
      const builder = rangeBuilder();
      const nextRange = buildRange === undefined ? undefined : buildRange(builder);
      return createQueryInitializer(table, query, nextIndex, nextRange, limit, cursor, order);
    },
    order: nextOrder => createQueryInitializer(table, query, index, range, limit, cursor, nextOrder),
    collect: async () => (await execute()).page,
    take: async count => (await execute(count)).page,
    first: async () => (await execute(1)).page[0] ?? null,
    unique: async () => {
      const documents = (await execute(2)).page;
      if (documents.length > 1) throw new Error("Query returned more than one document.");
      return documents[0] ?? null;
    },
    paginate: options => execute(options.numItems, options.cursor === null ? undefined : options.cursor),
  };
}

function rangeBuilder(expressions = []) {
  return {
    expressions,
    eq: (field, value) => rangeBuilder([...expressions, { op: "eq", field, value }]),
    gt: (field, value) => rangeBuilder([...expressions, { op: "gt", field, value }]),
    gte: (field, value) => rangeBuilder([...expressions, { op: "gte", field, value }]),
    lt: (field, value) => rangeBuilder([...expressions, { op: "lt", field, value }]),
    lte: (field, value) => rangeBuilder([...expressions, { op: "lte", field, value }]),
  };
}

async function postBackend(backend, path, body) {
  const response = await backend.fetch(\`https://flarex-backend.internal\${path}\`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const value = await response.json().catch(() => null);
  if (!response.ok) {
    const message =
      typeof value === "object" && value !== null && "error" in value
        ? String(value.error)
        : \`Backend request failed with status \${response.status}\`;
    throw new Error(message);
  }
  return value;
}

function isRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function errorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}
`;
}
