/**
 * Drizzle Kit's authoritative live schema surface.
 *
 * Historical table objects can remain importable from `schema.ts` for the
 * explicitly retained migration-drain readers without making Drizzle treat
 * those displaced tables as part of a fresh deployment.
 */
export {
  commits,
  deploymentPackages,
  deployments,
  documentFreshnessVersions,
  documents,
  freshnessProcessedEvents,
  fxAppEdgeAdjacencyVersions,
  fxAppEdgeCurrent,
  fxAppIndexEntryCurrent,
  fxAppIndexEntryRevisions,
  fxAppRowCurrent,
  fxAppRowRevisions,
  fxAppUniqueKeys,
  fxControlApplicationSchemaAuthoritiesV1,
  fxControlApplicationManifestSchemaBindings,
  fxControlBoundApplicationSchemas,
  fxControlEdgeDefinitions,
  fxControlIndexDefinitions,
  fxControlIndexes,
  fxControlRelations,
  fxControlSchemaVersionRelationBindings,
  fxControlSchemaVersionIndexBindings,
  fxControlSchemaVersionUniqueConstraintBindings,
  fxControlSchemaVersionUniqueConstraintSets,
  fxControlSchemaVersions,
  fxControlScopeProvisioning,
  fxControlScopes,
  fxControlTables,
  fxControlUniqueConstraintDefinitions,
  fxControlUniqueConstraints,
  fxSystemApplicationActionInvocationsV1,
  fxSystemApplicationAnalysesV1,
  fxSystemApplicationCandidatesV1,
  fxSystemApplicationFunctionsV1,
  fxSystemApplicationPublicationsV1,
  fxSystemApplicationReadinessFunctionsV1,
  fxSystemApplicationReadinessV1,
  fxSystemApplicationRelationSemanticReadiness,
  fxSystemApplicationRelationSemanticValidations,
  fxSystemEdgeDefinitionBuilds,
  fxSystemEdgeDefinitionReadiness,
  fxSystemApplicationRevisionSchemasV1,
  fxSystemApplicationRevisionsV2,
  fxSystemApplicationTaskCatalogsV1,
  fxSystemApplicationTaskDefinitionsV1,
  fxSystemAppSchemaCandidateValidations,
  fxSystemCommitAppRowChanges,
  fxSystemCommitRelationAdjacencyChanges,
  fxSystemCommits,
  fxSystemDurableTaskAttemptIdentitiesV1,
  fxSystemDurableTaskComputeCancellationsV1,
  fxSystemDurableTaskComputeDispatchesV1,
  fxSystemDurableTaskComputePendingV1,
  fxSystemDurableTaskDefinitionRevisionsV1,
  fxSystemDurableTaskRepairSchedulerV1,
  fxSystemDurableTaskRequestedEffectsV1,
  fxSystemDurableTaskRunRequestsV1,
  fxSystemDurableTaskRunsV1,
  fxSystemExternalEffectAttemptsV1,
  fxSystemIdempotency,
  fxSystemIndexBuildStates,
  fxSystemPhysicalDefinitionLifecycles,
  fxSystemOutbox,
  fxSystemPointMutationRedeliveryScheduler,
  fxSystemRetainedHistoryScheduler,
  fxSystemScopeClocks,
  fxSystemSnapshotLeases,
  fxSystemTransactionExecutionClaims,
  fxSystemTransactionJournalIndexRanges,
  fxSystemTransactionJournalRelationIncomingDependencies,
  fxSystemTransactionJournalLatestReceipts,
  fxSystemTransactionJournalPoints,
  fxSystemTransactionJournals,
  fxSystemTransactionJournalWriteEvents,
  fxSystemTransactionSessions,
  fxSystemUniqueConstraintSetBuilds,
  indexes,
  invokeSessionDocumentReads,
  invokeSessionDocumentWrites,
  invokeSessionIndexReads,
  invokeSessions,
  invokeSessionTableReads,
  leases,
  liveQueryConnections,
  liveQueryDeliveries,
  liveQuerySubscriptions,
  outbox,
  persistenceGlobals,
  readOnly,
  tableFreshnessVersions,
} from "./schema";

export {
  fxSystemApplicationFunctions,
  fxSystemApplicationPublications,
  fxSystemApplicationReadiness,
  fxSystemApplicationReadinessFunctions,
  fxSystemApplicationReadinessRelations,
  fxSystemApplicationRevisionSchemas,
  fxSystemApplicationTaskCatalogs,
  fxSystemApplicationTaskDefinitions,
} from "./applicationRelationSchema";

export {
  fxSystemApplicationActivations,
  fxSystemApplicationActiveHeads,
} from "./applicationActivationSchema";

export {
  fxControlFrameworkSchemaArtifactDependencies,
  fxControlFrameworkSchemaArtifacts,
} from "./frameworkSchema/artifact/schema";
